; wEventFlags bit flags

	const_def

; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8 ; 7

; Gym Leader TM gifts
	const EVENT_GOT_TM18_RAIN_DANCE
	const EVENT_GOT_TM60_HEX
	const EVENT_GOT_TM69_U_TURN
	const EVENT_GOT_TM09_VENOSHOCK
	const EVENT_GOT_TM01_DYNAMICPUNCH
	const EVENT_GOT_TM53_ENERGY_BALL
	const EVENT_GOT_TM62_ACROBATICS
	const EVENT_GOT_TM02_DRAGON_CLAW ; 15

; HMs
	const EVENT_GOT_HM01_CUT
	const EVENT_GOT_HM02_FLY
	const EVENT_GOT_HM03_SURF
	const EVENT_GOT_HM04_STRENGTH
	const EVENT_GOT_HM05_WATERFALL ; 20

; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD ; 23

; Humilau City
	const EVENT_GOT_A_POKEMON
	const EVENT_TALKED_TO_MOM_AFTER_POKEMON
	const EVENT_GOT_SNIVY
	const EVENT_GOT_TEPIG
	const EVENT_GOT_OSHAWOTT
	const EVENT_GOT_HUMILAU_CITY_HEART_SCALE
	
; Route 22
	const EVENT_ROUTE_22_LASS_POTION
	
; Lacunosa Town
	const EVENT_GOT_BIANCAS_NUMBER
	const EVENT_GOT_LACUNOSA_PECHA_BERRY
	const EVENT_GOT_LACUNOSA_CHERI_BERRY
	
; Undella Town
	const EVENT_MET_MARLON_IN_UNDELLA ; 34
	
	const EVENT_BEAT_POKEMON_LEAGUE
	const EVENT_SAW_FIRST_HIDDEN_GROTTO
	const EVENT_BRED_AN_EGG
	const EVENT_GOT_SPIKY_EARED_PICHU
	const EVENT_NURSE_SAW_TRAINER_STAR
	const EVENT_BATTLE_TOWER_INTRO
	const EVENT_BATTLE_TOWER_CLOSED
	const EVENT_BATTLE_TOWER_OPEN
	
	const EVENT_INITIALIZED_EVENTS
	
	const_next 163

; HIDDEN ITEMS

; Giant Chasm
	const EVENT_GIANT_CHASM_1F_FULL_HEAL
	
; Route 13
	const EVENT_ROUTE_13_RED_SHARD
	const EVENT_ROUTE_13_BLUE_SHARD

; Lacunosa Town
	const EVENT_LACUNOSA_TOWN_ETHER

; Route 12
	const EVENT_ROUTE_12_FULL_HEAL

; Undella Town
	const EVENT_UNDELLA_TOWN_PEARL_1
	const EVENT_UNDELLA_TOWN_PEARL_2 ; 169
	
	const_next 500

; Phone events
	const EVENT_DAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_FREDDY_ASKED_FOR_PHONE_NUMBER
	const EVENT_ERIC_ASKED_FOR_PHONE_NUMBER
	const EVENT_LACEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_SOPHIE_ASKED_FOR_PHONE_NUMBER
	const EVENT_ARIANA_ASKED_FOR_PHONE_NUMBER
	const EVENT_CARLA_ASKED_FOR_PHONE_NUMBER
	const EVENT_CLARISSA_ASKED_FOR_PHONE_NUMBER
	const EVENT_JENNY_ASKED_FOR_PHONE_NUMBER
	const EVENT_MARCO_ASKED_FOR_PHONE_NUMBER
	const EVENT_PARKER_ASKED_FOR_PHONE_NUMBER
	const EVENT_DEAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_LOIS_ASKED_FOR_PHONE_NUMBER ; 512
	
	const_next 543

; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_5
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_GAMECUBE
	const EVENT_DECO_WII
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_RAICHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_CHIKORITA_DOLL
	const EVENT_DECO_CYNDAQUIL_DOLL
	const EVENT_DECO_TOTODILE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_MAREEP_DOLL
	const EVENT_DECO_TOGEPI_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_OCTILLERY_DOLL
	const EVENT_DECO_DITTO_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_ABRA_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_PINECO_DOLL
	const EVENT_DECO_MARILL_DOLL
	const EVENT_DECO_TEDDIURSA_DOLL
	const EVENT_DECO_MEOWTH_DOLL
	const EVENT_DECO_VULPIX_DOLL
	const EVENT_DECO_GROWLITHE_DOLL
	const EVENT_DECO_EEVEE_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL ; 598
	
	const_next 733

; Trainer Flags
; Gym Leaders
	const EVENT_BEAT_MARLON
	const EVENT_BEAT_SHAUNTAL
	const EVENT_BEAT_BURGH
	const EVENT_BEAT_ROXIE
	const EVENT_BEAT_CHEREN
	const EVENT_BEAT_CILAN
	const EVENT_BEAT_SKYLA
	const EVENT_BEAT_DRAYDEN ; 740
; Elite Four and Champion
	const EVENT_BEAT_ELITE_4_MARSHAL
	const EVENT_BEAT_ELITE_4_GRIMSLEY
	const EVENT_BEAT_ELITE_4_ELESA
	const EVENT_BEAT_ELITE_4_COLRESS
	const EVENT_BEAT_CHAMPION_JUNIPER
; Youngster
	const EVENT_BEAT_YOUNGSTER_R13
; Lass
	const EVENT_BEAT_LASS_R13
; Fisher
	const EVENT_BEAT_FISHER_UNDELLA_1
	const EVENT_BEAT_FISHER_UNDELLA_2
; School KidM
	const EVENT_BEAT_SCHOOL_KIDM_R13
; School KidF
	const EVENT_BEAT_SCHOOL_KIDF_R13
; SwimmerM
	const EVENT_BEAT_SWIMMERM_HUMILAU_GYM
; SwimmerF
	const EVENT_BEAT_SWIMMERF_HUMILAU_GYM
; Battle Facility Bosses
	const EVENT_BEAT_PALMER
	const EVENT_BEAT_THORTON
; Postgame Bosses
	const EVENT_BEAT_CYNTHIA
	const EVENT_BEAT_HILBERT_HILDA ; 757
	
	const_next 1486

; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.

; ITEM BALLS

; Humilau City
	const EVENT_HUMILAU_CITY_SHELL_BELL
	
	const EVENT_MARLONS_HOUSE_SNIVY_BALL
	const EVENT_MARLONS_HOUSE_TEPIG_BALL
	const EVENT_MARLONS_HOUSE_OSHAWOTT_BALL
	
; Route 22
	const EVENT_ROUTE_22_POTION
	
; Giant Chasm
	const EVENT_GIANT_CHASM_1F_PARALYZEHEAL
	
; Route 13
	const EVENT_ROUTE_13_POTION
	const EVENT_ROUTE_13_POKE_BALL
	const EVENT_ROUTE_13_SUPER_POTION
	const EVENT_ROUTE_13_RARE_CANDY
	const EVENT_ROUTE_13_NUGGET
	
; Route 12
	const EVENT_ROUTE_12_ANTIDOTE
	
; Undella Town
	const EVENT_UNDELLA_TOWN_FRIEND_BALL
	const EVENT_UNDELLA_TOWN_LUCKY_EGG ; 1499
	
; Decorations
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	
	const_next 1655

; PEOPLE

; Humilau City
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const EVENT_PLAYERS_HOUSE_1F_NEIGHBOR
	const EVENT_HUMILAU_CITY_PC_BLOCKER
	const EVENT_HUMILAU_CITY_BLOCKERS
	const EVENT_HUMILAU_CITY_ROAMING_BLOCKER
	const EVENT_MOMS_PARTNERS_HOUSE_NEIGHBOR
	
; Giant Chasm
	const EVENT_GIANT_CHASM_INFER
	
; Route 13
	const EVENT_ROUTE_13_BLOCKERS
	const EVENT_ROUTE_13_YOUNGSTER
	
; Route 12
	const EVENT_ROUTE_12_INFER
	const EVENT_ROUTE_12_MARLON
	
; Undella Town
	const EVENT_UNDELLA_TOWN_MARLON ; 1667
	
; Battle Tower
	const EVENT_BATTLE_TOWER_BATTLE_ROOM_YOUNGSTER
	
	const_next 2180

; Cut trees
	const EVENT_ROUTE_13_CUT_TREE ; 2180

	const_next $8ff
DEF NUM_EVENTS EQU const_value ; 2303
