; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const SPECIAL_MAP          ; 00
; Johto landmarks
	const HUMILAU_CITY         ; 01
	const ROUTE_21             ; 02
	const SEASIDE_CAVE         ; 03
	const MARINE_TUBE          ; 04
	const ROUTE_22             ; 05
	const GIANT_CHASM          ; 06
	const LACUNOSA_TOWN        ; 07
	const ROUTE_13             ; 08
	const UNDELLA_TOWN         ; 09
	const ROUTE_14             ; 0a
	const ABUNDANT_SHRINE      ; 0b
	const REVERSAL_MOUNTAIN    ; 0c
	const LENTIMAS_OUTSKIRT    ; 0d
	const STRANGE_HOUSE        ; 0e
	const LENTIMAS_TOWN        ; 0f
	const LOSTLORN_FOREST      ; 10
	const UNKNOWN_AREA         ; 11
	const ROUTE_15             ; 12
	const MARVELOUS_BRIDGE     ; 13
	const ROUTE_16             ; 14
	const NIMBASA_CITY         ; 15
	const NIMBASA_PARK         ; 16
	const ROUTE_4              ; 17
	const DESERT_RESORT        ; 18
	const RELIC_CASTLE         ; 19
	const CASTELIA_CITY        ; 1a
	const CASTELIA_SEWERS      ; 1b
	const SKYARROW_BRIDGE      ; 1c
	const PINWHEEL_FOREST      ; 1d
	const NACRENE_CITY         ; 1e
	const ROUTE_3              ; 1f
	const WELLSPRING_CAVE      ; 20
	const STRIATON_CITY        ; 21
	const DREAMYARD            ; 22
	const ROUTE_2              ; 23
	const ACCUMULA_TOWN        ; 24
	const ROUTE_1              ; 25
	const NUVEMA_TOWN          ; 26
	const ROUTE_17             ; 27
	const ROUTE_18             ; 28
	const P2_LAB               ; 29
	const ASPERTIA_CITY        ; 2a
	const ROUTE_19             ; 2b
	const FLOCCESY_TOWN        ; 2c
	const FLOCCESY_RANCH       ; 2d
	const ROUTE_20             ; 2e
	const VIRBANK_CITY         ; 2f
	const VIRBANK_COMPLEX      ; 30
	const ROUTE_5              ; 31
	const DRIFTVEIL_DRAWBRIDGE ; 32
	const DRIFTVEIL_CITY       ; 33
	const CLAY_TUNNEL          ; 33
	const PWT                  ; 34
	const RELIC_PASSAGE        ; 35
	const ROUTE_6              ; 36
	const MISTRALTON_CAVE      ; 37
	const CHARGESTONE_CAVE     ; 38
	const MISTRALTON_CITY      ; 39
	const ROUTE_7              ; 3a
	const CELESTIAL_TOWER      ; 3b
	const TWIST_MOUNTAIN       ; 3c
	const ICIRRUS_CITY         ; 3d
	const DRAGONSPIRAL_TOWER   ; 3e
	const ROUTE_8              ; 3f
	const MOOR_OF_ICIRRUS      ; 40
	const TUBELINE_BRIDGE      ; 41
	const ROUTE_9              ; 42
	const OPELUCID_CITY        ; 43
	const ROUTE_11             ; 44
	const VILLAGE_BRIDGE       ; 45
	const ROUTE_12             ; 46
	const ROUTE_23             ; 47
	const VICTORY_ROAD         ; 48
	const POKEMON_LEAGUE       ; 49
	const BATTLE_TOWER         ; 4a
DEF KANTO_LANDMARK EQU const_value
DEF SHAMOUTI_LANDMARK EQU const_value
DEF NUM_LANDMARKS EQU const_value

; used in CaughtData
DEF LANDMARK_EVENT EQU $ff

; Regions
	const_def
	const JOHTO_REGION  ; 0
	const KANTO_REGION  ; 1
	const ORANGE_REGION ; 2
DEF NUM_REGIONS EQU const_value
