; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_SILPH
	const MARTTYPE_ADVENTURER
	const MARTTYPE_INFORMAL
	const MARTTYPE_BAZAAR
	const MARTTYPE_TM
	const MARTTYPE_BLUECARD
	const MARTTYPE_BP
	const MARTTYPE_EXP_CANDY

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_NO_DEX
	const MART_NO_BADGES
	const MART_ONE_BADGE
	const MART_TWO_BADGES
	const MART_THREE_BADGES
	const MART_FOUR_BADGES
	const MART_FIVE_BADGES
	const MART_SEVEN_BADGES
	const MART_EIGHT_BADGES
	const MART_BATTLETOWER_1
	const MART_BATTLETOWER_2
	const MART_BATTLETOWER_3
	const MART_BATTLEFACTORY_1
	const MART_BATTLEFACTORY_2
	const MART_BATTLEFACTORY_3
DEF NUM_MARTS EQU const_value
