Music:
; entries correspond to MUSIC_* constants
	table_width 3
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_MainMenu
	dba Music_Mom
	dba Music_UnovaWildBattle
	dba Music_UnovaWildBattleNight
	dba Music_WildPokemonVictory
	dba Music_ShowMeAround
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_SuccessfulCapture
	dba Music_LookYoungster
	dba Music_UnovaTrainerBattle
	dba Music_TrainerVictory
	dba Music_HiddenGrotto
	dba Music_UnovaRoute4
	dba Music_LookPlasma
	dba Music_PlasmaBattle
	dba Music_LookRival
	dba Music_RivalBattle
	dba Music_Evolution
	dba Music_Gym
	dba Music_UnovaGymBattle
	dba Music_FinalPokemon
	dba Music_GymLeaderVictory
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_LookLass
	dba Music_Surf
	dba Music_SurfingPikachu
	dba Music_RocketHideout
	dba Music_SuicuneBattle
	dba Music_VictoryRoad
	dba Music_UnovaEliteFourBattle
	dba Music_ChampionBattle
	dba Music_HallOfFame
	dba Music_MagnetTrain
	dba Music_PokemonLullaby
	dba Music_LookHiker
	dba Music_ProfOak
	dba Music_LookBeauty
	dba Music_BattleTowerTheme
	dba Music_BattleTowerLobby
	dba Music_BattleFactoryRSE
	dba Music_FrontierBrainBattleRSE
	dba Music_SpikyEaredPichu
	dba Music_CynthiaBattle
	dba Music_PWTFinalBattle
	dba Music_IrisBattle
	dba Music_Credits
	dba Music_PostCredits
	dba Music_Printer
	dba Music_HumilauCity
	dba Music_UnovaRoute1
	dba Music_LookAceTrainer
	dba Music_LookGentleman
	dba Music_LookWorker
	dba Music_LookPsychic
	dba Music_LookRoughneck
	dba Music_LookCyclist
	dba Music_LookScientist
	dba Music_LookTwins
	dba Music_UnovaCave
	dba Music_UnovaRoute2
	dba Music_LacunosaTown
	dba Music_BrendanEncounter
	dba Music_CynthiaEncounter
	dba Music_LentimasTown
	dba Music_ScaryHouse
	dba Music_PetalburgWoods
	dba Music_NimbasaCity
	dab Music_Mart
	dba Music_LookZinnia
	dba Music_RoadToReversalMountain
	dba Music_CasteliaCity
	dba Music_CasteliaSewers
	dba Music_AspertiaCity
	assert_table_length NUM_MUSIC_SONGS
