MarvelousBridge_MapScriptHeader:
	def_scene_scripts

	def_callbacks

	def_warp_events
	warp_event  4,  5, ROUTE_16_MARVELOUS_BRIDGE_GATE, 3
	warp_event  4,  6, ROUTE_16_MARVELOUS_BRIDGE_GATE, 4
	warp_event 37,  5, ROUTE_15_MARVELOUS_BRIDGE_GATE, 1
	warp_event 37,  6, ROUTE_15_MARVELOUS_BRIDGE_GATE, 2

	def_coord_events

	def_bg_events
	
	def_object_events
	object_event 10,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 11,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 14,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 15,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 18,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 19,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 22,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 23,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 26,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 27,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_LEFT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 30,  4, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_1, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	object_event 31,  7, SPRITE_BRIDGE_CABLE, SPRITEMOVEDATA_MARVELOUS_RIGHT_2, 0, 0, -1, PAL_NPC_BRIDGE_CABLE, OBJECTTYPE_SCRIPT, 0, DoNothingScript, -1
	