AnimationPointers:
	table_width 2
	dw RattataPlainAnimation
	dw RaticatePlainAnimation
	dw PikachuPlainAnimation
	dw RaichuPlainAnimation
	dw SandshrewPlainAnimation
	dw SandslashPlainAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixPlainAnimation
	dw NinetalesPlainAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw MeowthPlainAnimation
	dw PersianPlainAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw GrowlithePlainAnimation
	dw ArcaninePlainAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw GeodudePlainAnimation
	dw GravelerPlainAnimation
	dw GolemPlainAnimation
	dw PonytaPlainAnimation
	dw RapidashPlainAnimation
	dw SlowpokePlainAnimation
	dw SlowbroPlainAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerPlainAnimation
	dw MukPlainAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw ExeggcuteAnimation
	dw ExeggutorPlainAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingPlainAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimePlainAnimation
	dw ScytherAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw SnorlaxAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuPlainAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingPlainAnimation
	dw MisdreavusAnimation
	dw UnownAAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselPlainAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaPlainAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw AzurillAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw MunchlaxAnimation
	dw MantykeAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw SylveonAnimation
	dw PerrserkerAnimation
	dw CursolaAnimation
	dw MrRimeAnimation
	dw KleavorAnimation
	dw SneaslerAnimation
	dw DudunsparceTwoSegmentAnimation
	dw AnnihilapeAnimation
	dw VictiniAnimation
	dw SnivyAnimation
	dw ServineAnimation
	dw SerperiorAnimation
	dw TepigAnimation
	dw PigniteAnimation
	dw EmboarAnimation
	dw OshawottAnimation
	dw DewottAnimation
	dw SamurottPlainAnimation
	dw PatratAnimation
	dw WatchogAnimation
	dw LillipupAnimation
	dw HerdierAnimation
	dw StoutlandAnimation
	dw PurrloinAnimation
	dw LiepardAnimation
	dw PansageAnimation
	dw SimisageAnimation
	dw PansearAnimation
	dw SimisearAnimation
	dw PanpourAnimation
	dw SimipourAnimation
	dw MunnaAnimation
	dw MusharnaAnimation
	dw PidoveAnimation
	dw TranquillAnimation
	dw UnfezantMaleAnimation
	dw BlitzleAnimation
	dw ZebstrikaAnimation
	dw RoggenrolaAnimation
	dw BoldoreAnimation
	dw GigalithAnimation
	dw WoobatAnimation
	dw SwoobatAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw AudinoAnimation
	dw TimburrAnimation
	dw GurdurrAnimation
	dw ConkeldurrAnimation
	dw TympoleAnimation
	dw PalpitoadAnimation
	dw SeismitoadAnimation
	dw ThrohAnimation
	dw SawkAnimation
	dw SewaddleAnimation
	dw SwadloonAnimation
	dw LeavannyAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw PetililAnimation
	dw LilligantPlainAnimation
	dw BasculinWhiteAnimation
	dw SandileAnimation
	dw KrokorokAnimation
	dw KrookodileAnimation
	dw DarumakaPlainAnimation
	dw DarmanitanPlainAnimation
	dw MaractusAnimation
	dw DwebbleAnimation
	dw CrustleAnimation
	dw ScraggyAnimation
	dw ScraftyAnimation
	dw SigilyphAnimation
	dw YamaskPlainAnimation
	dw CofagrigusAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw TrubbishAnimation
	dw GarbodorAnimation
	dw ZoruaPlainAnimation
	dw ZoroarkPlainAnimation
	dw MinccinoAnimation
	dw CinccinoAnimation
	dw GothitaAnimation
	dw GothoritaAnimation
	dw GothitelleAnimation
	dw SolosisAnimation
	dw DuosionAnimation
	dw ReuniclusAnimation
	dw DucklettAnimation
	dw SwannaAnimation
	dw VanilliteAnimation
	dw VanillishAnimation
	dw VanilluxeAnimation
	dw DeerlingSpringAnimation
	dw SawsbuckSpringAnimation
	dw EmolgaAnimation
	dw EggAnimation
	dw EggAnimation ; 100
	dw KarrablastAnimation
	dw EscavalierAnimation
	dw FoongusAnimation
	dw AmoongussAnimation
	dw FrillishMaleAnimation
	dw JellicentMaleAnimation
	dw AlomomolaAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw FerroseedAnimation
	dw FerrothornAnimation
	dw KlinkAnimation
	dw KlangAnimation
	dw KlinklangAnimation
	dw TynamoAnimation
	dw EelektrikAnimation
	dw EelektrossAnimation
	dw ElgyemAnimation
	dw BeheeyemAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw AxewAnimation
	dw FraxureAnimation
	dw HaxorusAnimation
	dw CubchooAnimation
	dw BearticAnimation
	dw CryogonalAnimation
	dw ShelmetAnimation
	dw AccelgorAnimation
	dw StunfiskPlainAnimation
	dw MienfooAnimation
	dw MienshaoAnimation
	dw DruddigonAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw PawniardAnimation
	dw BisharpAnimation
	dw BouffalantAnimation
	dw RuffletAnimation
	dw BraviaryPlainAnimation
	dw VullabyAnimation
	dw MandibuzzAnimation
	dw HeatmorAnimation
	dw DurantAnimation
	dw DeinoAnimation
	dw ZweilousAnimation
	dw HydreigonAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw CobalionAnimation
	dw TerrakionAnimation
	dw VirizionAnimation
	dw TornadusPlainAnimation
	dw ThundurusPlainAnimation
	dw ReshiramAnimation
	dw ZekromAnimation
	dw LandorusPlainAnimation
	dw KyuremPlainAnimation
	dw KeldeoAnimation
	dw MeloettaPlainAnimation
	dw GenesectAnimation
	dw RunerigusAnimation
	assert_table_length NUM_SPECIES

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw PikachuFlyAnimation
	dw PikachuSurfAnimation
	dw PikachuPikaAnimation
	dw PikachuChuchuAnimation
	dw PikachuSparkAnimation

	dw PichuSpikyAnimation

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw DudunsparceThreeSegmentAnimation

	dw RattataAlolanAnimation
	dw RaticateAlolanAnimation
	dw RaichuAlolanAnimation
	dw SandshrewAlolanAnimation
	dw SandslashAlolanAnimation
	dw VulpixAlolanAnimation
	dw NinetalesAlolanAnimation
	dw MeowthAlolanAnimation
	dw PersianAlolanAnimation
	dw GeodudeAlolanAnimation
	dw GravelerAlolanAnimation
	dw GolemAlolanAnimation
	dw GrimerAlolanAnimation
	dw MukAlolanAnimation
	dw ExeggutorAlolanAnimation

	dw MeowthGalarianAnimation
	dw PonytaGalarianAnimation
	dw RapidashGalarianAnimation
	dw SlowpokeGalarianAnimation
	dw SlowbroGalarianAnimation
	dw WeezingGalarianAnimation
	dw MrMimeGalarianAnimation
	dw SlowkingGalarianAnimation
	dw CorsolaGalarianAnimation
	dw DarumakaGalarianAnimation
	dw DarmanitanGalarianAnimation
	dw YamaskGalarianAnimation

	dw GrowlitheHisuianAnimation
	dw ArcanineHisuianAnimation
	dw SneaselHisuianAnimation
	
	dw UnfezantFemaleAnimation
	
	dw BasculinRedAnimation
	dw BasculinBlueAnimation
	
	dw DarmanitanZenAnimation
	dw DarmanitanGalarianZenAnimation
	
	dw DeerlingSummerAnimation
	dw DeerlingAutumnAnimation
	dw DeerlingWinterAnimation
	
	dw SawsbuckSummerAnimation
	dw SawsbuckAutumnAnimation
	dw SawsbuckWinterAnimation
	
	dw FrillishFemaleAnimation
	dw JellicentFemaleAnimation
	
	dw TornadusTherianAnimation
	dw ThundurusTherianAnimation
	dw LandorusTherianAnimation
	
	dw KyuremWhiteAnimation
	dw KyuremBlackAnimation
	
	dw MeloettaPirouetteAnimation

	assert_table_length NUM_UNIQUE_POKEMON
