BulbasaurAnimation:  INCLUDE "gfx/pokemon/bulbasaur/anim.asm"
IvysaurAnimation:    INCLUDE "gfx/pokemon/ivysaur/anim.asm"
VenusaurAnimation:   INCLUDE "gfx/pokemon/venusaur/anim.asm"
CharmanderAnimation: INCLUDE "gfx/pokemon/charmander/anim.asm"
CharmeleonAnimation: INCLUDE "gfx/pokemon/charmeleon/anim.asm"
CharizardAnimation:  INCLUDE "gfx/pokemon/charizard/anim.asm"
SquirtleAnimation:   INCLUDE "gfx/pokemon/squirtle/anim.asm"
WartortleAnimation:  INCLUDE "gfx/pokemon/wartortle/anim.asm"
BlastoiseAnimation:  INCLUDE "gfx/pokemon/blastoise/anim.asm"
NidoranFAnimation:   INCLUDE "gfx/pokemon/nidoran_f/anim.asm"
NidorinaAnimation:   INCLUDE "gfx/pokemon/nidorina/anim.asm"
NidoqueenAnimation:  INCLUDE "gfx/pokemon/nidoqueen/anim.asm"
NidoranMAnimation:   INCLUDE "gfx/pokemon/nidoran_m/anim.asm"
NidorinoAnimation:   INCLUDE "gfx/pokemon/nidorino/anim.asm"
NidokingAnimation:   INCLUDE "gfx/pokemon/nidoking/anim.asm"
ClefairyAnimation:   INCLUDE "gfx/pokemon/clefairy/anim.asm"
ClefableAnimation:   INCLUDE "gfx/pokemon/clefable/anim.asm"
JigglypuffAnimation: INCLUDE "gfx/pokemon/jigglypuff/anim.asm"
WigglytuffAnimation: INCLUDE "gfx/pokemon/wigglytuff/anim.asm"
ZubatAnimation:      INCLUDE "gfx/pokemon/zubat/anim.asm"
GolbatAnimation:     INCLUDE "gfx/pokemon/golbat/anim.asm"
ParasAnimation:      INCLUDE "gfx/pokemon/paras/anim.asm"
ParasectAnimation:   INCLUDE "gfx/pokemon/parasect/anim.asm"
PsyduckAnimation:    INCLUDE "gfx/pokemon/psyduck/anim.asm"
GolduckAnimation:    INCLUDE "gfx/pokemon/golduck/anim.asm"
MankeyAnimation:     INCLUDE "gfx/pokemon/mankey/anim.asm"
PrimeapeAnimation:   INCLUDE "gfx/pokemon/primeape/anim.asm"
PoliwagAnimation:    INCLUDE "gfx/pokemon/poliwag/anim.asm"
PoliwhirlAnimation:  INCLUDE "gfx/pokemon/poliwhirl/anim.asm"
PoliwrathAnimation:  INCLUDE "gfx/pokemon/poliwrath/anim.asm"
MagnemiteAnimation:  INCLUDE "gfx/pokemon/magnemite/anim.asm"
MagnetonAnimation:   INCLUDE "gfx/pokemon/magneton/anim.asm"
SeelAnimation:       INCLUDE "gfx/pokemon/seel/anim.asm"
DewgongAnimation:    INCLUDE "gfx/pokemon/dewgong/anim.asm"
GastlyAnimation:     INCLUDE "gfx/pokemon/gastly/anim.asm"
HaunterAnimation:    INCLUDE "gfx/pokemon/haunter/anim.asm"
GengarAnimation:     INCLUDE "gfx/pokemon/gengar/anim.asm"
OnixAnimation:       INCLUDE "gfx/pokemon/onix/anim.asm"
ExeggcuteAnimation:  INCLUDE "gfx/pokemon/exeggcute/anim.asm"
LickitungAnimation:  INCLUDE "gfx/pokemon/lickitung/anim.asm"
KoffingAnimation:    INCLUDE "gfx/pokemon/koffing/anim.asm"
TangelaAnimation:    INCLUDE "gfx/pokemon/tangela/anim.asm"
KangaskhanAnimation: INCLUDE "gfx/pokemon/kangaskhan/anim.asm"
HorseaAnimation:     INCLUDE "gfx/pokemon/horsea/anim.asm"
SeadraAnimation:     INCLUDE "gfx/pokemon/seadra/anim.asm"
StaryuAnimation:     INCLUDE "gfx/pokemon/staryu/anim.asm"
StarmieAnimation:    INCLUDE "gfx/pokemon/starmie/anim.asm"
ScytherAnimation:    INCLUDE "gfx/pokemon/scyther/anim.asm"
ElectabuzzAnimation: INCLUDE "gfx/pokemon/electabuzz/anim.asm"
MagmarAnimation:     INCLUDE "gfx/pokemon/magmar/anim.asm"
PinsirAnimation:     INCLUDE "gfx/pokemon/pinsir/anim.asm"
LaprasAnimation:     INCLUDE "gfx/pokemon/lapras/anim.asm"
DittoAnimation:      INCLUDE "gfx/pokemon/ditto/anim.asm"
EeveeAnimation:      INCLUDE "gfx/pokemon/eevee/anim.asm"
VaporeonAnimation:   INCLUDE "gfx/pokemon/vaporeon/anim.asm"
JolteonAnimation:    INCLUDE "gfx/pokemon/jolteon/anim.asm"
FlareonAnimation:    INCLUDE "gfx/pokemon/flareon/anim.asm"
SnorlaxAnimation:    INCLUDE "gfx/pokemon/snorlax/anim.asm"
DratiniAnimation:    INCLUDE "gfx/pokemon/dratini/anim.asm"
DragonairAnimation:  INCLUDE "gfx/pokemon/dragonair/anim.asm"
DragoniteAnimation:  INCLUDE "gfx/pokemon/dragonite/anim.asm"
MewAnimation:        INCLUDE "gfx/pokemon/mew/anim.asm"
ChikoritaAnimation:  INCLUDE "gfx/pokemon/chikorita/anim.asm"
BayleefAnimation:    INCLUDE "gfx/pokemon/bayleef/anim.asm"
MeganiumAnimation:   INCLUDE "gfx/pokemon/meganium/anim.asm"
CyndaquilAnimation:  INCLUDE "gfx/pokemon/cyndaquil/anim.asm"
QuilavaAnimation:    INCLUDE "gfx/pokemon/quilava/anim.asm"
TotodileAnimation:   INCLUDE "gfx/pokemon/totodile/anim.asm"
CroconawAnimation:   INCLUDE "gfx/pokemon/croconaw/anim.asm"
FeraligatrAnimation: INCLUDE "gfx/pokemon/feraligatr/anim.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim.asm"
CleffaAnimation:     INCLUDE "gfx/pokemon/cleffa/anim.asm"
IgglybuffAnimation:  INCLUDE "gfx/pokemon/igglybuff/anim.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim.asm"
DelibirdAnimation:   INCLUDE "gfx/pokemon/delibird/anim.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim.asm"
AzurillAnimation:    INCLUDE "gfx/pokemon/azurill/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim.asm"
BonslyAnimation:     INCLUDE "gfx/pokemon/bonsly/anim.asm"
MimeJrAnimation:     INCLUDE "gfx/pokemon/mime_jr_/anim.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim.asm"
MantykeAnimation:    INCLUDE "gfx/pokemon/mantyke/anim.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim.asm"
LickilickyAnimation: INCLUDE "gfx/pokemon/lickilicky/anim.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim.asm"
PerrserkerAnimation: INCLUDE "gfx/pokemon/perrserker/anim.asm"
CursolaAnimation:    INCLUDE "gfx/pokemon/cursola/anim.asm"
MrRimeAnimation:     INCLUDE "gfx/pokemon/mr__rime/anim.asm"
KleavorAnimation:    INCLUDE "gfx/pokemon/kleavor/anim.asm"
SneaslerAnimation:   INCLUDE "gfx/pokemon/sneasler/anim.asm"
AnnihilapeAnimation: INCLUDE "gfx/pokemon/annihilape/anim.asm"
SnivyAnimation:      INCLUDE "gfx/pokemon/snivy/anim.asm"
ServineAnimation:    INCLUDE "gfx/pokemon/servine/anim.asm"
SerperiorAnimation:  INCLUDE "gfx/pokemon/serperior/anim.asm"
TepigAnimation:      INCLUDE "gfx/pokemon/tepig/anim.asm"
PigniteAnimation:    INCLUDE "gfx/pokemon/pignite/anim.asm"
EmboarAnimation:     INCLUDE "gfx/pokemon/emboar/anim.asm"
OshawottAnimation:   INCLUDE "gfx/pokemon/oshawott/anim.asm"
DewottAnimation:     INCLUDE "gfx/pokemon/dewott/anim.asm"
PatratAnimation:     INCLUDE "gfx/pokemon/patrat/anim.asm"
WatchogAnimation:    INCLUDE "gfx/pokemon/watchog/anim.asm"
LillipupAnimation:   INCLUDE "gfx/pokemon/lillipup/anim.asm"
HerdierAnimation:    INCLUDE "gfx/pokemon/herdier/anim.asm"
StoutlandAnimation:  INCLUDE "gfx/pokemon/stoutland/anim.asm"
PurrloinAnimation:   INCLUDE "gfx/pokemon/purrloin/anim.asm"
LiepardAnimation:    INCLUDE "gfx/pokemon/liepard/anim.asm"
PansageAnimation:    INCLUDE "gfx/pokemon/pansage/anim.asm"
SimisageAnimation:   INCLUDE "gfx/pokemon/simisage/anim.asm"
PansearAnimation:    INCLUDE "gfx/pokemon/pansear/anim.asm"
SimisearAnimation:   INCLUDE "gfx/pokemon/simisear/anim.asm"
PanpourAnimation:    INCLUDE "gfx/pokemon/panpour/anim.asm"
SimipourAnimation:   INCLUDE "gfx/pokemon/simipour/anim.asm"
MunnaAnimation:      INCLUDE "gfx/pokemon/munna/anim.asm"
MusharnaAnimation:   INCLUDE "gfx/pokemon/musharna/anim.asm"
PidoveAnimation:     INCLUDE "gfx/pokemon/pidove/anim.asm"
TranquillAnimation:  INCLUDE "gfx/pokemon/tranquill/anim.asm"
BlitzleAnimation:    INCLUDE "gfx/pokemon/blitzle/anim.asm"
ZebstrikaAnimation:  INCLUDE "gfx/pokemon/zebstrika/anim.asm"
RoggenrolaAnimation: INCLUDE "gfx/pokemon/roggenrola/anim.asm"
BoldoreAnimation:    INCLUDE "gfx/pokemon/boldore/anim.asm"
GigalithAnimation:   INCLUDE "gfx/pokemon/gigalith/anim.asm"
WoobatAnimation:     INCLUDE "gfx/pokemon/woobat/anim.asm"
SwoobatAnimation:    INCLUDE "gfx/pokemon/swoobat/anim.asm"
DrilburAnimation:    INCLUDE "gfx/pokemon/drilbur/anim.asm"
ExcadrillAnimation:  INCLUDE "gfx/pokemon/excadrill/anim.asm"
AudinoAnimation:     INCLUDE "gfx/pokemon/audino/anim.asm"
TimburrAnimation:    INCLUDE "gfx/pokemon/timburr/anim.asm"
GurdurrAnimation:    INCLUDE "gfx/pokemon/gurdurr/anim.asm"
ConkeldurrAnimation: INCLUDE "gfx/pokemon/conkeldurr/anim.asm"
TympoleAnimation:    INCLUDE "gfx/pokemon/tympole/anim.asm"
PalpitoadAnimation:  INCLUDE "gfx/pokemon/palpitoad/anim.asm"
SeismitoadAnimation: INCLUDE "gfx/pokemon/seismitoad/anim.asm"
ThrohAnimation:      INCLUDE "gfx/pokemon/throh/anim.asm"
SawkAnimation:       INCLUDE "gfx/pokemon/sawk/anim.asm"
SewaddleAnimation:   INCLUDE "gfx/pokemon/sewaddle/anim.asm"
SwadloonAnimation:   INCLUDE "gfx/pokemon/swadloon/anim.asm"
LeavannyAnimation:   INCLUDE "gfx/pokemon/leavanny/anim.asm"
VenipedeAnimation:   INCLUDE "gfx/pokemon/venipede/anim.asm"
WhirlipedeAnimation: INCLUDE "gfx/pokemon/whirlipede/anim.asm"
ScolipedeAnimation:  INCLUDE "gfx/pokemon/scolipede/anim.asm"
CottoneeAnimation:   INCLUDE "gfx/pokemon/cottonee/anim.asm"
WhimsicottAnimation: INCLUDE "gfx/pokemon/whimsicott/anim.asm"
PetililAnimation:    INCLUDE "gfx/pokemon/petilil/anim.asm"
SandileAnimation:    INCLUDE "gfx/pokemon/sandile/anim.asm"
KrokorokAnimation:   INCLUDE "gfx/pokemon/krokorok/anim.asm"
KrookodileAnimation: INCLUDE "gfx/pokemon/krookodile/anim.asm"
MaractusAnimation:   INCLUDE "gfx/pokemon/maractus/anim.asm"
DwebbleAnimation:    INCLUDE "gfx/pokemon/dwebble/anim.asm"
CrustleAnimation:    INCLUDE "gfx/pokemon/crustle/anim.asm"
ScraggyAnimation:    INCLUDE "gfx/pokemon/scraggy/anim.asm"
ScraftyAnimation:    INCLUDE "gfx/pokemon/scrafty/anim.asm"
SigilyphAnimation:   INCLUDE "gfx/pokemon/sigilyph/anim.asm"
CofagrigusAnimation: INCLUDE "gfx/pokemon/cofagrigus/anim.asm"
TirtougaAnimation:   INCLUDE "gfx/pokemon/tirtouga/anim.asm"
CarracostaAnimation: INCLUDE "gfx/pokemon/carracosta/anim.asm"
ArchenAnimation:     INCLUDE "gfx/pokemon/archen/anim.asm"
ArcheopsAnimation:   INCLUDE "gfx/pokemon/archeops/anim.asm"
TrubbishAnimation:   INCLUDE "gfx/pokemon/trubbish/anim.asm"
GarbodorAnimation:   INCLUDE "gfx/pokemon/garbodor/anim.asm"
MinccinoAnimation:   INCLUDE "gfx/pokemon/minccino/anim.asm"
CinccinoAnimation:   INCLUDE "gfx/pokemon/cinccino/anim.asm"
GothitaAnimation:    INCLUDE "gfx/pokemon/gothita/anim.asm"
GothoritaAnimation:  INCLUDE "gfx/pokemon/gothorita/anim.asm"
GothitelleAnimation: INCLUDE "gfx/pokemon/gothitelle/anim.asm"
SolosisAnimation:    INCLUDE "gfx/pokemon/solosis/anim.asm"
DuosionAnimation:    INCLUDE "gfx/pokemon/duosion/anim.asm"
ReuniclusAnimation:  INCLUDE "gfx/pokemon/reuniclus/anim.asm"
DucklettAnimation:   INCLUDE "gfx/pokemon/ducklett/anim.asm"
SwannaAnimation:     INCLUDE "gfx/pokemon/swanna/anim.asm"
VanilliteAnimation:  INCLUDE "gfx/pokemon/vanillite/anim.asm"
VanillishAnimation:  INCLUDE "gfx/pokemon/vanillish/anim.asm"
VanilluxeAnimation:  INCLUDE "gfx/pokemon/vanilluxe/anim.asm"
EmolgaAnimation:     INCLUDE "gfx/pokemon/emolga/anim.asm"
KarrablastAnimation: INCLUDE "gfx/pokemon/karrablast/anim.asm"
EscavalierAnimation: INCLUDE "gfx/pokemon/escavalier/anim.asm"
FoongusAnimation:    INCLUDE "gfx/pokemon/foongus/anim.asm"
AmoongussAnimation:  INCLUDE "gfx/pokemon/amoonguss/anim.asm"
AlomomolaAnimation:  INCLUDE "gfx/pokemon/alomomola/anim.asm"
JoltikAnimation:     INCLUDE "gfx/pokemon/joltik/anim.asm"
GalvantulaAnimation: INCLUDE "gfx/pokemon/galvantula/anim.asm"
FerroseedAnimation:  INCLUDE "gfx/pokemon/ferroseed/anim.asm"
FerrothornAnimation: INCLUDE "gfx/pokemon/ferrothorn/anim.asm"
KlinkAnimation:      INCLUDE "gfx/pokemon/klink/anim.asm"
KlangAnimation:      INCLUDE "gfx/pokemon/klang/anim.asm"
KlinklangAnimation:  INCLUDE "gfx/pokemon/klinklang/anim.asm"
TynamoAnimation:     INCLUDE "gfx/pokemon/tynamo/anim.asm"
EelektrikAnimation:  INCLUDE "gfx/pokemon/eelektrik/anim.asm"
EelektrossAnimation: INCLUDE "gfx/pokemon/eelektross/anim.asm"
ElgyemAnimation:     INCLUDE "gfx/pokemon/elgyem/anim.asm"
BeheeyemAnimation:   INCLUDE "gfx/pokemon/beheeyem/anim.asm"
LitwickAnimation:    INCLUDE "gfx/pokemon/litwick/anim.asm"
LampentAnimation:    INCLUDE "gfx/pokemon/lampent/anim.asm"
ChandelureAnimation: INCLUDE "gfx/pokemon/chandelure/anim.asm"
AxewAnimation:       INCLUDE "gfx/pokemon/axew/anim.asm"
FraxureAnimation:    INCLUDE "gfx/pokemon/fraxure/anim.asm"
HaxorusAnimation:    INCLUDE "gfx/pokemon/haxorus/anim.asm"
CubchooAnimation:    INCLUDE "gfx/pokemon/cubchoo/anim.asm"
BearticAnimation:    INCLUDE "gfx/pokemon/beartic/anim.asm"
CryogonalAnimation:  INCLUDE "gfx/pokemon/cryogonal/anim.asm"
ShelmetAnimation:    INCLUDE "gfx/pokemon/shelmet/anim.asm"
AccelgorAnimation:   INCLUDE "gfx/pokemon/accelgor/anim.asm"
MienfooAnimation:    INCLUDE "gfx/pokemon/mienfoo/anim.asm"
MienshaoAnimation:   INCLUDE "gfx/pokemon/mienshao/anim.asm"
DruddigonAnimation:  INCLUDE "gfx/pokemon/druddigon/anim.asm"
GolettAnimation:     INCLUDE "gfx/pokemon/golett/anim.asm"
GolurkAnimation:     INCLUDE "gfx/pokemon/golurk/anim.asm"
PawniardAnimation:   INCLUDE "gfx/pokemon/pawniard/anim.asm"
BisharpAnimation:    INCLUDE "gfx/pokemon/bisharp/anim.asm"
BouffalantAnimation: INCLUDE "gfx/pokemon/bouffalant/anim.asm"
RuffletAnimation:    INCLUDE "gfx/pokemon/rufflet/anim.asm"
VullabyAnimation:    INCLUDE "gfx/pokemon/vullaby/anim.asm"
MandibuzzAnimation:  INCLUDE "gfx/pokemon/mandibuzz/anim.asm"
HeatmorAnimation:    INCLUDE "gfx/pokemon/heatmor/anim.asm"
DurantAnimation:     INCLUDE "gfx/pokemon/durant/anim.asm"
DeinoAnimation:      INCLUDE "gfx/pokemon/deino/anim.asm"
ZweilousAnimation:   INCLUDE "gfx/pokemon/zweilous/anim.asm"
HydreigonAnimation:  INCLUDE "gfx/pokemon/hydreigon/anim.asm"
LarvestaAnimation:   INCLUDE "gfx/pokemon/larvesta/anim.asm"
VolcaronaAnimation:  INCLUDE "gfx/pokemon/volcarona/anim.asm"
GenesectAnimation:   INCLUDE "gfx/pokemon/genesect/anim.asm"

EggAnimation:        INCLUDE "gfx/pokemon/egg/anim.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim.asm"

PikachuPlainAnimation:  INCLUDE "gfx/pokemon/pikachu_plain/anim.asm"
PikachuFlyAnimation:    INCLUDE "gfx/pokemon/pikachu_fly/anim.asm"
PikachuSurfAnimation:   INCLUDE "gfx/pokemon/pikachu_surf/anim.asm"
PikachuPikaAnimation:   INCLUDE "gfx/pokemon/pikachu_pika/anim.asm"
PikachuChuchuAnimation: INCLUDE "gfx/pokemon/pikachu_chuchu/anim.asm"
PikachuSparkAnimation:  INCLUDE "gfx/pokemon/pikachu_spark/anim.asm"

MagikarpPlainAnimation:
MagikarpSkellyAnimation:
MagikarpCalico1Animation:
MagikarpCalico2Animation:
MagikarpCalico3Animation:
MagikarpTwoToneAnimation:
MagikarpOrcaAnimation:
MagikarpDapplesAnimation:
MagikarpTigerAnimation:
MagikarpZebraAnimation:
MagikarpStripeAnimation:
MagikarpBubblesAnimation:
MagikarpDiamondsAnimation:
MagikarpPatchesAnimation:
MagikarpForehead1Animation:
MagikarpMask1Animation:
MagikarpForehead2Animation:
MagikarpMask2Animation:
MagikarpSaucyAnimation:
MagikarpRaindropAnimation: INCLUDE "gfx/pokemon/magikarp/anim.asm"

DudunsparceTwoSegmentAnimation:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim.asm"
DudunsparceThreeSegmentAnimation: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim.asm"

GyaradosPlainAnimation: INCLUDE "gfx/pokemon/gyarados_plain/anim.asm"
GyaradosRedAnimation:   INCLUDE "gfx/pokemon/gyarados_red/anim.asm"

MewtwoPlainAnimation:   INCLUDE "gfx/pokemon/mewtwo_plain/anim.asm"
MewtwoArmoredAnimation: INCLUDE "gfx/pokemon/mewtwo_armored/anim.asm"

RattataPlainAnimation:  INCLUDE "gfx/pokemon/rattata_plain/anim.asm"
RattataAlolanAnimation: INCLUDE "gfx/pokemon/rattata_alolan/anim.asm"

RaticatePlainAnimation:  INCLUDE "gfx/pokemon/raticate_plain/anim.asm"
RaticateAlolanAnimation: INCLUDE "gfx/pokemon/raticate_alolan/anim.asm"

RaichuPlainAnimation:  INCLUDE "gfx/pokemon/raichu_plain/anim.asm"
RaichuAlolanAnimation: INCLUDE "gfx/pokemon/raichu_alolan/anim.asm"

SandshrewPlainAnimation:  INCLUDE "gfx/pokemon/sandshrew_plain/anim.asm"
SandshrewAlolanAnimation: INCLUDE "gfx/pokemon/sandshrew_alolan/anim.asm"

SandslashPlainAnimation:  INCLUDE "gfx/pokemon/sandslash_plain/anim.asm"
SandslashAlolanAnimation: INCLUDE "gfx/pokemon/sandslash_alolan/anim.asm"

VulpixPlainAnimation:  INCLUDE "gfx/pokemon/vulpix_plain/anim.asm"
VulpixAlolanAnimation: INCLUDE "gfx/pokemon/vulpix_alolan/anim.asm"

NinetalesPlainAnimation:  INCLUDE "gfx/pokemon/ninetales_plain/anim.asm"
NinetalesAlolanAnimation: INCLUDE "gfx/pokemon/ninetales_alolan/anim.asm"

MeowthPlainAnimation:    INCLUDE "gfx/pokemon/meowth_plain/anim.asm"
MeowthAlolanAnimation:   INCLUDE "gfx/pokemon/meowth_alolan/anim.asm"
MeowthGalarianAnimation: INCLUDE "gfx/pokemon/meowth_galarian/anim.asm"

PersianPlainAnimation:  INCLUDE "gfx/pokemon/persian_plain/anim.asm"
PersianAlolanAnimation: INCLUDE "gfx/pokemon/persian_alolan/anim.asm"

GeodudePlainAnimation:  INCLUDE "gfx/pokemon/geodude_plain/anim.asm"
GeodudeAlolanAnimation: INCLUDE "gfx/pokemon/geodude_alolan/anim.asm"

GravelerPlainAnimation:  INCLUDE "gfx/pokemon/graveler_plain/anim.asm"
GravelerAlolanAnimation: INCLUDE "gfx/pokemon/graveler_alolan/anim.asm"

GolemPlainAnimation:  INCLUDE "gfx/pokemon/golem_plain/anim.asm"
GolemAlolanAnimation: INCLUDE "gfx/pokemon/golem_alolan/anim.asm"

GrimerPlainAnimation:  INCLUDE "gfx/pokemon/grimer_plain/anim.asm"
GrimerAlolanAnimation: INCLUDE "gfx/pokemon/grimer_alolan/anim.asm"

MukPlainAnimation:  INCLUDE "gfx/pokemon/muk_plain/anim.asm"
MukAlolanAnimation: INCLUDE "gfx/pokemon/muk_alolan/anim.asm"

ExeggutorPlainAnimation:  INCLUDE "gfx/pokemon/exeggutor_plain/anim.asm"
ExeggutorAlolanAnimation: INCLUDE "gfx/pokemon/exeggutor_alolan/anim.asm"

PonytaPlainAnimation:    INCLUDE "gfx/pokemon/ponyta_plain/anim.asm"
PonytaGalarianAnimation: INCLUDE "gfx/pokemon/ponyta_galarian/anim.asm"

RapidashPlainAnimation:    INCLUDE "gfx/pokemon/rapidash_plain/anim.asm"
RapidashGalarianAnimation: INCLUDE "gfx/pokemon/rapidash_galarian/anim.asm"

SlowpokePlainAnimation:    INCLUDE "gfx/pokemon/slowpoke_plain/anim.asm"
SlowpokeGalarianAnimation: INCLUDE "gfx/pokemon/slowpoke_galarian/anim.asm"

SlowbroPlainAnimation:    INCLUDE "gfx/pokemon/slowbro_plain/anim.asm"
SlowbroGalarianAnimation: INCLUDE "gfx/pokemon/slowbro_galarian/anim.asm"

WeezingPlainAnimation:    INCLUDE "gfx/pokemon/weezing_plain/anim.asm"
WeezingGalarianAnimation: INCLUDE "gfx/pokemon/weezing_galarian/anim.asm"

MrMimePlainAnimation:    INCLUDE "gfx/pokemon/mr__mime_plain/anim.asm"
MrMimeGalarianAnimation: INCLUDE "gfx/pokemon/mr__mime_galarian/anim.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim.asm"

CorsolaPlainAnimation:    INCLUDE "gfx/pokemon/corsola_plain/anim.asm"
CorsolaGalarianAnimation: INCLUDE "gfx/pokemon/corsola_galarian/anim.asm"

GrowlithePlainAnimation:   INCLUDE "gfx/pokemon/growlithe_plain/anim.asm"
GrowlitheHisuianAnimation: INCLUDE "gfx/pokemon/growlithe_hisuian/anim.asm"

ArcaninePlainAnimation:   INCLUDE "gfx/pokemon/arcanine_plain/anim.asm"
ArcanineHisuianAnimation: INCLUDE "gfx/pokemon/arcanine_hisuian/anim.asm"

TyphlosionPlainAnimation:   INCLUDE "gfx/pokemon/typhlosion_plain/anim.asm"
TyphlosionHisuianAnimation: INCLUDE "gfx/pokemon/typhlosion_hisuian/anim.asm"

SneaselPlainAnimation:   INCLUDE "gfx/pokemon/sneasel_plain/anim.asm"
SneaselHisuianAnimation: INCLUDE "gfx/pokemon/sneasel_hisuian/anim.asm"

UnfezantMaleAnimation:   INCLUDE "gfx/pokemon/unfezant_male/anim.asm"
UnfezantFemaleAnimation: INCLUDE "gfx/pokemon/unfezant_female/anim.asm"

SamurottPlainAnimation: INCLUDE "gfx/pokemon/samurott_plain/anim.asm"

LilligantPlainAnimation: INCLUDE "gfx/pokemon/lilligant_plain/anim.asm"

BasculinRedAnimation: INCLUDE "gfx/pokemon/basculin_red/anim.asm"

DarumakaPlainAnimation: INCLUDE "gfx/pokemon/darumaka_plain/anim.asm"

DarmanitanPlainAnimation: INCLUDE "gfx/pokemon/darmanitan_plain/anim.asm"

YamaskPlainAnimation: INCLUDE "gfx/pokemon/yamask_plain/anim.asm"

ZoruaPlainAnimation: INCLUDE "gfx/pokemon/zorua_plain/anim.asm"

ZoroarkPlainAnimation: INCLUDE "gfx/pokemon/zoroark_plain/anim.asm"

DeerlingSpringAnimation: INCLUDE "gfx/pokemon/deerling_spring/anim.asm"
DeerlingSummerAnimation: INCLUDE "gfx/pokemon/deerling_summer/anim.asm"
DeerlingAutumnAnimation: INCLUDE "gfx/pokemon/deerling_autumn/anim.asm"
DeerlingWinterAnimation: INCLUDE "gfx/pokemon/deerling_winter/anim.asm"

SawsbuckSpringAnimation: INCLUDE "gfx/pokemon/sawsbuck_spring/anim.asm"
SawsbuckSummerAnimation: INCLUDE "gfx/pokemon/sawsbuck_summer/anim.asm"
SawsbuckAutumnAnimation: INCLUDE "gfx/pokemon/sawsbuck_autumn/anim.asm"
SawsbuckWinterAnimation: INCLUDE "gfx/pokemon/sawsbuck_winter/anim.asm"

FrillishMaleAnimation:   INCLUDE "gfx/pokemon/frillish_male/anim.asm"
FrillishFemaleAnimation: INCLUDE "gfx/pokemon/frillish_female/anim.asm"

JellicentMaleAnimation:   INCLUDE "gfx/pokemon/jellicent_male/anim.asm"
JellicentFemaleAnimation: INCLUDE "gfx/pokemon/jellicent_female/anim.asm"

StunfiskPlainAnimation: INCLUDE "gfx/pokemon/stunfisk_plain/anim.asm"

BraviaryPlainAnimation: INCLUDE "gfx/pokemon/braviary_plain/anim.asm"
