NidoranFAnimation:   INCLUDE "gfx/pokemon/nidoran_f/anim.asm"
NidorinaAnimation:   INCLUDE "gfx/pokemon/nidorina/anim.asm"
NidoqueenAnimation:  INCLUDE "gfx/pokemon/nidoqueen/anim.asm"
NidoranMAnimation:   INCLUDE "gfx/pokemon/nidoran_m/anim.asm"
NidorinoAnimation:   INCLUDE "gfx/pokemon/nidorino/anim.asm"
NidokingAnimation:   INCLUDE "gfx/pokemon/nidoking/anim.asm"
ClefairyAnimation:   INCLUDE "gfx/pokemon/clefairy/anim.asm"
ClefableAnimation:   INCLUDE "gfx/pokemon/clefable/anim.asm"
JigglypuffAnimation: INCLUDE "gfx/pokemon/jigglypuff/anim.asm"
WigglytuffAnimation: INCLUDE "gfx/pokemon/wigglytuff/anim.asm"
ZubatAnimation:      INCLUDE "gfx/pokemon/zubat/anim.asm"
GolbatAnimation:     INCLUDE "gfx/pokemon/golbat/anim.asm"
ParasAnimation:      INCLUDE "gfx/pokemon/paras/anim.asm"
ParasectAnimation:   INCLUDE "gfx/pokemon/parasect/anim.asm"
PsyduckAnimation:    INCLUDE "gfx/pokemon/psyduck/anim.asm"
GolduckAnimation:    INCLUDE "gfx/pokemon/golduck/anim.asm"
MankeyAnimation:     INCLUDE "gfx/pokemon/mankey/anim.asm"
PrimeapeAnimation:   INCLUDE "gfx/pokemon/primeape/anim.asm"
PoliwagAnimation:    INCLUDE "gfx/pokemon/poliwag/anim.asm"
PoliwhirlAnimation:  INCLUDE "gfx/pokemon/poliwhirl/anim.asm"
PoliwrathAnimation:  INCLUDE "gfx/pokemon/poliwrath/anim.asm"
MagnemiteAnimation:  INCLUDE "gfx/pokemon/magnemite/anim.asm"
MagnetonAnimation:   INCLUDE "gfx/pokemon/magneton/anim.asm"
SeelAnimation:       INCLUDE "gfx/pokemon/seel/anim.asm"
DewgongAnimation:    INCLUDE "gfx/pokemon/dewgong/anim.asm"
GastlyAnimation:     INCLUDE "gfx/pokemon/gastly/anim.asm"
HaunterAnimation:    INCLUDE "gfx/pokemon/haunter/anim.asm"
GengarAnimation:     INCLUDE "gfx/pokemon/gengar/anim.asm"
OnixAnimation:       INCLUDE "gfx/pokemon/onix/anim.asm"
ExeggcuteAnimation:  INCLUDE "gfx/pokemon/exeggcute/anim.asm"
LickitungAnimation:  INCLUDE "gfx/pokemon/lickitung/anim.asm"
KoffingAnimation:    INCLUDE "gfx/pokemon/koffing/anim.asm"
TangelaAnimation:    INCLUDE "gfx/pokemon/tangela/anim.asm"
KangaskhanAnimation: INCLUDE "gfx/pokemon/kangaskhan/anim.asm"
HorseaAnimation:     INCLUDE "gfx/pokemon/horsea/anim.asm"
SeadraAnimation:     INCLUDE "gfx/pokemon/seadra/anim.asm"
StaryuAnimation:     INCLUDE "gfx/pokemon/staryu/anim.asm"
StarmieAnimation:    INCLUDE "gfx/pokemon/starmie/anim.asm"
ScytherAnimation:    INCLUDE "gfx/pokemon/scyther/anim.asm"
ElectabuzzAnimation: INCLUDE "gfx/pokemon/electabuzz/anim.asm"
MagmarAnimation:     INCLUDE "gfx/pokemon/magmar/anim.asm"
PinsirAnimation:     INCLUDE "gfx/pokemon/pinsir/anim.asm"
LaprasAnimation:     INCLUDE "gfx/pokemon/lapras/anim.asm"
DittoAnimation:      INCLUDE "gfx/pokemon/ditto/anim.asm"
EeveeAnimation:      INCLUDE "gfx/pokemon/eevee/anim.asm"
VaporeonAnimation:   INCLUDE "gfx/pokemon/vaporeon/anim.asm"
JolteonAnimation:    INCLUDE "gfx/pokemon/jolteon/anim.asm"
FlareonAnimation:    INCLUDE "gfx/pokemon/flareon/anim.asm"
SnorlaxAnimation:    INCLUDE "gfx/pokemon/snorlax/anim.asm"
DratiniAnimation:    INCLUDE "gfx/pokemon/dratini/anim.asm"
DragonairAnimation:  INCLUDE "gfx/pokemon/dragonair/anim.asm"
DragoniteAnimation:  INCLUDE "gfx/pokemon/dragonite/anim.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim.asm"
CleffaAnimation:     INCLUDE "gfx/pokemon/cleffa/anim.asm"
IgglybuffAnimation:  INCLUDE "gfx/pokemon/igglybuff/anim.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim.asm"
DelibirdAnimation:   INCLUDE "gfx/pokemon/delibird/anim.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim.asm"
LotadAnimation:      INCLUDE "gfx/pokemon/lotad/anim.asm"
LombreAnimation:     INCLUDE "gfx/pokemon/lombre/anim.asm"
LudicoloAnimation:   INCLUDE "gfx/pokemon/ludicolo/anim.asm"
SeedotAnimation:     INCLUDE "gfx/pokemon/seedot/anim.asm"
NuzleafAnimation:    INCLUDE "gfx/pokemon/nuzleaf/anim.asm"
ShiftryAnimation:    INCLUDE "gfx/pokemon/shiftry/anim.asm"
WingullAnimation:    INCLUDE "gfx/pokemon/wingull/anim.asm"
PelipperAnimation:   INCLUDE "gfx/pokemon/pelipper/anim.asm"
RaltsAnimation:      INCLUDE "gfx/pokemon/ralts/anim.asm"
KirliaAnimation:     INCLUDE "gfx/pokemon/kirlia/anim.asm"
GardevoirAnimation:  INCLUDE "gfx/pokemon/gardevoir/anim.asm"
ShroomishAnimation:  INCLUDE "gfx/pokemon/shroomish/anim.asm"
BreloomAnimation:    INCLUDE "gfx/pokemon/breloom/anim.asm"
SlakothAnimation:    INCLUDE "gfx/pokemon/slakoth/anim.asm"
VigorothAnimation:   INCLUDE "gfx/pokemon/vigoroth/anim.asm"
SlakingAnimation:    INCLUDE "gfx/pokemon/slaking/anim.asm"
AzurillAnimation:    INCLUDE "gfx/pokemon/azurill/anim.asm"
NosepassAnimation:   INCLUDE "gfx/pokemon/nosepass/anim.asm"
SkittyAnimation:     INCLUDE "gfx/pokemon/skitty/anim.asm"
DelcattyAnimation:   INCLUDE "gfx/pokemon/delcatty/anim.asm"
SableyeAnimation:    INCLUDE "gfx/pokemon/sableye/anim.asm"
MawileAnimation:     INCLUDE "gfx/pokemon/mawile/anim.asm"
AronAnimation:       INCLUDE "gfx/pokemon/aron/anim.asm"
LaironAnimation:     INCLUDE "gfx/pokemon/lairon/anim.asm"
AggronAnimation:     INCLUDE "gfx/pokemon/aggron/anim.asm"
MedititeAnimation:   INCLUDE "gfx/pokemon/meditite/anim.asm"
MedichamAnimation:   INCLUDE "gfx/pokemon/medicham/anim.asm"
RoseliaAnimation:    INCLUDE "gfx/pokemon/roselia/anim.asm"
WailmerAnimation:    INCLUDE "gfx/pokemon/wailmer/anim.asm"
WailordAnimation:    INCLUDE "gfx/pokemon/wailord/anim.asm"
NumelAnimation:      INCLUDE "gfx/pokemon/numel/anim.asm"
CameruptAnimation:   INCLUDE "gfx/pokemon/camerupt/anim.asm"
TorkoalAnimation:    INCLUDE "gfx/pokemon/torkoal/anim.asm"
SpoinkAnimation:     INCLUDE "gfx/pokemon/spoink/anim.asm"
GrumpigAnimation:    INCLUDE "gfx/pokemon/grumpig/anim.asm"
TrapinchAnimation:   INCLUDE "gfx/pokemon/trapinch/anim.asm"
VibravaAnimation:    INCLUDE "gfx/pokemon/vibrava/anim.asm"
FlygonAnimation:     INCLUDE "gfx/pokemon/flygon/anim.asm"
SwabluAnimation:     INCLUDE "gfx/pokemon/swablu/anim.asm"
AltariaAnimation:    INCLUDE "gfx/pokemon/altaria/anim.asm"
ZangooseAnimation:   INCLUDE "gfx/pokemon/zangoose/anim.asm"
SeviperAnimation:    INCLUDE "gfx/pokemon/seviper/anim.asm"
LunatoneAnimation:   INCLUDE "gfx/pokemon/lunatone/anim.asm"
SolrockAnimation:    INCLUDE "gfx/pokemon/solrock/anim.asm"
CorphishAnimation:   INCLUDE "gfx/pokemon/corphish/anim.asm"
CrawdauntAnimation:  INCLUDE "gfx/pokemon/crawdaunt/anim.asm"
BaltoyAnimation:     INCLUDE "gfx/pokemon/baltoy/anim.asm"
ClaydolAnimation:    INCLUDE "gfx/pokemon/claydol/anim.asm"
ShuppetAnimation:    INCLUDE "gfx/pokemon/shuppet/anim.asm"
BanetteAnimation:    INCLUDE "gfx/pokemon/banette/anim.asm"
TropiusAnimation:    INCLUDE "gfx/pokemon/tropius/anim.asm"
AbsolAnimation:      INCLUDE "gfx/pokemon/absol/anim.asm"
SnoruntAnimation:    INCLUDE "gfx/pokemon/snorunt/anim.asm"
GlalieAnimation:     INCLUDE "gfx/pokemon/glalie/anim.asm"
SphealAnimation:     INCLUDE "gfx/pokemon/spheal/anim.asm"
SealeoAnimation:     INCLUDE "gfx/pokemon/sealeo/anim.asm"
WalreinAnimation:    INCLUDE "gfx/pokemon/walrein/anim.asm"
BagonAnimation:      INCLUDE "gfx/pokemon/bagon/anim.asm"
ShelgonAnimation:    INCLUDE "gfx/pokemon/shelgon/anim.asm"
SalamenceAnimation:  INCLUDE "gfx/pokemon/salamence/anim.asm"
BeldumAnimation:     INCLUDE "gfx/pokemon/beldum/anim.asm"
MetangAnimation:     INCLUDE "gfx/pokemon/metang/anim.asm"
MetagrossAnimation:  INCLUDE "gfx/pokemon/metagross/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim.asm"
BonslyAnimation:     INCLUDE "gfx/pokemon/bonsly/anim.asm"
MimeJrAnimation:     INCLUDE "gfx/pokemon/mime_jr_/anim.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim.asm"
MantykeAnimation:    INCLUDE "gfx/pokemon/mantyke/anim.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim.asm"
LickilickyAnimation: INCLUDE "gfx/pokemon/lickilicky/anim.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim.asm"
PerrserkerAnimation: INCLUDE "gfx/pokemon/perrserker/anim.asm"
CursolaAnimation:    INCLUDE "gfx/pokemon/cursola/anim.asm"
MrRimeAnimation:     INCLUDE "gfx/pokemon/mr__rime/anim.asm"
KleavorAnimation:    INCLUDE "gfx/pokemon/kleavor/anim.asm"
SneaslerAnimation:   INCLUDE "gfx/pokemon/sneasler/anim.asm"
AnnihilapeAnimation: INCLUDE "gfx/pokemon/annihilape/anim.asm"
VictiniAnimation:    INCLUDE "gfx/pokemon/victini/anim.asm"
SnivyAnimation:      INCLUDE "gfx/pokemon/snivy/anim.asm"
ServineAnimation:    INCLUDE "gfx/pokemon/servine/anim.asm"
SerperiorAnimation:  INCLUDE "gfx/pokemon/serperior/anim.asm"
TepigAnimation:      INCLUDE "gfx/pokemon/tepig/anim.asm"
PigniteAnimation:    INCLUDE "gfx/pokemon/pignite/anim.asm"
EmboarAnimation:     INCLUDE "gfx/pokemon/emboar/anim.asm"
OshawottAnimation:   INCLUDE "gfx/pokemon/oshawott/anim.asm"
DewottAnimation:     INCLUDE "gfx/pokemon/dewott/anim.asm"
PatratAnimation:     INCLUDE "gfx/pokemon/patrat/anim.asm"
WatchogAnimation:    INCLUDE "gfx/pokemon/watchog/anim.asm"
LillipupAnimation:   INCLUDE "gfx/pokemon/lillipup/anim.asm"
HerdierAnimation:    INCLUDE "gfx/pokemon/herdier/anim.asm"
StoutlandAnimation:  INCLUDE "gfx/pokemon/stoutland/anim.asm"
PurrloinAnimation:   INCLUDE "gfx/pokemon/purrloin/anim.asm"
LiepardAnimation:    INCLUDE "gfx/pokemon/liepard/anim.asm"
PansageAnimation:    INCLUDE "gfx/pokemon/pansage/anim.asm"
SimisageAnimation:   INCLUDE "gfx/pokemon/simisage/anim.asm"
PansearAnimation:    INCLUDE "gfx/pokemon/pansear/anim.asm"
SimisearAnimation:   INCLUDE "gfx/pokemon/simisear/anim.asm"
PanpourAnimation:    INCLUDE "gfx/pokemon/panpour/anim.asm"
SimipourAnimation:   INCLUDE "gfx/pokemon/simipour/anim.asm"
MunnaAnimation:      INCLUDE "gfx/pokemon/munna/anim.asm"
MusharnaAnimation:   INCLUDE "gfx/pokemon/musharna/anim.asm"
PidoveAnimation:     INCLUDE "gfx/pokemon/pidove/anim.asm"
TranquillAnimation:  INCLUDE "gfx/pokemon/tranquill/anim.asm"
BlitzleAnimation:    INCLUDE "gfx/pokemon/blitzle/anim.asm"
ZebstrikaAnimation:  INCLUDE "gfx/pokemon/zebstrika/anim.asm"
RoggenrolaAnimation: INCLUDE "gfx/pokemon/roggenrola/anim.asm"
BoldoreAnimation:    INCLUDE "gfx/pokemon/boldore/anim.asm"
GigalithAnimation:   INCLUDE "gfx/pokemon/gigalith/anim.asm"
WoobatAnimation:     INCLUDE "gfx/pokemon/woobat/anim.asm"
SwoobatAnimation:    INCLUDE "gfx/pokemon/swoobat/anim.asm"
DrilburAnimation:    INCLUDE "gfx/pokemon/drilbur/anim.asm"
ExcadrillAnimation:  INCLUDE "gfx/pokemon/excadrill/anim.asm"
AudinoAnimation:     INCLUDE "gfx/pokemon/audino/anim.asm"
TimburrAnimation:    INCLUDE "gfx/pokemon/timburr/anim.asm"
GurdurrAnimation:    INCLUDE "gfx/pokemon/gurdurr/anim.asm"
ConkeldurrAnimation: INCLUDE "gfx/pokemon/conkeldurr/anim.asm"
TympoleAnimation:    INCLUDE "gfx/pokemon/tympole/anim.asm"
PalpitoadAnimation:  INCLUDE "gfx/pokemon/palpitoad/anim.asm"
SeismitoadAnimation: INCLUDE "gfx/pokemon/seismitoad/anim.asm"
ThrohAnimation:      INCLUDE "gfx/pokemon/throh/anim.asm"
SawkAnimation:       INCLUDE "gfx/pokemon/sawk/anim.asm"
SewaddleAnimation:   INCLUDE "gfx/pokemon/sewaddle/anim.asm"
SwadloonAnimation:   INCLUDE "gfx/pokemon/swadloon/anim.asm"
LeavannyAnimation:   INCLUDE "gfx/pokemon/leavanny/anim.asm"
VenipedeAnimation:   INCLUDE "gfx/pokemon/venipede/anim.asm"
WhirlipedeAnimation: INCLUDE "gfx/pokemon/whirlipede/anim.asm"
ScolipedeAnimation:  INCLUDE "gfx/pokemon/scolipede/anim.asm"
CottoneeAnimation:   INCLUDE "gfx/pokemon/cottonee/anim.asm"
WhimsicottAnimation: INCLUDE "gfx/pokemon/whimsicott/anim.asm"
PetililAnimation:    INCLUDE "gfx/pokemon/petilil/anim.asm"
SandileAnimation:    INCLUDE "gfx/pokemon/sandile/anim.asm"
KrokorokAnimation:   INCLUDE "gfx/pokemon/krokorok/anim.asm"
KrookodileAnimation: INCLUDE "gfx/pokemon/krookodile/anim.asm"
MaractusAnimation:   INCLUDE "gfx/pokemon/maractus/anim.asm"
DwebbleAnimation:    INCLUDE "gfx/pokemon/dwebble/anim.asm"
CrustleAnimation:    INCLUDE "gfx/pokemon/crustle/anim.asm"
ScraggyAnimation:    INCLUDE "gfx/pokemon/scraggy/anim.asm"
ScraftyAnimation:    INCLUDE "gfx/pokemon/scrafty/anim.asm"
SigilyphAnimation:   INCLUDE "gfx/pokemon/sigilyph/anim.asm"
CofagrigusAnimation: INCLUDE "gfx/pokemon/cofagrigus/anim.asm"
TirtougaAnimation:   INCLUDE "gfx/pokemon/tirtouga/anim.asm"
CarracostaAnimation: INCLUDE "gfx/pokemon/carracosta/anim.asm"
ArchenAnimation:     INCLUDE "gfx/pokemon/archen/anim.asm"
ArcheopsAnimation:   INCLUDE "gfx/pokemon/archeops/anim.asm"
TrubbishAnimation:   INCLUDE "gfx/pokemon/trubbish/anim.asm"
GarbodorAnimation:   INCLUDE "gfx/pokemon/garbodor/anim.asm"
MinccinoAnimation:   INCLUDE "gfx/pokemon/minccino/anim.asm"
CinccinoAnimation:   INCLUDE "gfx/pokemon/cinccino/anim.asm"
GothitaAnimation:    INCLUDE "gfx/pokemon/gothita/anim.asm"
GothoritaAnimation:  INCLUDE "gfx/pokemon/gothorita/anim.asm"
GothitelleAnimation: INCLUDE "gfx/pokemon/gothitelle/anim.asm"
SolosisAnimation:    INCLUDE "gfx/pokemon/solosis/anim.asm"
DuosionAnimation:    INCLUDE "gfx/pokemon/duosion/anim.asm"
ReuniclusAnimation:  INCLUDE "gfx/pokemon/reuniclus/anim.asm"
DucklettAnimation:   INCLUDE "gfx/pokemon/ducklett/anim.asm"
SwannaAnimation:     INCLUDE "gfx/pokemon/swanna/anim.asm"
VanilliteAnimation:  INCLUDE "gfx/pokemon/vanillite/anim.asm"
VanillishAnimation:  INCLUDE "gfx/pokemon/vanillish/anim.asm"
VanilluxeAnimation:  INCLUDE "gfx/pokemon/vanilluxe/anim.asm"
EmolgaAnimation:     INCLUDE "gfx/pokemon/emolga/anim.asm"
KarrablastAnimation: INCLUDE "gfx/pokemon/karrablast/anim.asm"
EscavalierAnimation: INCLUDE "gfx/pokemon/escavalier/anim.asm"
FoongusAnimation:    INCLUDE "gfx/pokemon/foongus/anim.asm"
AmoongussAnimation:  INCLUDE "gfx/pokemon/amoonguss/anim.asm"
AlomomolaAnimation:  INCLUDE "gfx/pokemon/alomomola/anim.asm"
JoltikAnimation:     INCLUDE "gfx/pokemon/joltik/anim.asm"
GalvantulaAnimation: INCLUDE "gfx/pokemon/galvantula/anim.asm"
FerroseedAnimation:  INCLUDE "gfx/pokemon/ferroseed/anim.asm"
FerrothornAnimation: INCLUDE "gfx/pokemon/ferrothorn/anim.asm"
KlinkAnimation:      INCLUDE "gfx/pokemon/klink/anim.asm"
KlangAnimation:      INCLUDE "gfx/pokemon/klang/anim.asm"
KlinklangAnimation:  INCLUDE "gfx/pokemon/klinklang/anim.asm"
TynamoAnimation:     INCLUDE "gfx/pokemon/tynamo/anim.asm"
EelektrikAnimation:  INCLUDE "gfx/pokemon/eelektrik/anim.asm"
EelektrossAnimation: INCLUDE "gfx/pokemon/eelektross/anim.asm"
ElgyemAnimation:     INCLUDE "gfx/pokemon/elgyem/anim.asm"
BeheeyemAnimation:   INCLUDE "gfx/pokemon/beheeyem/anim.asm"
LitwickAnimation:    INCLUDE "gfx/pokemon/litwick/anim.asm"
LampentAnimation:    INCLUDE "gfx/pokemon/lampent/anim.asm"
ChandelureAnimation: INCLUDE "gfx/pokemon/chandelure/anim.asm"
AxewAnimation:       INCLUDE "gfx/pokemon/axew/anim.asm"
FraxureAnimation:    INCLUDE "gfx/pokemon/fraxure/anim.asm"
HaxorusAnimation:    INCLUDE "gfx/pokemon/haxorus/anim.asm"
CubchooAnimation:    INCLUDE "gfx/pokemon/cubchoo/anim.asm"
BearticAnimation:    INCLUDE "gfx/pokemon/beartic/anim.asm"
CryogonalAnimation:  INCLUDE "gfx/pokemon/cryogonal/anim.asm"
ShelmetAnimation:    INCLUDE "gfx/pokemon/shelmet/anim.asm"
AccelgorAnimation:   INCLUDE "gfx/pokemon/accelgor/anim.asm"
MienfooAnimation:    INCLUDE "gfx/pokemon/mienfoo/anim.asm"
MienshaoAnimation:   INCLUDE "gfx/pokemon/mienshao/anim.asm"
DruddigonAnimation:  INCLUDE "gfx/pokemon/druddigon/anim.asm"
GolettAnimation:     INCLUDE "gfx/pokemon/golett/anim.asm"
GolurkAnimation:     INCLUDE "gfx/pokemon/golurk/anim.asm"
PawniardAnimation:   INCLUDE "gfx/pokemon/pawniard/anim.asm"
BisharpAnimation:    INCLUDE "gfx/pokemon/bisharp/anim.asm"
BouffalantAnimation: INCLUDE "gfx/pokemon/bouffalant/anim.asm"
RuffletAnimation:    INCLUDE "gfx/pokemon/rufflet/anim.asm"
VullabyAnimation:    INCLUDE "gfx/pokemon/vullaby/anim.asm"
MandibuzzAnimation:  INCLUDE "gfx/pokemon/mandibuzz/anim.asm"
HeatmorAnimation:    INCLUDE "gfx/pokemon/heatmor/anim.asm"
DurantAnimation:     INCLUDE "gfx/pokemon/durant/anim.asm"
DeinoAnimation:      INCLUDE "gfx/pokemon/deino/anim.asm"
ZweilousAnimation:   INCLUDE "gfx/pokemon/zweilous/anim.asm"
HydreigonAnimation:  INCLUDE "gfx/pokemon/hydreigon/anim.asm"
LarvestaAnimation:   INCLUDE "gfx/pokemon/larvesta/anim.asm"
VolcaronaAnimation:  INCLUDE "gfx/pokemon/volcarona/anim.asm"
CobalionAnimation:   INCLUDE "gfx/pokemon/cobalion/anim.asm"
TerrakionAnimation:  INCLUDE "gfx/pokemon/terrakion/anim.asm"
VirizionAnimation:   INCLUDE "gfx/pokemon/virizion/anim.asm"
ReshiramAnimation:   INCLUDE "gfx/pokemon/reshiram/anim.asm"
ZekromAnimation:     INCLUDE "gfx/pokemon/zekrom/anim.asm"
KeldeoAnimation:     INCLUDE "gfx/pokemon/keldeo/anim.asm"
GenesectAnimation:   INCLUDE "gfx/pokemon/genesect/anim.asm"
RunerigusAnimation:  INCLUDE "gfx/pokemon/runerigus/anim.asm"

EggAnimation:        INCLUDE "gfx/pokemon/egg/anim.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim.asm"

PikachuPlainAnimation:  INCLUDE "gfx/pokemon/pikachu_plain/anim.asm"
PikachuFlyAnimation:    INCLUDE "gfx/pokemon/pikachu_fly/anim.asm"
PikachuSurfAnimation:   INCLUDE "gfx/pokemon/pikachu_surf/anim.asm"
PikachuPikaAnimation:   INCLUDE "gfx/pokemon/pikachu_pika/anim.asm"
PikachuChuchuAnimation: INCLUDE "gfx/pokemon/pikachu_chuchu/anim.asm"
PikachuSparkAnimation:  INCLUDE "gfx/pokemon/pikachu_spark/anim.asm"

DudunsparceTwoSegmentAnimation:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim.asm"
DudunsparceThreeSegmentAnimation: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim.asm"

RattataPlainAnimation:  INCLUDE "gfx/pokemon/rattata_plain/anim.asm"
RattataAlolanAnimation: INCLUDE "gfx/pokemon/rattata_alolan/anim.asm"

RaticatePlainAnimation:  INCLUDE "gfx/pokemon/raticate_plain/anim.asm"
RaticateAlolanAnimation: INCLUDE "gfx/pokemon/raticate_alolan/anim.asm"

RaichuPlainAnimation:  INCLUDE "gfx/pokemon/raichu_plain/anim.asm"
RaichuAlolanAnimation: INCLUDE "gfx/pokemon/raichu_alolan/anim.asm"

SandshrewPlainAnimation:  INCLUDE "gfx/pokemon/sandshrew_plain/anim.asm"
SandshrewAlolanAnimation: INCLUDE "gfx/pokemon/sandshrew_alolan/anim.asm"

SandslashPlainAnimation:  INCLUDE "gfx/pokemon/sandslash_plain/anim.asm"
SandslashAlolanAnimation: INCLUDE "gfx/pokemon/sandslash_alolan/anim.asm"

VulpixPlainAnimation:  INCLUDE "gfx/pokemon/vulpix_plain/anim.asm"
VulpixAlolanAnimation: INCLUDE "gfx/pokemon/vulpix_alolan/anim.asm"

NinetalesPlainAnimation:  INCLUDE "gfx/pokemon/ninetales_plain/anim.asm"
NinetalesAlolanAnimation: INCLUDE "gfx/pokemon/ninetales_alolan/anim.asm"

MeowthPlainAnimation:    INCLUDE "gfx/pokemon/meowth_plain/anim.asm"
MeowthAlolanAnimation:   INCLUDE "gfx/pokemon/meowth_alolan/anim.asm"
MeowthGalarianAnimation: INCLUDE "gfx/pokemon/meowth_galarian/anim.asm"

PersianPlainAnimation:  INCLUDE "gfx/pokemon/persian_plain/anim.asm"
PersianAlolanAnimation: INCLUDE "gfx/pokemon/persian_alolan/anim.asm"

GeodudePlainAnimation:  INCLUDE "gfx/pokemon/geodude_plain/anim.asm"
GeodudeAlolanAnimation: INCLUDE "gfx/pokemon/geodude_alolan/anim.asm"

GravelerPlainAnimation:  INCLUDE "gfx/pokemon/graveler_plain/anim.asm"
GravelerAlolanAnimation: INCLUDE "gfx/pokemon/graveler_alolan/anim.asm"

GolemPlainAnimation:  INCLUDE "gfx/pokemon/golem_plain/anim.asm"
GolemAlolanAnimation: INCLUDE "gfx/pokemon/golem_alolan/anim.asm"

GrimerPlainAnimation:  INCLUDE "gfx/pokemon/grimer_plain/anim.asm"
GrimerAlolanAnimation: INCLUDE "gfx/pokemon/grimer_alolan/anim.asm"

MukPlainAnimation:  INCLUDE "gfx/pokemon/muk_plain/anim.asm"
MukAlolanAnimation: INCLUDE "gfx/pokemon/muk_alolan/anim.asm"

ExeggutorPlainAnimation:  INCLUDE "gfx/pokemon/exeggutor_plain/anim.asm"
ExeggutorAlolanAnimation: INCLUDE "gfx/pokemon/exeggutor_alolan/anim.asm"

PonytaPlainAnimation:    INCLUDE "gfx/pokemon/ponyta_plain/anim.asm"
PonytaGalarianAnimation: INCLUDE "gfx/pokemon/ponyta_galarian/anim.asm"

RapidashPlainAnimation:    INCLUDE "gfx/pokemon/rapidash_plain/anim.asm"
RapidashGalarianAnimation: INCLUDE "gfx/pokemon/rapidash_galarian/anim.asm"

SlowpokePlainAnimation:    INCLUDE "gfx/pokemon/slowpoke_plain/anim.asm"
SlowpokeGalarianAnimation: INCLUDE "gfx/pokemon/slowpoke_galarian/anim.asm"

SlowbroPlainAnimation:    INCLUDE "gfx/pokemon/slowbro_plain/anim.asm"
SlowbroGalarianAnimation: INCLUDE "gfx/pokemon/slowbro_galarian/anim.asm"

WeezingPlainAnimation:    INCLUDE "gfx/pokemon/weezing_plain/anim.asm"
WeezingGalarianAnimation: INCLUDE "gfx/pokemon/weezing_galarian/anim.asm"

MrMimePlainAnimation:    INCLUDE "gfx/pokemon/mr__mime_plain/anim.asm"
MrMimeGalarianAnimation: INCLUDE "gfx/pokemon/mr__mime_galarian/anim.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim.asm"

CorsolaPlainAnimation:    INCLUDE "gfx/pokemon/corsola_plain/anim.asm"
CorsolaGalarianAnimation: INCLUDE "gfx/pokemon/corsola_galarian/anim.asm"

GrowlithePlainAnimation:   INCLUDE "gfx/pokemon/growlithe_plain/anim.asm"
GrowlitheHisuianAnimation: INCLUDE "gfx/pokemon/growlithe_hisuian/anim.asm"

ArcaninePlainAnimation:   INCLUDE "gfx/pokemon/arcanine_plain/anim.asm"
ArcanineHisuianAnimation: INCLUDE "gfx/pokemon/arcanine_hisuian/anim.asm"

SneaselPlainAnimation:   INCLUDE "gfx/pokemon/sneasel_plain/anim.asm"
SneaselHisuianAnimation: INCLUDE "gfx/pokemon/sneasel_hisuian/anim.asm"

CastformPlainAnimation: INCLUDE "gfx/pokemon/castform_plain/anim.asm"
CastformSunAnimation:   INCLUDE "gfx/pokemon/castform_sun/anim.asm"
CastformRainAnimation:  INCLUDE "gfx/pokemon/castform_rain/anim.asm"
CastformHailAnimation:  INCLUDE "gfx/pokemon/castform_hail/anim.asm"

UnfezantMaleAnimation:   INCLUDE "gfx/pokemon/unfezant_male/anim.asm"
UnfezantFemaleAnimation: INCLUDE "gfx/pokemon/unfezant_female/anim.asm"

SamurottPlainAnimation: INCLUDE "gfx/pokemon/samurott_plain/anim.asm"

LilligantPlainAnimation: INCLUDE "gfx/pokemon/lilligant_plain/anim.asm"

BasculinRedAnimation:   INCLUDE "gfx/pokemon/basculin_red/anim.asm"
BasculinBlueAnimation:  INCLUDE "gfx/pokemon/basculin_blue/anim.asm"
BasculinWhiteAnimation: INCLUDE "gfx/pokemon/basculin_white/anim.asm"

DarumakaPlainAnimation:    INCLUDE "gfx/pokemon/darumaka_plain/anim.asm"
DarumakaGalarianAnimation: INCLUDE "gfx/pokemon/darumaka_galarian/anim.asm"

DarmanitanPlainAnimation:       INCLUDE "gfx/pokemon/darmanitan_plain/anim.asm"
DarmanitanZenAnimation:         INCLUDE "gfx/pokemon/darmanitan_zen/anim.asm"
DarmanitanGalarianAnimation:    INCLUDE "gfx/pokemon/darmanitan_galarian/anim.asm"
DarmanitanGalarianZenAnimation: INCLUDE "gfx/pokemon/darmanitan_galarian_zen/anim.asm"

YamaskPlainAnimation:    INCLUDE "gfx/pokemon/yamask_plain/anim.asm"
YamaskGalarianAnimation: INCLUDE "gfx/pokemon/yamask_galarian/anim.asm"

ZoruaPlainAnimation: INCLUDE "gfx/pokemon/zorua_plain/anim.asm"

ZoroarkPlainAnimation: INCLUDE "gfx/pokemon/zoroark_plain/anim.asm"

DeerlingSpringAnimation: INCLUDE "gfx/pokemon/deerling_spring/anim.asm"
DeerlingSummerAnimation: INCLUDE "gfx/pokemon/deerling_summer/anim.asm"
DeerlingAutumnAnimation: INCLUDE "gfx/pokemon/deerling_autumn/anim.asm"
DeerlingWinterAnimation: INCLUDE "gfx/pokemon/deerling_winter/anim.asm"

SawsbuckSpringAnimation: INCLUDE "gfx/pokemon/sawsbuck_spring/anim.asm"
SawsbuckSummerAnimation: INCLUDE "gfx/pokemon/sawsbuck_summer/anim.asm"
SawsbuckAutumnAnimation: INCLUDE "gfx/pokemon/sawsbuck_autumn/anim.asm"
SawsbuckWinterAnimation: INCLUDE "gfx/pokemon/sawsbuck_winter/anim.asm"

FrillishMaleAnimation:   INCLUDE "gfx/pokemon/frillish_male/anim.asm"
FrillishFemaleAnimation: INCLUDE "gfx/pokemon/frillish_female/anim.asm"

JellicentMaleAnimation:   INCLUDE "gfx/pokemon/jellicent_male/anim.asm"
JellicentFemaleAnimation: INCLUDE "gfx/pokemon/jellicent_female/anim.asm"

StunfiskPlainAnimation: INCLUDE "gfx/pokemon/stunfisk_plain/anim.asm"

BraviaryPlainAnimation: INCLUDE "gfx/pokemon/braviary_plain/anim.asm"

TornadusPlainAnimation:   INCLUDE "gfx/pokemon/tornadus_plain/anim.asm"
TornadusTherianAnimation: INCLUDE "gfx/pokemon/tornadus_therian/anim.asm"

ThundurusPlainAnimation:   INCLUDE "gfx/pokemon/thundurus_plain/anim.asm"
ThundurusTherianAnimation: INCLUDE "gfx/pokemon/thundurus_therian/anim.asm"

LandorusPlainAnimation:   INCLUDE "gfx/pokemon/landorus_plain/anim.asm"
LandorusTherianAnimation: INCLUDE "gfx/pokemon/landorus_therian/anim.asm"

KyuremPlainAnimation: INCLUDE "gfx/pokemon/kyurem_plain/anim.asm"
KyuremWhiteAnimation: INCLUDE "gfx/pokemon/kyurem_white/anim.asm"
KyuremBlackAnimation: INCLUDE "gfx/pokemon/kyurem_black/anim.asm"

MeloettaPlainAnimation:     INCLUDE "gfx/pokemon/meloetta_plain/anim.asm"
MeloettaPirouetteAnimation: INCLUDE "gfx/pokemon/meloetta_pirouette/anim.asm"
