BitmasksPointers:
	table_width 2
	dw RattataPlainBitmasks
	dw RaticatePlainBitmasks
	dw PikachuPlainBitmasks
	dw RaichuPlainBitmasks
	dw SandshrewPlainBitmasks
	dw SandslashPlainBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixPlainBitmasks
	dw NinetalesPlainBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw MeowthPlainBitmasks
	dw PersianPlainBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlithePlainBitmasks
	dw ArcaninePlainBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw GeodudePlainBitmasks
	dw GravelerPlainBitmasks
	dw GolemPlainBitmasks
	dw PonytaPlainBitmasks
	dw RapidashPlainBitmasks
	dw SlowpokePlainBitmasks
	dw SlowbroPlainBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerPlainBitmasks
	dw MukPlainBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorPlainBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingPlainBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimePlainBitmasks
	dw ScytherBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw SnorlaxBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuPlainBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingPlainBitmasks
	dw MisdreavusBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselPlainBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaPlainBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw SeedotBitmasks
	dw NuzleafBitmasks
	dw ShiftryBitmasks
	dw WingullBitmasks
	dw PelipperBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw SlakothBitmasks
	dw VigorothBitmasks
	dw SlakingBitmasks
	dw AzurillBitmasks
	dw NosepassBitmasks
	dw SkittyBitmasks
	dw DelcattyBitmasks
	dw SableyeBitmasks
	dw MawileBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw MedititeBitmasks
	dw MedichamBitmasks
	dw RoseliaBitmasks
	dw WailmerBitmasks
	dw WailordBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw TorkoalBitmasks
	dw SpoinkBitmasks
	dw GrumpigBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw ZangooseBitmasks
	dw SeviperBitmasks
	dw LunatoneBitmasks
	dw SolrockBitmasks
	dw CorphishBitmasks
	dw CrawdauntBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw CastformPlainBitmasks
	dw ShuppetBitmasks
	dw BanetteBitmasks
	dw TropiusBitmasks
	dw AbsolBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw SphealBitmasks
	dw SealeoBitmasks
	dw WalreinBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw StarlyBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw BudewBitmasks
	dw RoseradeBitmasks
	dw CombeeFemaleBitmasks
	dw VespiquenBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw MunchlaxBitmasks
	dw MantykeBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw VictiniBitmasks
	dw SnivyBitmasks
	dw ServineBitmasks
	dw SerperiorBitmasks
	dw TepigBitmasks
	dw PigniteBitmasks
	dw EmboarBitmasks
	dw OshawottBitmasks
	dw DewottBitmasks
	dw SamurottPlainBitmasks
	dw PatratBitmasks
	dw WatchogBitmasks
	dw LillipupBitmasks
	dw HerdierBitmasks
	dw StoutlandBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw PansageBitmasks
	dw SimisageBitmasks
	dw PansearBitmasks
	dw SimisearBitmasks
	dw PanpourBitmasks
	dw SimipourBitmasks
	dw MunnaBitmasks
	dw MusharnaBitmasks
	dw PidoveBitmasks
	dw TranquillBitmasks
	dw UnfezantMaleBitmasks
	dw BlitzleBitmasks
	dw ZebstrikaBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw RoggenrolaBitmasks
	dw BoldoreBitmasks
	dw GigalithBitmasks
	dw WoobatBitmasks
	dw SwoobatBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw AudinoBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw TympoleBitmasks
	dw PalpitoadBitmasks
	dw SeismitoadBitmasks
	dw ThrohBitmasks
	dw SawkBitmasks
	dw SewaddleBitmasks
	dw SwadloonBitmasks
	dw LeavannyBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw PetililBitmasks
	dw LilligantPlainBitmasks
	dw BasculinWhiteBitmasks
	dw SandileBitmasks
	dw KrokorokBitmasks
	dw KrookodileBitmasks
	dw DarumakaPlainBitmasks
	dw DarmanitanPlainBitmasks
	dw MaractusBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw ScraggyBitmasks
	dw ScraftyBitmasks
	dw SigilyphBitmasks
	dw YamaskPlainBitmasks
	dw CofagrigusBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw TrubbishBitmasks
	dw GarbodorBitmasks
	dw ZoruaPlainBitmasks
	dw ZoroarkPlainBitmasks
	dw MinccinoBitmasks
	dw CinccinoBitmasks
	dw GothitaBitmasks
	dw GothoritaBitmasks
	dw GothitelleBitmasks
	dw SolosisBitmasks
	dw DuosionBitmasks
	dw ReuniclusBitmasks
	dw DucklettBitmasks
	dw SwannaBitmasks
	dw VanilliteBitmasks
	dw VanillishBitmasks
	dw VanilluxeBitmasks
	dw DeerlingSpringBitmasks
	dw SawsbuckSpringBitmasks
	dw EmolgaBitmasks
	dw KarrablastBitmasks
	dw EscavalierBitmasks
	dw FoongusBitmasks
	dw AmoongussBitmasks
	dw FrillishMaleBitmasks
	dw JellicentMaleBitmasks
	dw AlomomolaBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw FerroseedBitmasks
	dw FerrothornBitmasks
	dw KlinkBitmasks
	dw KlangBitmasks
	dw KlinklangBitmasks
	dw TynamoBitmasks
	dw EelektrikBitmasks
	dw EelektrossBitmasks
	dw ElgyemBitmasks
	dw BeheeyemBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw HaxorusBitmasks
	dw CubchooBitmasks
	dw BearticBitmasks
	dw CryogonalBitmasks
	dw ShelmetBitmasks
	dw AccelgorBitmasks
	dw StunfiskPlainBitmasks
	dw MienfooBitmasks
	dw MienshaoBitmasks
	dw DruddigonBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw BouffalantBitmasks
	dw RuffletBitmasks
	dw BraviaryPlainBitmasks
	dw VullabyBitmasks
	dw MandibuzzBitmasks
	dw HeatmorBitmasks
	dw DurantBitmasks
	dw DeinoBitmasks
	dw ZweilousBitmasks
	dw HydreigonBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw CobalionBitmasks
	dw TerrakionBitmasks
	dw VirizionBitmasks
	dw TornadusPlainBitmasks
	dw ThundurusPlainBitmasks
	dw ReshiramBitmasks
	dw ZekromBitmasks
	dw LandorusPlainBitmasks
	dw KyuremPlainBitmasks
	dw KeldeoBitmasks
	dw MeloettaPlainBitmasks
	dw GenesectBitmasks
	dw SylveonBitmasks
	dw PerrserkerBitmasks
	dw CursolaBitmasks
	dw MrRimeBitmasks
	dw RunerigusBitmasks
	dw KleavorBitmasks
	dw SneaslerBitmasks
	dw AnnihilapeBitmasks
	dw DudunsparceTwoSegmentBitmasks
	assert_table_length NUM_SPECIES

	dw PikachuFlyBitmasks
	dw PikachuSurfBitmasks
	dw PikachuPikaBitmasks
	dw PikachuChuchuBitmasks
	dw PikachuSparkBitmasks

	dw PichuSpikyBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw DudunsparceThreeSegmentBitmasks

	dw RattataAlolanBitmasks
	dw RaticateAlolanBitmasks
	dw RaichuAlolanBitmasks
	dw SandshrewAlolanBitmasks
	dw SandslashAlolanBitmasks
	dw VulpixAlolanBitmasks
	dw NinetalesAlolanBitmasks
	dw MeowthAlolanBitmasks
	dw PersianAlolanBitmasks
	dw GeodudeAlolanBitmasks
	dw GravelerAlolanBitmasks
	dw GolemAlolanBitmasks
	dw GrimerAlolanBitmasks
	dw MukAlolanBitmasks
	dw ExeggutorAlolanBitmasks

	dw MeowthGalarianBitmasks
	dw PonytaGalarianBitmasks
	dw RapidashGalarianBitmasks
	dw SlowpokeGalarianBitmasks
	dw SlowbroGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw MrMimeGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw CorsolaGalarianBitmasks
	dw DarumakaGalarianBitmasks
	dw DarmanitanGalarianBitmasks
	dw YamaskGalarianBitmasks

	dw GrowlitheHisuianBitmasks
	dw ArcanineHisuianBitmasks
	dw SneaselHisuianBitmasks
	
	dw CastformSunBitmasks
	dw CastformRainBitmasks
	dw CastformHailBitmasks
	
	dw CombeeMaleBitmasks
	
	dw UnfezantFemaleBitmasks
	
	dw BasculinRedBitmasks
	dw BasculinBlueBitmasks
	
	dw DarmanitanZenBitmasks
	dw DarmanitanGalarianZenBitmasks
	
	dw DeerlingSummerBitmasks
	dw DeerlingAutumnBitmasks
	dw DeerlingWinterBitmasks
	
	dw SawsbuckSummerBitmasks
	dw SawsbuckAutumnBitmasks
	dw SawsbuckWinterBitmasks
	
	dw FrillishFemaleBitmasks
	dw JellicentFemaleBitmasks
	
	dw TornadusTherianBitmasks
	dw ThundurusTherianBitmasks
	dw LandorusTherianBitmasks
	
	dw KyuremWhiteBitmasks
	dw KyuremBlackBitmasks
	
	dw MeloettaPirouetteBitmasks

	assert_table_length NUM_UNIQUE_POKEMON
