BitmasksPointers:
	table_width 2
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw RattataPlainBitmasks
	dw RaticatePlainBitmasks
	dw EkansBitmasks
	dw ArbokJohtoBitmasks
	dw PikachuPlainBitmasks
	dw RaichuPlainBitmasks
	dw SandshrewPlainBitmasks
	dw SandslashPlainBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixPlainBitmasks
	dw NinetalesPlainBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw DiglettPlainBitmasks
	dw DugtrioPlainBitmasks
	dw MeowthPlainBitmasks
	dw PersianPlainBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlithePlainBitmasks
	dw ArcaninePlainBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw GeodudePlainBitmasks
	dw GravelerPlainBitmasks
	dw GolemPlainBitmasks
	dw PonytaPlainBitmasks
	dw RapidashPlainBitmasks
	dw SlowpokePlainBitmasks
	dw SlowbroPlainBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDPlainBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerPlainBitmasks
	dw MukPlainBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw VoltorbPlainBitmasks
	dw ElectrodePlainBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorPlainBitmasks
	dw CuboneBitmasks
	dw MarowakPlainBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingPlainBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimePlainBitmasks
	dw ScytherBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosPlainBitmasks
	dw MagikarpPlainBitmasks
	dw GyaradosPlainBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw SnorlaxBitmasks
	dw ArticunoPlainBitmasks
	dw ZapdosPlainBitmasks
	dw MoltresPlainBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoPlainBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionPlainBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuPlainBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperPlainBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingPlainBitmasks
	dw MisdreavusBitmasks
	dw UnownABitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishPlainBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselPlainBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaPlainBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw AzurillBitmasks
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw MunchlaxBitmasks
	dw MantykeBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw SylveonBitmasks
	dw PerrserkerBitmasks
	dw CursolaBitmasks
	dw SirfetchDBitmasks
	dw MrRimeBitmasks
	dw KleavorBitmasks
	dw UrsalunaPlainBitmasks
	dw SneaslerBitmasks
	dw OverqwilBitmasks
	dw DudunsparceTwoSegmentBitmasks
	dw ClodsireBitmasks
	dw AnnihilapeBitmasks
	dw SnivyBitmasks
	dw ServineBitmasks
	dw SerperiorBitmasks
	dw TepigBitmasks
	dw PigniteBitmasks
	dw EmboarBitmasks
	dw OshawottBitmasks
	dw DewottBitmasks
	dw SamurottPlainBitmasks
	dw PatratBitmasks
	dw WatchogBitmasks
	dw LillipupBitmasks
	dw HerdierBitmasks
	dw StoutlandBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw MunnaBitmasks
	dw MusharnaBitmasks
	dw PidoveBitmasks
	dw TranquillBitmasks
	dw UnfezantMaleBitmasks
	dw BlitzleBitmasks
	dw ZebstrikaBitmasks
	dw RoggenrolaBitmasks
	dw BoldoreBitmasks
	dw GigalithBitmasks
	dw WoobatBitmasks
	dw SwoobatBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw AudinoBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw TympoleBitmasks
	dw PalpitoadBitmasks
	dw SeismitoadBitmasks
	dw ThrohBitmasks
	dw SawkBitmasks
	dw SewaddleBitmasks
	dw SwadloonBitmasks
	dw LeavannyBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw PetililBitmasks
	dw LilligantPlainBitmasks
	dw BasculinRedBitmasks ; BasculinWhiteBitmasks
	dw SandileBitmasks
	dw KrokorokBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw KrookodileBitmasks
	dw DarumakaPlainBitmasks
	dw DarmanitanPlainBitmasks
	dw MaractusBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw ScraggyBitmasks
	dw ScraftyBitmasks
	dw SigilyphBitmasks
	dw YamaskPlainBitmasks
	dw CofagrigusBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw TrubbishBitmasks
	dw GarbodorBitmasks
	dw ZoruaPlainBitmasks
	dw ZoroarkPlainBitmasks
	dw GothitaBitmasks
	dw GothoritaBitmasks
	dw GothitelleBitmasks
	dw SolosisBitmasks
	dw DuosionBitmasks
	dw ReuniclusBitmasks
	dw DucklettBitmasks
	dw SwannaBitmasks
	dw VanilliteBitmasks
	dw VanillishBitmasks
	dw VanilluxeBitmasks
	dw DeerlingSpringBitmasks
	dw SawsbuckSpringBitmasks
	dw EmolgaBitmasks
	dw KarrablastBitmasks
	dw EscavalierBitmasks
	dw FoongusBitmasks
	dw AmoongussBitmasks
	assert_table_length NUM_SPECIES

	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	dw UnownExclamationBitmasks
	dw UnownQuestionBitmasks

	dw ArbokKantoBitmasks
	dw ArbokKogaBitmasks
	dw ArbokAgathaBitmasks
	dw ArbokArianaBitmasks

	dw PikachuFlyBitmasks
	dw PikachuSurfBitmasks
	dw PikachuPikaBitmasks
	dw PikachuChuchuBitmasks
	dw PikachuSparkBitmasks

	dw PichuSpikyBitmasks

	dw MagikarpSkellyBitmasks
	dw MagikarpCalico1Bitmasks
	dw MagikarpCalico2Bitmasks
	dw MagikarpCalico3Bitmasks
	dw MagikarpTwoToneBitmasks
	dw MagikarpOrcaBitmasks
	dw MagikarpDapplesBitmasks
	dw MagikarpTigerBitmasks
	dw MagikarpZebraBitmasks
	dw MagikarpStripeBitmasks
	dw MagikarpBubblesBitmasks
	dw MagikarpDiamondsBitmasks
	dw MagikarpPatchesBitmasks
	dw MagikarpForehead1Bitmasks
	dw MagikarpMask1Bitmasks
	dw MagikarpForehead2Bitmasks
	dw MagikarpMask2Bitmasks
	dw MagikarpSaucyBitmasks
	dw MagikarpRaindropBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw GyaradosRedBitmasks

	dw MewtwoArmoredBitmasks

	dw DudunsparceThreeSegmentBitmasks

	dw RattataAlolanBitmasks
	dw RaticateAlolanBitmasks
	dw RaichuAlolanBitmasks
	dw SandshrewAlolanBitmasks
	dw SandslashAlolanBitmasks
	dw VulpixAlolanBitmasks
	dw NinetalesAlolanBitmasks
	dw DiglettAlolanBitmasks
	dw DugtrioAlolanBitmasks
	dw MeowthAlolanBitmasks
	dw PersianAlolanBitmasks
	dw GeodudeAlolanBitmasks
	dw GravelerAlolanBitmasks
	dw GolemAlolanBitmasks
	dw GrimerAlolanBitmasks
	dw MukAlolanBitmasks
	dw ExeggutorAlolanBitmasks
	dw MarowakAlolanBitmasks

	dw MeowthGalarianBitmasks
	dw PonytaGalarianBitmasks
	dw RapidashGalarianBitmasks
	dw SlowpokeGalarianBitmasks
	dw SlowbroGalarianBitmasks
	dw FarfetchDGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw MrMimeGalarianBitmasks
	dw ArticunoGalarianBitmasks
	dw ZapdosGalarianBitmasks
	dw MoltresGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw CorsolaGalarianBitmasks

	dw GrowlitheHisuianBitmasks
	dw ArcanineHisuianBitmasks
	dw VoltorbHisuianBitmasks
	dw ElectrodeHisuianBitmasks
	dw TyphlosionHisuianBitmasks
	dw QwilfishHisuianBitmasks
	dw SneaselHisuianBitmasks

	dw WooperPaldeanBitmasks
	dw TaurosPaldeanBitmasks
	dw TaurosPaldeanFireBitmasks
	dw TaurosPaldeanWaterBitmasks

	dw UrsalunaBloodmoonBitmasks
	
	dw UnfezantFemaleBitmasks

	assert_table_length NUM_UNIQUE_POKEMON
