BulbasaurBitmasks:  INCLUDE "gfx/pokemon/bulbasaur/bitmask.asm"
IvysaurBitmasks:    INCLUDE "gfx/pokemon/ivysaur/bitmask.asm"
VenusaurBitmasks:   INCLUDE "gfx/pokemon/venusaur/bitmask.asm"
CharmanderBitmasks: INCLUDE "gfx/pokemon/charmander/bitmask.asm"
CharmeleonBitmasks: INCLUDE "gfx/pokemon/charmeleon/bitmask.asm"
CharizardBitmasks:  INCLUDE "gfx/pokemon/charizard/bitmask.asm"
SquirtleBitmasks:   INCLUDE "gfx/pokemon/squirtle/bitmask.asm"
WartortleBitmasks:  INCLUDE "gfx/pokemon/wartortle/bitmask.asm"
BlastoiseBitmasks:  INCLUDE "gfx/pokemon/blastoise/bitmask.asm"
EkansBitmasks:      INCLUDE "gfx/pokemon/ekans/bitmask.asm"
NidoranFBitmasks:   INCLUDE "gfx/pokemon/nidoran_f/bitmask.asm"
NidorinaBitmasks:   INCLUDE "gfx/pokemon/nidorina/bitmask.asm"
NidoqueenBitmasks:  INCLUDE "gfx/pokemon/nidoqueen/bitmask.asm"
NidoranMBitmasks:   INCLUDE "gfx/pokemon/nidoran_m/bitmask.asm"
NidorinoBitmasks:   INCLUDE "gfx/pokemon/nidorino/bitmask.asm"
NidokingBitmasks:   INCLUDE "gfx/pokemon/nidoking/bitmask.asm"
ClefairyBitmasks:   INCLUDE "gfx/pokemon/clefairy/bitmask.asm"
ClefableBitmasks:   INCLUDE "gfx/pokemon/clefable/bitmask.asm"
JigglypuffBitmasks: INCLUDE "gfx/pokemon/jigglypuff/bitmask.asm"
WigglytuffBitmasks: INCLUDE "gfx/pokemon/wigglytuff/bitmask.asm"
ZubatBitmasks:      INCLUDE "gfx/pokemon/zubat/bitmask.asm"
GolbatBitmasks:     INCLUDE "gfx/pokemon/golbat/bitmask.asm"
ParasBitmasks:      INCLUDE "gfx/pokemon/paras/bitmask.asm"
ParasectBitmasks:   INCLUDE "gfx/pokemon/parasect/bitmask.asm"
PsyduckBitmasks:    INCLUDE "gfx/pokemon/psyduck/bitmask.asm"
GolduckBitmasks:    INCLUDE "gfx/pokemon/golduck/bitmask.asm"
MankeyBitmasks:     INCLUDE "gfx/pokemon/mankey/bitmask.asm"
PrimeapeBitmasks:   INCLUDE "gfx/pokemon/primeape/bitmask.asm"
PoliwagBitmasks:    INCLUDE "gfx/pokemon/poliwag/bitmask.asm"
PoliwhirlBitmasks:  INCLUDE "gfx/pokemon/poliwhirl/bitmask.asm"
PoliwrathBitmasks:  INCLUDE "gfx/pokemon/poliwrath/bitmask.asm"
MagnemiteBitmasks:  INCLUDE "gfx/pokemon/magnemite/bitmask.asm"
MagnetonBitmasks:   INCLUDE "gfx/pokemon/magneton/bitmask.asm"
SeelBitmasks:       INCLUDE "gfx/pokemon/seel/bitmask.asm"
DewgongBitmasks:    INCLUDE "gfx/pokemon/dewgong/bitmask.asm"
GastlyBitmasks:     INCLUDE "gfx/pokemon/gastly/bitmask.asm"
HaunterBitmasks:    INCLUDE "gfx/pokemon/haunter/bitmask.asm"
GengarBitmasks:     INCLUDE "gfx/pokemon/gengar/bitmask.asm"
OnixBitmasks:       INCLUDE "gfx/pokemon/onix/bitmask.asm"
ExeggcuteBitmasks:  INCLUDE "gfx/pokemon/exeggcute/bitmask.asm"
CuboneBitmasks:     INCLUDE "gfx/pokemon/cubone/bitmask.asm"
LickitungBitmasks:  INCLUDE "gfx/pokemon/lickitung/bitmask.asm"
KoffingBitmasks:    INCLUDE "gfx/pokemon/koffing/bitmask.asm"
TangelaBitmasks:    INCLUDE "gfx/pokemon/tangela/bitmask.asm"
KangaskhanBitmasks: INCLUDE "gfx/pokemon/kangaskhan/bitmask.asm"
HorseaBitmasks:     INCLUDE "gfx/pokemon/horsea/bitmask.asm"
SeadraBitmasks:     INCLUDE "gfx/pokemon/seadra/bitmask.asm"
StaryuBitmasks:     INCLUDE "gfx/pokemon/staryu/bitmask.asm"
StarmieBitmasks:    INCLUDE "gfx/pokemon/starmie/bitmask.asm"
ScytherBitmasks:    INCLUDE "gfx/pokemon/scyther/bitmask.asm"
ElectabuzzBitmasks: INCLUDE "gfx/pokemon/electabuzz/bitmask.asm"
MagmarBitmasks:     INCLUDE "gfx/pokemon/magmar/bitmask.asm"
PinsirBitmasks:     INCLUDE "gfx/pokemon/pinsir/bitmask.asm"
LaprasBitmasks:     INCLUDE "gfx/pokemon/lapras/bitmask.asm"
DittoBitmasks:      INCLUDE "gfx/pokemon/ditto/bitmask.asm"
EeveeBitmasks:      INCLUDE "gfx/pokemon/eevee/bitmask.asm"
VaporeonBitmasks:   INCLUDE "gfx/pokemon/vaporeon/bitmask.asm"
JolteonBitmasks:    INCLUDE "gfx/pokemon/jolteon/bitmask.asm"
FlareonBitmasks:    INCLUDE "gfx/pokemon/flareon/bitmask.asm"
KabutoBitmasks:     INCLUDE "gfx/pokemon/kabuto/bitmask.asm"
KabutopsBitmasks:   INCLUDE "gfx/pokemon/kabutops/bitmask.asm"
AerodactylBitmasks: INCLUDE "gfx/pokemon/aerodactyl/bitmask.asm"
SnorlaxBitmasks:    INCLUDE "gfx/pokemon/snorlax/bitmask.asm"
DratiniBitmasks:    INCLUDE "gfx/pokemon/dratini/bitmask.asm"
DragonairBitmasks:  INCLUDE "gfx/pokemon/dragonair/bitmask.asm"
DragoniteBitmasks:  INCLUDE "gfx/pokemon/dragonite/bitmask.asm"
MewBitmasks:        INCLUDE "gfx/pokemon/mew/bitmask.asm"
ChikoritaBitmasks:  INCLUDE "gfx/pokemon/chikorita/bitmask.asm"
BayleefBitmasks:    INCLUDE "gfx/pokemon/bayleef/bitmask.asm"
MeganiumBitmasks:   INCLUDE "gfx/pokemon/meganium/bitmask.asm"
CyndaquilBitmasks:  INCLUDE "gfx/pokemon/cyndaquil/bitmask.asm"
QuilavaBitmasks:    INCLUDE "gfx/pokemon/quilava/bitmask.asm"
TotodileBitmasks:   INCLUDE "gfx/pokemon/totodile/bitmask.asm"
CroconawBitmasks:   INCLUDE "gfx/pokemon/croconaw/bitmask.asm"
FeraligatrBitmasks: INCLUDE "gfx/pokemon/feraligatr/bitmask.asm"
SentretBitmasks:    INCLUDE "gfx/pokemon/sentret/bitmask.asm"
FurretBitmasks:     INCLUDE "gfx/pokemon/furret/bitmask.asm"
HoothootBitmasks:   INCLUDE "gfx/pokemon/hoothoot/bitmask.asm"
NoctowlBitmasks:    INCLUDE "gfx/pokemon/noctowl/bitmask.asm"
LedybaBitmasks:     INCLUDE "gfx/pokemon/ledyba/bitmask.asm"
LedianBitmasks:     INCLUDE "gfx/pokemon/ledian/bitmask.asm"
SpinarakBitmasks:   INCLUDE "gfx/pokemon/spinarak/bitmask.asm"
AriadosBitmasks:    INCLUDE "gfx/pokemon/ariados/bitmask.asm"
CrobatBitmasks:     INCLUDE "gfx/pokemon/crobat/bitmask.asm"
ChinchouBitmasks:   INCLUDE "gfx/pokemon/chinchou/bitmask.asm"
LanturnBitmasks:    INCLUDE "gfx/pokemon/lanturn/bitmask.asm"
CleffaBitmasks:     INCLUDE "gfx/pokemon/cleffa/bitmask.asm"
IgglybuffBitmasks:  INCLUDE "gfx/pokemon/igglybuff/bitmask.asm"
TogepiBitmasks:     INCLUDE "gfx/pokemon/togepi/bitmask.asm"
TogeticBitmasks:    INCLUDE "gfx/pokemon/togetic/bitmask.asm"
NatuBitmasks:       INCLUDE "gfx/pokemon/natu/bitmask.asm"
XatuBitmasks:       INCLUDE "gfx/pokemon/xatu/bitmask.asm"
MareepBitmasks:     INCLUDE "gfx/pokemon/mareep/bitmask.asm"
FlaaffyBitmasks:    INCLUDE "gfx/pokemon/flaaffy/bitmask.asm"
AmpharosBitmasks:   INCLUDE "gfx/pokemon/ampharos/bitmask.asm"
SudowoodoBitmasks:  INCLUDE "gfx/pokemon/sudowoodo/bitmask.asm"
MarillBitmasks:     INCLUDE "gfx/pokemon/marill/bitmask.asm"
AzumarillBitmasks:  INCLUDE "gfx/pokemon/azumarill/bitmask.asm"
PolitoedBitmasks:   INCLUDE "gfx/pokemon/politoed/bitmask.asm"
HoppipBitmasks:     INCLUDE "gfx/pokemon/hoppip/bitmask.asm"
SkiploomBitmasks:   INCLUDE "gfx/pokemon/skiploom/bitmask.asm"
JumpluffBitmasks:   INCLUDE "gfx/pokemon/jumpluff/bitmask.asm"
AipomBitmasks:      INCLUDE "gfx/pokemon/aipom/bitmask.asm"
SunkernBitmasks:    INCLUDE "gfx/pokemon/sunkern/bitmask.asm"
SunfloraBitmasks:   INCLUDE "gfx/pokemon/sunflora/bitmask.asm"
YanmaBitmasks:      INCLUDE "gfx/pokemon/yanma/bitmask.asm"
QuagsireBitmasks:   INCLUDE "gfx/pokemon/quagsire/bitmask.asm"
EspeonBitmasks:     INCLUDE "gfx/pokemon/espeon/bitmask.asm"
UmbreonBitmasks:    INCLUDE "gfx/pokemon/umbreon/bitmask.asm"
MurkrowBitmasks:    INCLUDE "gfx/pokemon/murkrow/bitmask.asm"
MisdreavusBitmasks: INCLUDE "gfx/pokemon/misdreavus/bitmask.asm"
WobbuffetBitmasks:  INCLUDE "gfx/pokemon/wobbuffet/bitmask.asm"
GirafarigBitmasks:  INCLUDE "gfx/pokemon/girafarig/bitmask.asm"
PinecoBitmasks:     INCLUDE "gfx/pokemon/pineco/bitmask.asm"
ForretressBitmasks: INCLUDE "gfx/pokemon/forretress/bitmask.asm"
DunsparceBitmasks:  INCLUDE "gfx/pokemon/dunsparce/bitmask.asm"
GligarBitmasks:     INCLUDE "gfx/pokemon/gligar/bitmask.asm"
SteelixBitmasks:    INCLUDE "gfx/pokemon/steelix/bitmask.asm"
SnubbullBitmasks:   INCLUDE "gfx/pokemon/snubbull/bitmask.asm"
GranbullBitmasks:   INCLUDE "gfx/pokemon/granbull/bitmask.asm"
ScizorBitmasks:     INCLUDE "gfx/pokemon/scizor/bitmask.asm"
ShuckleBitmasks:    INCLUDE "gfx/pokemon/shuckle/bitmask.asm"
HeracrossBitmasks:  INCLUDE "gfx/pokemon/heracross/bitmask.asm"
TeddiursaBitmasks:  INCLUDE "gfx/pokemon/teddiursa/bitmask.asm"
UrsaringBitmasks:   INCLUDE "gfx/pokemon/ursaring/bitmask.asm"
SlugmaBitmasks:     INCLUDE "gfx/pokemon/slugma/bitmask.asm"
MagcargoBitmasks:   INCLUDE "gfx/pokemon/magcargo/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/pokemon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/pokemon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
PhanpyBitmasks:     INCLUDE "gfx/pokemon/phanpy/bitmask.asm"
DonphanBitmasks:    INCLUDE "gfx/pokemon/donphan/bitmask.asm"
StantlerBitmasks:   INCLUDE "gfx/pokemon/stantler/bitmask.asm"
SmeargleBitmasks:   INCLUDE "gfx/pokemon/smeargle/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/pokemon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/pokemon/magby/bitmask.asm"
MiltankBitmasks:    INCLUDE "gfx/pokemon/miltank/bitmask.asm"
RaikouBitmasks:     INCLUDE "gfx/pokemon/raikou/bitmask.asm"
EnteiBitmasks:      INCLUDE "gfx/pokemon/entei/bitmask.asm"
SuicuneBitmasks:    INCLUDE "gfx/pokemon/suicune/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
LugiaBitmasks:      INCLUDE "gfx/pokemon/lugia/bitmask.asm"
HoOhBitmasks:       INCLUDE "gfx/pokemon/ho_oh/bitmask.asm"
CelebiBitmasks:     INCLUDE "gfx/pokemon/celebi/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/pokemon/azurill/bitmask.asm"
WynautBitmasks:     INCLUDE "gfx/pokemon/wynaut/bitmask.asm"
AmbipomBitmasks:    INCLUDE "gfx/pokemon/ambipom/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/pokemon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/pokemon/mime_jr_/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/pokemon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/pokemon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/pokemon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/pokemon/lickilicky/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/pokemon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
GliscorBitmasks:    INCLUDE "gfx/pokemon/gliscor/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/pokemon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/pokemon/cursola/bitmask.asm"
SirfetchDBitmasks:  INCLUDE "gfx/pokemon/sirfetch_d/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/pokemon/mr__rime/bitmask.asm"
WyrdeerBitmasks:    INCLUDE "gfx/pokemon/wyrdeer/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
OverqwilBitmasks:   INCLUDE "gfx/pokemon/overqwil/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/pokemon/farigiraf/bitmask.asm"
ClodsireBitmasks:   INCLUDE "gfx/pokemon/clodsire/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/pokemon/annihilape/bitmask.asm"
SnivyBitmasks:      INCLUDE "gfx/pokemon/snivy/bitmask.asm"
ServineBitmasks:    INCLUDE "gfx/pokemon/servine/bitmask.asm"
SerperiorBitmasks:  INCLUDE "gfx/pokemon/serperior/bitmask.asm"
TepigBitmasks:      INCLUDE "gfx/pokemon/tepig/bitmask.asm"
PigniteBitmasks:    INCLUDE "gfx/pokemon/pignite/bitmask.asm"
EmboarBitmasks:     INCLUDE "gfx/pokemon/emboar/bitmask.asm"
OshawottBitmasks:   INCLUDE "gfx/pokemon/oshawott/bitmask.asm"
DewottBitmasks:     INCLUDE "gfx/pokemon/dewott/bitmask.asm"
PatratBitmasks:     INCLUDE "gfx/pokemon/patrat/bitmask.asm"
WatchogBitmasks:    INCLUDE "gfx/pokemon/watchog/bitmask.asm"
LillipupBitmasks:   INCLUDE "gfx/pokemon/lillipup/bitmask.asm"
HerdierBitmasks:    INCLUDE "gfx/pokemon/herdier/bitmask.asm"
StoutlandBitmasks:  INCLUDE "gfx/pokemon/stoutland/bitmask.asm"
PurrloinBitmasks:   INCLUDE "gfx/pokemon/purrloin/bitmask.asm"
LiepardBitmasks:    INCLUDE "gfx/pokemon/liepard/bitmask.asm"
MunnaBitmasks:      INCLUDE "gfx/pokemon/munna/bitmask.asm"
MusharnaBitmasks:   INCLUDE "gfx/pokemon/musharna/bitmask.asm"
PidoveBitmasks:     INCLUDE "gfx/pokemon/pidove/bitmask.asm"
TranquillBitmasks:  INCLUDE "gfx/pokemon/tranquill/bitmask.asm"
UnfezantBitmasks:   INCLUDE "gfx/pokemon/unfezant/bitmask.asm"
BlitzleBitmasks:    INCLUDE "gfx/pokemon/blitzle/bitmask.asm"
ZebstrikaBitmasks:  INCLUDE "gfx/pokemon/zebstrika/bitmask.asm"
RoggenrolaBitmasks: INCLUDE "gfx/pokemon/roggenrola/bitmask.asm"
BoldoreBitmasks:    INCLUDE "gfx/pokemon/boldore/bitmask.asm"
GigalithBitmasks:   INCLUDE "gfx/pokemon/gigalith/bitmask.asm"
WoobatBitmasks:     INCLUDE "gfx/pokemon/woobat/bitmask.asm"
SwoobatBitmasks:    INCLUDE "gfx/pokemon/swoobat/bitmask.asm"
DrilburBitmasks:    INCLUDE "gfx/pokemon/drilbur/bitmask.asm"
ExcadrillBitmasks:  INCLUDE "gfx/pokemon/excadrill/bitmask.asm"
AudinoBitmasks:     INCLUDE "gfx/pokemon/audino/bitmask.asm"
TimburrBitmasks:    INCLUDE "gfx/pokemon/timburr/bitmask.asm"
GurdurrBitmasks:    INCLUDE "gfx/pokemon/gurdurr/bitmask.asm"
ConkeldurrBitmasks: INCLUDE "gfx/pokemon/conkeldurr/bitmask.asm"
TympoleBitmasks:    INCLUDE "gfx/pokemon/tympole/bitmask.asm"
PalpitoadBitmasks:  INCLUDE "gfx/pokemon/palpitoad/bitmask.asm"
SeismitoadBitmasks: INCLUDE "gfx/pokemon/seismitoad/bitmask.asm"
ThrohBitmasks:      INCLUDE "gfx/pokemon/throh/bitmask.asm"
SawkBitmasks:       INCLUDE "gfx/pokemon/sawk/bitmask.asm"
SewaddleBitmasks:   INCLUDE "gfx/pokemon/sewaddle/bitmask.asm"
SwadloonBitmasks:   INCLUDE "gfx/pokemon/swadloon/bitmask.asm"
LeavannyBitmasks:   INCLUDE "gfx/pokemon/leavanny/bitmask.asm"
VenipedeBitmasks:   INCLUDE "gfx/pokemon/venipede/bitmask.asm"
WhirlipedeBitmasks: INCLUDE "gfx/pokemon/whirlipede/bitmask.asm"
ScolipedeBitmasks:  INCLUDE "gfx/pokemon/scolipede/bitmask.asm"
CottoneeBitmasks:   INCLUDE "gfx/pokemon/cottonee/bitmask.asm"
WhimsicottBitmasks: INCLUDE "gfx/pokemon/whimsicott/bitmask.asm"
PetililBitmasks:    INCLUDE "gfx/pokemon/petilil/bitmask.asm"
SandileBitmasks:    INCLUDE "gfx/pokemon/sandile/bitmask.asm"
KrokorokBitmasks:   INCLUDE "gfx/pokemon/krokorok/bitmask.asm"
KrookodileBitmasks: INCLUDE "gfx/pokemon/krookodile/bitmask.asm"
MaractusBitmasks:   INCLUDE "gfx/pokemon/maractus/bitmask.asm"
DwebbleBitmasks:    INCLUDE "gfx/pokemon/dwebble/bitmask.asm"
CrustleBitmasks:    INCLUDE "gfx/pokemon/crustle/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.asm"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.asm"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.asm"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.asm"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.asm"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.asm"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.asm"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.asm"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.asm"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.asm"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.asm"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.asm"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.asm"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.asm"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.asm"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.asm"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.asm"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.asm"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.asm"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.asm"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.asm"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.asm"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.asm"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.asm"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.asm"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.asm"
UnownExclamationBitmasks: INCLUDE "gfx/pokemon/unown_exclamation/bitmask.asm"
UnownQuestionBitmasks:    INCLUDE "gfx/pokemon/unown_question/bitmask.asm"

PichuPlainBitmasks: INCLUDE "gfx/pokemon/pichu_plain/bitmask.asm"
PichuSpikyBitmasks: INCLUDE "gfx/pokemon/pichu_spiky/bitmask.asm"

PikachuPlainBitmasks:  INCLUDE "gfx/pokemon/pikachu_plain/bitmask.asm"
PikachuFlyBitmasks:    INCLUDE "gfx/pokemon/pikachu_fly/bitmask.asm"
PikachuSurfBitmasks:   INCLUDE "gfx/pokemon/pikachu_surf/bitmask.asm"
PikachuPikaBitmasks:   INCLUDE "gfx/pokemon/pikachu_pika/bitmask.asm"
PikachuChuchuBitmasks: INCLUDE "gfx/pokemon/pikachu_chuchu/bitmask.asm"
PikachuSparkBitmasks:  INCLUDE "gfx/pokemon/pikachu_spark/bitmask.asm"

ArbokJohtoBitmasks:  INCLUDE "gfx/pokemon/arbok_johto/bitmask.asm"
ArbokKantoBitmasks:  INCLUDE "gfx/pokemon/arbok_kanto/bitmask.asm"
ArbokKogaBitmasks:   INCLUDE "gfx/pokemon/arbok_koga/bitmask.asm"
ArbokAgathaBitmasks: INCLUDE "gfx/pokemon/arbok_agatha/bitmask.asm"
ArbokArianaBitmasks: INCLUDE "gfx/pokemon/arbok_ariana/bitmask.asm"

MagikarpPlainBitmasks:     INCLUDE "gfx/pokemon/magikarp_plain/bitmask.asm"
MagikarpSkellyBitmasks:    INCLUDE "gfx/pokemon/magikarp_skelly/bitmask.asm"
MagikarpCalico1Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico1/bitmask.asm"
MagikarpCalico2Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico2/bitmask.asm"
MagikarpCalico3Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico3/bitmask.asm"
MagikarpTwoToneBitmasks:   INCLUDE "gfx/pokemon/magikarp_twotone/bitmask.asm"
MagikarpOrcaBitmasks:      INCLUDE "gfx/pokemon/magikarp_orca/bitmask.asm"
MagikarpDapplesBitmasks:   INCLUDE "gfx/pokemon/magikarp_dapples/bitmask.asm"
MagikarpTigerBitmasks:     INCLUDE "gfx/pokemon/magikarp_tiger/bitmask.asm"
MagikarpZebraBitmasks:     INCLUDE "gfx/pokemon/magikarp_zebra/bitmask.asm"
MagikarpStripeBitmasks:    INCLUDE "gfx/pokemon/magikarp_stripe/bitmask.asm"
MagikarpBubblesBitmasks:   INCLUDE "gfx/pokemon/magikarp_bubbles/bitmask.asm"
MagikarpDiamondsBitmasks:  INCLUDE "gfx/pokemon/magikarp_diamonds/bitmask.asm"
MagikarpPatchesBitmasks:   INCLUDE "gfx/pokemon/magikarp_patches/bitmask.asm"
MagikarpForehead1Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead1/bitmask.asm"
MagikarpMask1Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask1/bitmask.asm"
MagikarpForehead2Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead2/bitmask.asm"
MagikarpMask2Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask2/bitmask.asm"
MagikarpSaucyBitmasks:     INCLUDE "gfx/pokemon/magikarp_saucy/bitmask.asm"
MagikarpRaindropBitmasks:  INCLUDE "gfx/pokemon/magikarp_raindrop/bitmask.asm"

DudunsparceTwoSegmentBitmasks:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/bitmask.asm"
DudunsparceThreeSegmentBitmasks: INCLUDE "gfx/pokemon/dudunsparce_three_segment/bitmask.asm"

GyaradosPlainBitmasks: INCLUDE "gfx/pokemon/gyarados_plain/bitmask.asm"
GyaradosRedBitmasks:   INCLUDE "gfx/pokemon/gyarados_red/bitmask.asm"

MewtwoPlainBitmasks:   INCLUDE "gfx/pokemon/mewtwo_plain/bitmask.asm"
MewtwoArmoredBitmasks: INCLUDE "gfx/pokemon/mewtwo_armored/bitmask.asm"

RattataPlainBitmasks:  INCLUDE "gfx/pokemon/rattata_plain/bitmask.asm"
RattataAlolanBitmasks: INCLUDE "gfx/pokemon/rattata_alolan/bitmask.asm"

RaticatePlainBitmasks:  INCLUDE "gfx/pokemon/raticate_plain/bitmask.asm"
RaticateAlolanBitmasks: INCLUDE "gfx/pokemon/raticate_alolan/bitmask.asm"

RaichuPlainBitmasks:  INCLUDE "gfx/pokemon/raichu_plain/bitmask.asm"
RaichuAlolanBitmasks: INCLUDE "gfx/pokemon/raichu_alolan/bitmask.asm"

SandshrewPlainBitmasks:  INCLUDE "gfx/pokemon/sandshrew_plain/bitmask.asm"
SandshrewAlolanBitmasks: INCLUDE "gfx/pokemon/sandshrew_alolan/bitmask.asm"

SandslashPlainBitmasks:  INCLUDE "gfx/pokemon/sandslash_plain/bitmask.asm"
SandslashAlolanBitmasks: INCLUDE "gfx/pokemon/sandslash_alolan/bitmask.asm"

VulpixPlainBitmasks:  INCLUDE "gfx/pokemon/vulpix_plain/bitmask.asm"
VulpixAlolanBitmasks: INCLUDE "gfx/pokemon/vulpix_alolan/bitmask.asm"

NinetalesPlainBitmasks:  INCLUDE "gfx/pokemon/ninetales_plain/bitmask.asm"
NinetalesAlolanBitmasks: INCLUDE "gfx/pokemon/ninetales_alolan/bitmask.asm"

DiglettPlainBitmasks:  INCLUDE "gfx/pokemon/diglett_plain/bitmask.asm"
DiglettAlolanBitmasks: INCLUDE "gfx/pokemon/diglett_alolan/bitmask.asm"

DugtrioPlainBitmasks:  INCLUDE "gfx/pokemon/dugtrio_plain/bitmask.asm"
DugtrioAlolanBitmasks: INCLUDE "gfx/pokemon/dugtrio_alolan/bitmask.asm"

MeowthPlainBitmasks:    INCLUDE "gfx/pokemon/meowth_plain/bitmask.asm"
MeowthAlolanBitmasks:   INCLUDE "gfx/pokemon/meowth_alolan/bitmask.asm"
MeowthGalarianBitmasks: INCLUDE "gfx/pokemon/meowth_galarian/bitmask.asm"

PersianPlainBitmasks:  INCLUDE "gfx/pokemon/persian_plain/bitmask.asm"
PersianAlolanBitmasks: INCLUDE "gfx/pokemon/persian_alolan/bitmask.asm"

GeodudePlainBitmasks:  INCLUDE "gfx/pokemon/geodude_plain/bitmask.asm"
GeodudeAlolanBitmasks: INCLUDE "gfx/pokemon/geodude_alolan/bitmask.asm"

GravelerPlainBitmasks:  INCLUDE "gfx/pokemon/graveler_plain/bitmask.asm"
GravelerAlolanBitmasks: INCLUDE "gfx/pokemon/graveler_alolan/bitmask.asm"

GolemPlainBitmasks:  INCLUDE "gfx/pokemon/golem_plain/bitmask.asm"
GolemAlolanBitmasks: INCLUDE "gfx/pokemon/golem_alolan/bitmask.asm"

GrimerPlainBitmasks:  INCLUDE "gfx/pokemon/grimer_plain/bitmask.asm"
GrimerAlolanBitmasks: INCLUDE "gfx/pokemon/grimer_alolan/bitmask.asm"

MukPlainBitmasks:  INCLUDE "gfx/pokemon/muk_plain/bitmask.asm"
MukAlolanBitmasks: INCLUDE "gfx/pokemon/muk_alolan/bitmask.asm"

ExeggutorPlainBitmasks:  INCLUDE "gfx/pokemon/exeggutor_plain/bitmask.asm"
ExeggutorAlolanBitmasks: INCLUDE "gfx/pokemon/exeggutor_alolan/bitmask.asm"

MarowakPlainBitmasks:  INCLUDE "gfx/pokemon/marowak_plain/bitmask.asm"
MarowakAlolanBitmasks: INCLUDE "gfx/pokemon/marowak_alolan/bitmask.asm"

PonytaPlainBitmasks:    INCLUDE "gfx/pokemon/ponyta_plain/bitmask.asm"
PonytaGalarianBitmasks: INCLUDE "gfx/pokemon/ponyta_galarian/bitmask.asm"

RapidashPlainBitmasks:    INCLUDE "gfx/pokemon/rapidash_plain/bitmask.asm"
RapidashGalarianBitmasks: INCLUDE "gfx/pokemon/rapidash_galarian/bitmask.asm"

SlowpokePlainBitmasks:   INCLUDE "gfx/pokemon/slowpoke_plain/bitmask.asm"
SlowpokeGalarianBitmasks: INCLUDE "gfx/pokemon/slowpoke_galarian/bitmask.asm"

SlowbroPlainBitmasks:    INCLUDE "gfx/pokemon/slowbro_plain/bitmask.asm"
SlowbroGalarianBitmasks: INCLUDE "gfx/pokemon/slowbro_galarian/bitmask.asm"

FarfetchDPlainBitmasks:     INCLUDE "gfx/pokemon/farfetch_d_plain/bitmask.asm"
FarfetchDGalarianBitmasks:  INCLUDE "gfx/pokemon/farfetch_d_galarian/bitmask.asm"

WeezingPlainBitmasks:    INCLUDE "gfx/pokemon/weezing_plain/bitmask.asm"
WeezingGalarianBitmasks: INCLUDE "gfx/pokemon/weezing_galarian/bitmask.asm"

MrMimePlainBitmasks:    INCLUDE "gfx/pokemon/mr__mime_plain/bitmask.asm"
MrMimeGalarianBitmasks: INCLUDE "gfx/pokemon/mr__mime_galarian/bitmask.asm"

ArticunoPlainBitmasks:    INCLUDE "gfx/pokemon/articuno_plain/bitmask.asm"
ArticunoGalarianBitmasks: INCLUDE "gfx/pokemon/articuno_galarian/bitmask.asm"

ZapdosPlainBitmasks:    INCLUDE "gfx/pokemon/zapdos_plain/bitmask.asm"
ZapdosGalarianBitmasks: INCLUDE "gfx/pokemon/zapdos_galarian/bitmask.asm"

MoltresPlainBitmasks:    INCLUDE "gfx/pokemon/moltres_plain/bitmask.asm"
MoltresGalarianBitmasks: INCLUDE "gfx/pokemon/moltres_galarian/bitmask.asm"

SlowkingPlainBitmasks:    INCLUDE "gfx/pokemon/slowking_plain/bitmask.asm"
SlowkingGalarianBitmasks: INCLUDE "gfx/pokemon/slowking_galarian/bitmask.asm"

CorsolaPlainBitmasks:    INCLUDE "gfx/pokemon/corsola_plain/bitmask.asm"
CorsolaGalarianBitmasks: INCLUDE "gfx/pokemon/corsola_galarian/bitmask.asm"

GrowlithePlainBitmasks:   INCLUDE "gfx/pokemon/growlithe_plain/bitmask.asm"
GrowlitheHisuianBitmasks: INCLUDE "gfx/pokemon/growlithe_hisuian/bitmask.asm"

ArcaninePlainBitmasks:   INCLUDE "gfx/pokemon/arcanine_plain/bitmask.asm"
ArcanineHisuianBitmasks: INCLUDE "gfx/pokemon/arcanine_hisuian/bitmask.asm"

VoltorbPlainBitmasks:   INCLUDE "gfx/pokemon/voltorb_plain/bitmask.asm"
VoltorbHisuianBitmasks: INCLUDE "gfx/pokemon/voltorb_hisuian/bitmask.asm"

ElectrodePlainBitmasks:   INCLUDE "gfx/pokemon/electrode_plain/bitmask.asm"
ElectrodeHisuianBitmasks: INCLUDE "gfx/pokemon/electrode_hisuian/bitmask.asm"

TyphlosionPlainBitmasks:   INCLUDE "gfx/pokemon/typhlosion_plain/bitmask.asm"
TyphlosionHisuianBitmasks: INCLUDE "gfx/pokemon/typhlosion_hisuian/bitmask.asm"

QwilfishPlainBitmasks:   INCLUDE "gfx/pokemon/qwilfish_plain/bitmask.asm"
QwilfishHisuianBitmasks: INCLUDE "gfx/pokemon/qwilfish_hisuian/bitmask.asm"

SneaselPlainBitmasks:   INCLUDE "gfx/pokemon/sneasel_plain/bitmask.asm"
SneaselHisuianBitmasks: INCLUDE "gfx/pokemon/sneasel_hisuian/bitmask.asm"

WooperPlainBitmasks:    INCLUDE "gfx/pokemon/wooper_plain/bitmask.asm"
WooperPaldeanBitmasks:  INCLUDE "gfx/pokemon/wooper_paldean/bitmask.asm"

TaurosPlainBitmasks:        INCLUDE "gfx/pokemon/tauros_plain/bitmask.asm"
TaurosPaldeanBitmasks:      INCLUDE "gfx/pokemon/tauros_paldean/bitmask.asm"
TaurosPaldeanFireBitmasks:  INCLUDE "gfx/pokemon/tauros_paldean_fire/bitmask.asm"
TaurosPaldeanWaterBitmasks: INCLUDE "gfx/pokemon/tauros_paldean_water/bitmask.asm"

UrsalunaPlainBitmasks:     INCLUDE "gfx/pokemon/ursaluna_plain/bitmask.asm"
UrsalunaBloodmoonBitmasks: INCLUDE "gfx/pokemon/ursaluna_bloodmoon/bitmask.asm"

SamurottPlainBitmasks: INCLUDE "gfx/pokemon/samurott_plain/bitmask.asm"

LilligantPlainBitmasks: INCLUDE "gfx/pokemon/lilligant_plain/bitmask.asm"

BasculinRedBitmasks: INCLUDE "gfx/pokemon/basculin_red/bitmask.asm"

DarumakaPlainBitmasks: INCLUDE "gfx/pokemon/darumaka_plain/bitmask.asm"

DarmanitanPlainBitmasks: INCLUDE "gfx/pokemon/darmanitan_plain/bitmask.asm"
