NidoranFBitmasks:   INCLUDE "gfx/pokemon/nidoran_f/bitmask.asm"
NidorinaBitmasks:   INCLUDE "gfx/pokemon/nidorina/bitmask.asm"
NidoqueenBitmasks:  INCLUDE "gfx/pokemon/nidoqueen/bitmask.asm"
NidoranMBitmasks:   INCLUDE "gfx/pokemon/nidoran_m/bitmask.asm"
NidorinoBitmasks:   INCLUDE "gfx/pokemon/nidorino/bitmask.asm"
NidokingBitmasks:   INCLUDE "gfx/pokemon/nidoking/bitmask.asm"
ClefairyBitmasks:   INCLUDE "gfx/pokemon/clefairy/bitmask.asm"
ClefableBitmasks:   INCLUDE "gfx/pokemon/clefable/bitmask.asm"
JigglypuffBitmasks: INCLUDE "gfx/pokemon/jigglypuff/bitmask.asm"
WigglytuffBitmasks: INCLUDE "gfx/pokemon/wigglytuff/bitmask.asm"
ZubatBitmasks:      INCLUDE "gfx/pokemon/zubat/bitmask.asm"
GolbatBitmasks:     INCLUDE "gfx/pokemon/golbat/bitmask.asm"
ParasBitmasks:      INCLUDE "gfx/pokemon/paras/bitmask.asm"
ParasectBitmasks:   INCLUDE "gfx/pokemon/parasect/bitmask.asm"
PsyduckBitmasks:    INCLUDE "gfx/pokemon/psyduck/bitmask.asm"
GolduckBitmasks:    INCLUDE "gfx/pokemon/golduck/bitmask.asm"
MankeyBitmasks:     INCLUDE "gfx/pokemon/mankey/bitmask.asm"
PrimeapeBitmasks:   INCLUDE "gfx/pokemon/primeape/bitmask.asm"
PoliwagBitmasks:    INCLUDE "gfx/pokemon/poliwag/bitmask.asm"
PoliwhirlBitmasks:  INCLUDE "gfx/pokemon/poliwhirl/bitmask.asm"
PoliwrathBitmasks:  INCLUDE "gfx/pokemon/poliwrath/bitmask.asm"
MagnemiteBitmasks:  INCLUDE "gfx/pokemon/magnemite/bitmask.asm"
MagnetonBitmasks:   INCLUDE "gfx/pokemon/magneton/bitmask.asm"
SeelBitmasks:       INCLUDE "gfx/pokemon/seel/bitmask.asm"
DewgongBitmasks:    INCLUDE "gfx/pokemon/dewgong/bitmask.asm"
GastlyBitmasks:     INCLUDE "gfx/pokemon/gastly/bitmask.asm"
HaunterBitmasks:    INCLUDE "gfx/pokemon/haunter/bitmask.asm"
GengarBitmasks:     INCLUDE "gfx/pokemon/gengar/bitmask.asm"
OnixBitmasks:       INCLUDE "gfx/pokemon/onix/bitmask.asm"
ExeggcuteBitmasks:  INCLUDE "gfx/pokemon/exeggcute/bitmask.asm"
LickitungBitmasks:  INCLUDE "gfx/pokemon/lickitung/bitmask.asm"
KoffingBitmasks:    INCLUDE "gfx/pokemon/koffing/bitmask.asm"
TangelaBitmasks:    INCLUDE "gfx/pokemon/tangela/bitmask.asm"
KangaskhanBitmasks: INCLUDE "gfx/pokemon/kangaskhan/bitmask.asm"
HorseaBitmasks:     INCLUDE "gfx/pokemon/horsea/bitmask.asm"
SeadraBitmasks:     INCLUDE "gfx/pokemon/seadra/bitmask.asm"
StaryuBitmasks:     INCLUDE "gfx/pokemon/staryu/bitmask.asm"
StarmieBitmasks:    INCLUDE "gfx/pokemon/starmie/bitmask.asm"
ScytherBitmasks:    INCLUDE "gfx/pokemon/scyther/bitmask.asm"
ElectabuzzBitmasks: INCLUDE "gfx/pokemon/electabuzz/bitmask.asm"
MagmarBitmasks:     INCLUDE "gfx/pokemon/magmar/bitmask.asm"
PinsirBitmasks:     INCLUDE "gfx/pokemon/pinsir/bitmask.asm"
LaprasBitmasks:     INCLUDE "gfx/pokemon/lapras/bitmask.asm"
DittoBitmasks:      INCLUDE "gfx/pokemon/ditto/bitmask.asm"
EeveeBitmasks:      INCLUDE "gfx/pokemon/eevee/bitmask.asm"
VaporeonBitmasks:   INCLUDE "gfx/pokemon/vaporeon/bitmask.asm"
JolteonBitmasks:    INCLUDE "gfx/pokemon/jolteon/bitmask.asm"
FlareonBitmasks:    INCLUDE "gfx/pokemon/flareon/bitmask.asm"
SnorlaxBitmasks:    INCLUDE "gfx/pokemon/snorlax/bitmask.asm"
DratiniBitmasks:    INCLUDE "gfx/pokemon/dratini/bitmask.asm"
DragonairBitmasks:  INCLUDE "gfx/pokemon/dragonair/bitmask.asm"
DragoniteBitmasks:  INCLUDE "gfx/pokemon/dragonite/bitmask.asm"
CrobatBitmasks:     INCLUDE "gfx/pokemon/crobat/bitmask.asm"
ChinchouBitmasks:   INCLUDE "gfx/pokemon/chinchou/bitmask.asm"
LanturnBitmasks:    INCLUDE "gfx/pokemon/lanturn/bitmask.asm"
CleffaBitmasks:     INCLUDE "gfx/pokemon/cleffa/bitmask.asm"
IgglybuffBitmasks:  INCLUDE "gfx/pokemon/igglybuff/bitmask.asm"
TogepiBitmasks:     INCLUDE "gfx/pokemon/togepi/bitmask.asm"
TogeticBitmasks:    INCLUDE "gfx/pokemon/togetic/bitmask.asm"
MareepBitmasks:     INCLUDE "gfx/pokemon/mareep/bitmask.asm"
FlaaffyBitmasks:    INCLUDE "gfx/pokemon/flaaffy/bitmask.asm"
AmpharosBitmasks:   INCLUDE "gfx/pokemon/ampharos/bitmask.asm"
SudowoodoBitmasks:  INCLUDE "gfx/pokemon/sudowoodo/bitmask.asm"
MarillBitmasks:     INCLUDE "gfx/pokemon/marill/bitmask.asm"
AzumarillBitmasks:  INCLUDE "gfx/pokemon/azumarill/bitmask.asm"
PolitoedBitmasks:   INCLUDE "gfx/pokemon/politoed/bitmask.asm"
SunkernBitmasks:    INCLUDE "gfx/pokemon/sunkern/bitmask.asm"
SunfloraBitmasks:   INCLUDE "gfx/pokemon/sunflora/bitmask.asm"
YanmaBitmasks:      INCLUDE "gfx/pokemon/yanma/bitmask.asm"
EspeonBitmasks:     INCLUDE "gfx/pokemon/espeon/bitmask.asm"
UmbreonBitmasks:    INCLUDE "gfx/pokemon/umbreon/bitmask.asm"
MurkrowBitmasks:    INCLUDE "gfx/pokemon/murkrow/bitmask.asm"
MisdreavusBitmasks: INCLUDE "gfx/pokemon/misdreavus/bitmask.asm"
DunsparceBitmasks:  INCLUDE "gfx/pokemon/dunsparce/bitmask.asm"
GligarBitmasks:     INCLUDE "gfx/pokemon/gligar/bitmask.asm"
SteelixBitmasks:    INCLUDE "gfx/pokemon/steelix/bitmask.asm"
SnubbullBitmasks:   INCLUDE "gfx/pokemon/snubbull/bitmask.asm"
GranbullBitmasks:   INCLUDE "gfx/pokemon/granbull/bitmask.asm"
ScizorBitmasks:     INCLUDE "gfx/pokemon/scizor/bitmask.asm"
ShuckleBitmasks:    INCLUDE "gfx/pokemon/shuckle/bitmask.asm"
HeracrossBitmasks:  INCLUDE "gfx/pokemon/heracross/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/pokemon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/pokemon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/pokemon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/pokemon/magby/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
LotadBitmasks:      INCLUDE "gfx/pokemon/lotad/bitmask.asm"
LombreBitmasks:     INCLUDE "gfx/pokemon/lombre/bitmask.asm"
LudicoloBitmasks:   INCLUDE "gfx/pokemon/ludicolo/bitmask.asm"
SeedotBitmasks:     INCLUDE "gfx/pokemon/seedot/bitmask.asm"
NuzleafBitmasks:    INCLUDE "gfx/pokemon/nuzleaf/bitmask.asm"
ShiftryBitmasks:    INCLUDE "gfx/pokemon/shiftry/bitmask.asm"
WingullBitmasks:    INCLUDE "gfx/pokemon/wingull/bitmask.asm"
PelipperBitmasks:   INCLUDE "gfx/pokemon/pelipper/bitmask.asm"
RaltsBitmasks:      INCLUDE "gfx/pokemon/ralts/bitmask.asm"
KirliaBitmasks:     INCLUDE "gfx/pokemon/kirlia/bitmask.asm"
GardevoirBitmasks:  INCLUDE "gfx/pokemon/gardevoir/bitmask.asm"
ShroomishBitmasks:  INCLUDE "gfx/pokemon/shroomish/bitmask.asm"
BreloomBitmasks:    INCLUDE "gfx/pokemon/breloom/bitmask.asm"
SlakothBitmasks:    INCLUDE "gfx/pokemon/slakoth/bitmask.asm"
VigorothBitmasks:   INCLUDE "gfx/pokemon/vigoroth/bitmask.asm"
SlakingBitmasks:    INCLUDE "gfx/pokemon/slaking/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/pokemon/azurill/bitmask.asm"
NosepassBitmasks:   INCLUDE "gfx/pokemon/nosepass/bitmask.asm"
SkittyBitmasks:     INCLUDE "gfx/pokemon/skitty/bitmask.asm"
DelcattyBitmasks:   INCLUDE "gfx/pokemon/delcatty/bitmask.asm"
SableyeBitmasks:    INCLUDE "gfx/pokemon/sableye/bitmask.asm"
MawileBitmasks:     INCLUDE "gfx/pokemon/mawile/bitmask.asm"
AronBitmasks:       INCLUDE "gfx/pokemon/aron/bitmask.asm"
LaironBitmasks:     INCLUDE "gfx/pokemon/lairon/bitmask.asm"
AggronBitmasks:     INCLUDE "gfx/pokemon/aggron/bitmask.asm"
MedititeBitmasks:   INCLUDE "gfx/pokemon/meditite/bitmask.asm"
MedichamBitmasks:   INCLUDE "gfx/pokemon/medicham/bitmask.asm"
RoseliaBitmasks:    INCLUDE "gfx/pokemon/roselia/bitmask.asm"
WailmerBitmasks:    INCLUDE "gfx/pokemon/wailmer/bitmask.asm"
WailordBitmasks:    INCLUDE "gfx/pokemon/wailord/bitmask.asm"
NumelBitmasks:      INCLUDE "gfx/pokemon/numel/bitmask.asm"
CameruptBitmasks:   INCLUDE "gfx/pokemon/camerupt/bitmask.asm"
TorkoalBitmasks:    INCLUDE "gfx/pokemon/torkoal/bitmask.asm"
SpoinkBitmasks:     INCLUDE "gfx/pokemon/spoink/bitmask.asm"
GrumpigBitmasks:    INCLUDE "gfx/pokemon/grumpig/bitmask.asm"
TrapinchBitmasks:   INCLUDE "gfx/pokemon/trapinch/bitmask.asm"
VibravaBitmasks:    INCLUDE "gfx/pokemon/vibrava/bitmask.asm"
FlygonBitmasks:     INCLUDE "gfx/pokemon/flygon/bitmask.asm"
SwabluBitmasks:     INCLUDE "gfx/pokemon/swablu/bitmask.asm"
AltariaBitmasks:    INCLUDE "gfx/pokemon/altaria/bitmask.asm"
ZangooseBitmasks:   INCLUDE "gfx/pokemon/zangoose/bitmask.asm"
SeviperBitmasks:    INCLUDE "gfx/pokemon/seviper/bitmask.asm"
LunatoneBitmasks:   INCLUDE "gfx/pokemon/lunatone/bitmask.asm"
SolrockBitmasks:    INCLUDE "gfx/pokemon/solrock/bitmask.asm"
CorphishBitmasks:   INCLUDE "gfx/pokemon/corphish/bitmask.asm"
CrawdauntBitmasks:  INCLUDE "gfx/pokemon/crawdaunt/bitmask.asm"
BaltoyBitmasks:     INCLUDE "gfx/pokemon/baltoy/bitmask.asm"
ClaydolBitmasks:    INCLUDE "gfx/pokemon/claydol/bitmask.asm"
ShuppetBitmasks:    INCLUDE "gfx/pokemon/shuppet/bitmask.asm"
BanetteBitmasks:    INCLUDE "gfx/pokemon/banette/bitmask.asm"
TropiusBitmasks:    INCLUDE "gfx/pokemon/tropius/bitmask.asm"
AbsolBitmasks:      INCLUDE "gfx/pokemon/absol/bitmask.asm"
SnoruntBitmasks:    INCLUDE "gfx/pokemon/snorunt/bitmask.asm"
GlalieBitmasks:     INCLUDE "gfx/pokemon/glalie/bitmask.asm"
SphealBitmasks:     INCLUDE "gfx/pokemon/spheal/bitmask.asm"
SealeoBitmasks:     INCLUDE "gfx/pokemon/sealeo/bitmask.asm"
WalreinBitmasks:    INCLUDE "gfx/pokemon/walrein/bitmask.asm"
BagonBitmasks:      INCLUDE "gfx/pokemon/bagon/bitmask.asm"
ShelgonBitmasks:    INCLUDE "gfx/pokemon/shelgon/bitmask.asm"
SalamenceBitmasks:  INCLUDE "gfx/pokemon/salamence/bitmask.asm"
BeldumBitmasks:     INCLUDE "gfx/pokemon/beldum/bitmask.asm"
MetangBitmasks:     INCLUDE "gfx/pokemon/metang/bitmask.asm"
MetagrossBitmasks:  INCLUDE "gfx/pokemon/metagross/bitmask.asm"
StarlyBitmasks:     INCLUDE "gfx/pokemon/starly/bitmask.asm"
StaraviaBitmasks:   INCLUDE "gfx/pokemon/staravia/bitmask.asm"
StaraptorBitmasks:  INCLUDE "gfx/pokemon/staraptor/bitmask.asm"
ShinxBitmasks:      INCLUDE "gfx/pokemon/shinx/bitmask.asm"
LuxioBitmasks:      INCLUDE "gfx/pokemon/luxio/bitmask.asm"
LuxrayBitmasks:     INCLUDE "gfx/pokemon/luxray/bitmask.asm"
BudewBitmasks:      INCLUDE "gfx/pokemon/budew/bitmask.asm"
RoseradeBitmasks:   INCLUDE "gfx/pokemon/roserade/bitmask.asm"
VespiquenBitmasks:  INCLUDE "gfx/pokemon/vespiquen/bitmask.asm"
BuizelBitmasks:     INCLUDE "gfx/pokemon/buizel/bitmask.asm"
FloatzelBitmasks:   INCLUDE "gfx/pokemon/floatzel/bitmask.asm"
DrifloonBitmasks:   INCLUDE "gfx/pokemon/drifloon/bitmask.asm"
DrifblimBitmasks:   INCLUDE "gfx/pokemon/drifblim/bitmask.asm"
BunearyBitmasks:    INCLUDE "gfx/pokemon/buneary/bitmask.asm"
LopunnyBitmasks:    INCLUDE "gfx/pokemon/lopunny/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
BronzorBitmasks:    INCLUDE "gfx/pokemon/bronzor/bitmask.asm"
BronzongBitmasks:   INCLUDE "gfx/pokemon/bronzong/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/pokemon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/pokemon/mime_jr_/bitmask.asm"
SpiritombBitmasks:  INCLUDE "gfx/pokemon/spiritomb/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/pokemon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/pokemon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/pokemon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/pokemon/lickilicky/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/pokemon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
GliscorBitmasks:    INCLUDE "gfx/pokemon/gliscor/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/pokemon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/pokemon/cursola/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/pokemon/mr__rime/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/pokemon/annihilape/bitmask.asm"
VictiniBitmasks:    INCLUDE "gfx/pokemon/victini/bitmask.asm"
SnivyBitmasks:      INCLUDE "gfx/pokemon/snivy/bitmask.asm"
ServineBitmasks:    INCLUDE "gfx/pokemon/servine/bitmask.asm"
SerperiorBitmasks:  INCLUDE "gfx/pokemon/serperior/bitmask.asm"
TepigBitmasks:      INCLUDE "gfx/pokemon/tepig/bitmask.asm"
PigniteBitmasks:    INCLUDE "gfx/pokemon/pignite/bitmask.asm"
EmboarBitmasks:     INCLUDE "gfx/pokemon/emboar/bitmask.asm"
OshawottBitmasks:   INCLUDE "gfx/pokemon/oshawott/bitmask.asm"
DewottBitmasks:     INCLUDE "gfx/pokemon/dewott/bitmask.asm"
PatratBitmasks:     INCLUDE "gfx/pokemon/patrat/bitmask.asm"
WatchogBitmasks:    INCLUDE "gfx/pokemon/watchog/bitmask.asm"
LillipupBitmasks:   INCLUDE "gfx/pokemon/lillipup/bitmask.asm"
HerdierBitmasks:    INCLUDE "gfx/pokemon/herdier/bitmask.asm"
StoutlandBitmasks:  INCLUDE "gfx/pokemon/stoutland/bitmask.asm"
PurrloinBitmasks:   INCLUDE "gfx/pokemon/purrloin/bitmask.asm"
LiepardBitmasks:    INCLUDE "gfx/pokemon/liepard/bitmask.asm"
PansageBitmasks:    INCLUDE "gfx/pokemon/pansage/bitmask.asm"
SimisageBitmasks:   INCLUDE "gfx/pokemon/simisage/bitmask.asm"
PansearBitmasks:    INCLUDE "gfx/pokemon/pansear/bitmask.asm"
SimisearBitmasks:   INCLUDE "gfx/pokemon/simisear/bitmask.asm"
PanpourBitmasks:    INCLUDE "gfx/pokemon/panpour/bitmask.asm"
SimipourBitmasks:   INCLUDE "gfx/pokemon/simipour/bitmask.asm"
MunnaBitmasks:      INCLUDE "gfx/pokemon/munna/bitmask.asm"
MusharnaBitmasks:   INCLUDE "gfx/pokemon/musharna/bitmask.asm"
PidoveBitmasks:     INCLUDE "gfx/pokemon/pidove/bitmask.asm"
TranquillBitmasks:  INCLUDE "gfx/pokemon/tranquill/bitmask.asm"
BlitzleBitmasks:    INCLUDE "gfx/pokemon/blitzle/bitmask.asm"
ZebstrikaBitmasks:  INCLUDE "gfx/pokemon/zebstrika/bitmask.asm"
RoggenrolaBitmasks: INCLUDE "gfx/pokemon/roggenrola/bitmask.asm"
BoldoreBitmasks:    INCLUDE "gfx/pokemon/boldore/bitmask.asm"
GigalithBitmasks:   INCLUDE "gfx/pokemon/gigalith/bitmask.asm"
WoobatBitmasks:     INCLUDE "gfx/pokemon/woobat/bitmask.asm"
SwoobatBitmasks:    INCLUDE "gfx/pokemon/swoobat/bitmask.asm"
DrilburBitmasks:    INCLUDE "gfx/pokemon/drilbur/bitmask.asm"
ExcadrillBitmasks:  INCLUDE "gfx/pokemon/excadrill/bitmask.asm"
AudinoBitmasks:     INCLUDE "gfx/pokemon/audino/bitmask.asm"
TimburrBitmasks:    INCLUDE "gfx/pokemon/timburr/bitmask.asm"
GurdurrBitmasks:    INCLUDE "gfx/pokemon/gurdurr/bitmask.asm"
ConkeldurrBitmasks: INCLUDE "gfx/pokemon/conkeldurr/bitmask.asm"
TympoleBitmasks:    INCLUDE "gfx/pokemon/tympole/bitmask.asm"
PalpitoadBitmasks:  INCLUDE "gfx/pokemon/palpitoad/bitmask.asm"
SeismitoadBitmasks: INCLUDE "gfx/pokemon/seismitoad/bitmask.asm"
ThrohBitmasks:      INCLUDE "gfx/pokemon/throh/bitmask.asm"
SawkBitmasks:       INCLUDE "gfx/pokemon/sawk/bitmask.asm"
SewaddleBitmasks:   INCLUDE "gfx/pokemon/sewaddle/bitmask.asm"
SwadloonBitmasks:   INCLUDE "gfx/pokemon/swadloon/bitmask.asm"
LeavannyBitmasks:   INCLUDE "gfx/pokemon/leavanny/bitmask.asm"
VenipedeBitmasks:   INCLUDE "gfx/pokemon/venipede/bitmask.asm"
WhirlipedeBitmasks: INCLUDE "gfx/pokemon/whirlipede/bitmask.asm"
ScolipedeBitmasks:  INCLUDE "gfx/pokemon/scolipede/bitmask.asm"
CottoneeBitmasks:   INCLUDE "gfx/pokemon/cottonee/bitmask.asm"
WhimsicottBitmasks: INCLUDE "gfx/pokemon/whimsicott/bitmask.asm"
PetililBitmasks:    INCLUDE "gfx/pokemon/petilil/bitmask.asm"
SandileBitmasks:    INCLUDE "gfx/pokemon/sandile/bitmask.asm"
KrokorokBitmasks:   INCLUDE "gfx/pokemon/krokorok/bitmask.asm"
KrookodileBitmasks: INCLUDE "gfx/pokemon/krookodile/bitmask.asm"
MaractusBitmasks:   INCLUDE "gfx/pokemon/maractus/bitmask.asm"
DwebbleBitmasks:    INCLUDE "gfx/pokemon/dwebble/bitmask.asm"
CrustleBitmasks:    INCLUDE "gfx/pokemon/crustle/bitmask.asm"
ScraggyBitmasks:    INCLUDE "gfx/pokemon/scraggy/bitmask.asm"
ScraftyBitmasks:    INCLUDE "gfx/pokemon/scrafty/bitmask.asm"
SigilyphBitmasks:   INCLUDE "gfx/pokemon/sigilyph/bitmask.asm"
CofagrigusBitmasks: INCLUDE "gfx/pokemon/cofagrigus/bitmask.asm"
TirtougaBitmasks:   INCLUDE "gfx/pokemon/tirtouga/bitmask.asm"
CarracostaBitmasks: INCLUDE "gfx/pokemon/carracosta/bitmask.asm"
ArchenBitmasks:     INCLUDE "gfx/pokemon/archen/bitmask.asm"
ArcheopsBitmasks:   INCLUDE "gfx/pokemon/archeops/bitmask.asm"
TrubbishBitmasks:   INCLUDE "gfx/pokemon/trubbish/bitmask.asm"
GarbodorBitmasks:   INCLUDE "gfx/pokemon/garbodor/bitmask.asm"
MinccinoBitmasks:   INCLUDE "gfx/pokemon/minccino/bitmask.asm"
CinccinoBitmasks:   INCLUDE "gfx/pokemon/cinccino/bitmask.asm"
GothitaBitmasks:    INCLUDE "gfx/pokemon/gothita/bitmask.asm"
GothoritaBitmasks:  INCLUDE "gfx/pokemon/gothorita/bitmask.asm"
GothitelleBitmasks: INCLUDE "gfx/pokemon/gothitelle/bitmask.asm"
SolosisBitmasks:    INCLUDE "gfx/pokemon/solosis/bitmask.asm"
DuosionBitmasks:    INCLUDE "gfx/pokemon/duosion/bitmask.asm"
ReuniclusBitmasks:  INCLUDE "gfx/pokemon/reuniclus/bitmask.asm"
DucklettBitmasks:   INCLUDE "gfx/pokemon/ducklett/bitmask.asm"
SwannaBitmasks:     INCLUDE "gfx/pokemon/swanna/bitmask.asm"
VanilliteBitmasks:  INCLUDE "gfx/pokemon/vanillite/bitmask.asm"
VanillishBitmasks:  INCLUDE "gfx/pokemon/vanillish/bitmask.asm"
VanilluxeBitmasks:  INCLUDE "gfx/pokemon/vanilluxe/bitmask.asm"
EmolgaBitmasks:     INCLUDE "gfx/pokemon/emolga/bitmask.asm"
KarrablastBitmasks: INCLUDE "gfx/pokemon/karrablast/bitmask.asm"
EscavalierBitmasks: INCLUDE "gfx/pokemon/escavalier/bitmask.asm"
FoongusBitmasks:    INCLUDE "gfx/pokemon/foongus/bitmask.asm"
AmoongussBitmasks:  INCLUDE "gfx/pokemon/amoonguss/bitmask.asm"
AlomomolaBitmasks:  INCLUDE "gfx/pokemon/alomomola/bitmask.asm"
JoltikBitmasks:     INCLUDE "gfx/pokemon/joltik/bitmask.asm"
GalvantulaBitmasks: INCLUDE "gfx/pokemon/galvantula/bitmask.asm"
FerroseedBitmasks:  INCLUDE "gfx/pokemon/ferroseed/bitmask.asm"
FerrothornBitmasks: INCLUDE "gfx/pokemon/ferrothorn/bitmask.asm"
KlinkBitmasks:      INCLUDE "gfx/pokemon/klink/bitmask.asm"
KlangBitmasks:      INCLUDE "gfx/pokemon/klang/bitmask.asm"
KlinklangBitmasks:  INCLUDE "gfx/pokemon/klinklang/bitmask.asm"
TynamoBitmasks:     INCLUDE "gfx/pokemon/tynamo/bitmask.asm"
EelektrikBitmasks:  INCLUDE "gfx/pokemon/eelektrik/bitmask.asm"
EelektrossBitmasks: INCLUDE "gfx/pokemon/eelektross/bitmask.asm"
ElgyemBitmasks:     INCLUDE "gfx/pokemon/elgyem/bitmask.asm"
BeheeyemBitmasks:   INCLUDE "gfx/pokemon/beheeyem/bitmask.asm"
LitwickBitmasks:    INCLUDE "gfx/pokemon/litwick/bitmask.asm"
LampentBitmasks:    INCLUDE "gfx/pokemon/lampent/bitmask.asm"
ChandelureBitmasks: INCLUDE "gfx/pokemon/chandelure/bitmask.asm"
AxewBitmasks:       INCLUDE "gfx/pokemon/axew/bitmask.asm"
FraxureBitmasks:    INCLUDE "gfx/pokemon/fraxure/bitmask.asm"
HaxorusBitmasks:    INCLUDE "gfx/pokemon/haxorus/bitmask.asm"
CubchooBitmasks:    INCLUDE "gfx/pokemon/cubchoo/bitmask.asm"
BearticBitmasks:    INCLUDE "gfx/pokemon/beartic/bitmask.asm"
CryogonalBitmasks:  INCLUDE "gfx/pokemon/cryogonal/bitmask.asm"
ShelmetBitmasks:    INCLUDE "gfx/pokemon/shelmet/bitmask.asm"
AccelgorBitmasks:   INCLUDE "gfx/pokemon/accelgor/bitmask.asm"
MienfooBitmasks:    INCLUDE "gfx/pokemon/mienfoo/bitmask.asm"
MienshaoBitmasks:   INCLUDE "gfx/pokemon/mienshao/bitmask.asm"
DruddigonBitmasks:  INCLUDE "gfx/pokemon/druddigon/bitmask.asm"
GolettBitmasks:     INCLUDE "gfx/pokemon/golett/bitmask.asm"
GolurkBitmasks:     INCLUDE "gfx/pokemon/golurk/bitmask.asm"
PawniardBitmasks:   INCLUDE "gfx/pokemon/pawniard/bitmask.asm"
BisharpBitmasks:    INCLUDE "gfx/pokemon/bisharp/bitmask.asm"
BouffalantBitmasks: INCLUDE "gfx/pokemon/bouffalant/bitmask.asm"
RuffletBitmasks:    INCLUDE "gfx/pokemon/rufflet/bitmask.asm"
VullabyBitmasks:    INCLUDE "gfx/pokemon/vullaby/bitmask.asm"
MandibuzzBitmasks:  INCLUDE "gfx/pokemon/mandibuzz/bitmask.asm"
HeatmorBitmasks:    INCLUDE "gfx/pokemon/heatmor/bitmask.asm"
DurantBitmasks:     INCLUDE "gfx/pokemon/durant/bitmask.asm"
DeinoBitmasks:      INCLUDE "gfx/pokemon/deino/bitmask.asm"
ZweilousBitmasks:   INCLUDE "gfx/pokemon/zweilous/bitmask.asm"
HydreigonBitmasks:  INCLUDE "gfx/pokemon/hydreigon/bitmask.asm"
LarvestaBitmasks:   INCLUDE "gfx/pokemon/larvesta/bitmask.asm"
VolcaronaBitmasks:  INCLUDE "gfx/pokemon/volcarona/bitmask.asm"
CobalionBitmasks:   INCLUDE "gfx/pokemon/cobalion/bitmask.asm"
TerrakionBitmasks:  INCLUDE "gfx/pokemon/terrakion/bitmask.asm"
VirizionBitmasks:   INCLUDE "gfx/pokemon/virizion/bitmask.asm"
ReshiramBitmasks:   INCLUDE "gfx/pokemon/reshiram/bitmask.asm"
ZekromBitmasks:     INCLUDE "gfx/pokemon/zekrom/bitmask.asm"
KeldeoBitmasks:     INCLUDE "gfx/pokemon/keldeo/bitmask.asm"
GenesectBitmasks:   INCLUDE "gfx/pokemon/genesect/bitmask.asm"
RunerigusBitmasks:  INCLUDE "gfx/pokemon/runerigus/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

PichuPlainBitmasks: INCLUDE "gfx/pokemon/pichu_plain/bitmask.asm"
PichuSpikyBitmasks: INCLUDE "gfx/pokemon/pichu_spiky/bitmask.asm"

PikachuPlainBitmasks:  INCLUDE "gfx/pokemon/pikachu_plain/bitmask.asm"
PikachuFlyBitmasks:    INCLUDE "gfx/pokemon/pikachu_fly/bitmask.asm"
PikachuSurfBitmasks:   INCLUDE "gfx/pokemon/pikachu_surf/bitmask.asm"
PikachuPikaBitmasks:   INCLUDE "gfx/pokemon/pikachu_pika/bitmask.asm"
PikachuChuchuBitmasks: INCLUDE "gfx/pokemon/pikachu_chuchu/bitmask.asm"
PikachuSparkBitmasks:  INCLUDE "gfx/pokemon/pikachu_spark/bitmask.asm"

DudunsparceTwoSegmentBitmasks:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/bitmask.asm"
DudunsparceThreeSegmentBitmasks: INCLUDE "gfx/pokemon/dudunsparce_three_segment/bitmask.asm"

RattataPlainBitmasks:  INCLUDE "gfx/pokemon/rattata_plain/bitmask.asm"
RattataAlolanBitmasks: INCLUDE "gfx/pokemon/rattata_alolan/bitmask.asm"

RaticatePlainBitmasks:  INCLUDE "gfx/pokemon/raticate_plain/bitmask.asm"
RaticateAlolanBitmasks: INCLUDE "gfx/pokemon/raticate_alolan/bitmask.asm"

RaichuPlainBitmasks:  INCLUDE "gfx/pokemon/raichu_plain/bitmask.asm"
RaichuAlolanBitmasks: INCLUDE "gfx/pokemon/raichu_alolan/bitmask.asm"

SandshrewPlainBitmasks:  INCLUDE "gfx/pokemon/sandshrew_plain/bitmask.asm"
SandshrewAlolanBitmasks: INCLUDE "gfx/pokemon/sandshrew_alolan/bitmask.asm"

SandslashPlainBitmasks:  INCLUDE "gfx/pokemon/sandslash_plain/bitmask.asm"
SandslashAlolanBitmasks: INCLUDE "gfx/pokemon/sandslash_alolan/bitmask.asm"

VulpixPlainBitmasks:  INCLUDE "gfx/pokemon/vulpix_plain/bitmask.asm"
VulpixAlolanBitmasks: INCLUDE "gfx/pokemon/vulpix_alolan/bitmask.asm"

NinetalesPlainBitmasks:  INCLUDE "gfx/pokemon/ninetales_plain/bitmask.asm"
NinetalesAlolanBitmasks: INCLUDE "gfx/pokemon/ninetales_alolan/bitmask.asm"

MeowthPlainBitmasks:    INCLUDE "gfx/pokemon/meowth_plain/bitmask.asm"
MeowthAlolanBitmasks:   INCLUDE "gfx/pokemon/meowth_alolan/bitmask.asm"
MeowthGalarianBitmasks: INCLUDE "gfx/pokemon/meowth_galarian/bitmask.asm"

PersianPlainBitmasks:  INCLUDE "gfx/pokemon/persian_plain/bitmask.asm"
PersianAlolanBitmasks: INCLUDE "gfx/pokemon/persian_alolan/bitmask.asm"

GeodudePlainBitmasks:  INCLUDE "gfx/pokemon/geodude_plain/bitmask.asm"
GeodudeAlolanBitmasks: INCLUDE "gfx/pokemon/geodude_alolan/bitmask.asm"

GravelerPlainBitmasks:  INCLUDE "gfx/pokemon/graveler_plain/bitmask.asm"
GravelerAlolanBitmasks: INCLUDE "gfx/pokemon/graveler_alolan/bitmask.asm"

GolemPlainBitmasks:  INCLUDE "gfx/pokemon/golem_plain/bitmask.asm"
GolemAlolanBitmasks: INCLUDE "gfx/pokemon/golem_alolan/bitmask.asm"

GrimerPlainBitmasks:  INCLUDE "gfx/pokemon/grimer_plain/bitmask.asm"
GrimerAlolanBitmasks: INCLUDE "gfx/pokemon/grimer_alolan/bitmask.asm"

MukPlainBitmasks:  INCLUDE "gfx/pokemon/muk_plain/bitmask.asm"
MukAlolanBitmasks: INCLUDE "gfx/pokemon/muk_alolan/bitmask.asm"

ExeggutorPlainBitmasks:  INCLUDE "gfx/pokemon/exeggutor_plain/bitmask.asm"
ExeggutorAlolanBitmasks: INCLUDE "gfx/pokemon/exeggutor_alolan/bitmask.asm"

PonytaPlainBitmasks:    INCLUDE "gfx/pokemon/ponyta_plain/bitmask.asm"
PonytaGalarianBitmasks: INCLUDE "gfx/pokemon/ponyta_galarian/bitmask.asm"

RapidashPlainBitmasks:    INCLUDE "gfx/pokemon/rapidash_plain/bitmask.asm"
RapidashGalarianBitmasks: INCLUDE "gfx/pokemon/rapidash_galarian/bitmask.asm"

SlowpokePlainBitmasks:   INCLUDE "gfx/pokemon/slowpoke_plain/bitmask.asm"
SlowpokeGalarianBitmasks: INCLUDE "gfx/pokemon/slowpoke_galarian/bitmask.asm"

SlowbroPlainBitmasks:    INCLUDE "gfx/pokemon/slowbro_plain/bitmask.asm"
SlowbroGalarianBitmasks: INCLUDE "gfx/pokemon/slowbro_galarian/bitmask.asm"

WeezingPlainBitmasks:    INCLUDE "gfx/pokemon/weezing_plain/bitmask.asm"
WeezingGalarianBitmasks: INCLUDE "gfx/pokemon/weezing_galarian/bitmask.asm"

MrMimePlainBitmasks:    INCLUDE "gfx/pokemon/mr__mime_plain/bitmask.asm"
MrMimeGalarianBitmasks: INCLUDE "gfx/pokemon/mr__mime_galarian/bitmask.asm"

SlowkingPlainBitmasks:    INCLUDE "gfx/pokemon/slowking_plain/bitmask.asm"
SlowkingGalarianBitmasks: INCLUDE "gfx/pokemon/slowking_galarian/bitmask.asm"

CorsolaPlainBitmasks:    INCLUDE "gfx/pokemon/corsola_plain/bitmask.asm"
CorsolaGalarianBitmasks: INCLUDE "gfx/pokemon/corsola_galarian/bitmask.asm"

GrowlithePlainBitmasks:   INCLUDE "gfx/pokemon/growlithe_plain/bitmask.asm"
GrowlitheHisuianBitmasks: INCLUDE "gfx/pokemon/growlithe_hisuian/bitmask.asm"

ArcaninePlainBitmasks:   INCLUDE "gfx/pokemon/arcanine_plain/bitmask.asm"
ArcanineHisuianBitmasks: INCLUDE "gfx/pokemon/arcanine_hisuian/bitmask.asm"

SneaselPlainBitmasks:   INCLUDE "gfx/pokemon/sneasel_plain/bitmask.asm"
SneaselHisuianBitmasks: INCLUDE "gfx/pokemon/sneasel_hisuian/bitmask.asm"

CastformPlainBitmasks: INCLUDE "gfx/pokemon/castform_plain/bitmask.asm"
CastformSunBitmasks:   INCLUDE "gfx/pokemon/castform_sun/bitmask.asm"
CastformRainBitmasks:  INCLUDE "gfx/pokemon/castform_rain/bitmask.asm"
CastformHailBitmasks:  INCLUDE "gfx/pokemon/castform_hail/bitmask.asm"

CombeeMaleBitmasks:   INCLUDE "gfx/pokemon/combee_male/bitmask.asm"
CombeeFemaleBitmasks: INCLUDE "gfx/pokemon/combee_female/bitmask.asm"

UnfezantMaleBitmasks:   INCLUDE "gfx/pokemon/unfezant_male/bitmask.asm"
UnfezantFemaleBitmasks: INCLUDE "gfx/pokemon/unfezant_female/bitmask.asm"

SamurottPlainBitmasks: INCLUDE "gfx/pokemon/samurott_plain/bitmask.asm"

LilligantPlainBitmasks: INCLUDE "gfx/pokemon/lilligant_plain/bitmask.asm"

BasculinRedBitmasks:   INCLUDE "gfx/pokemon/basculin_red/bitmask.asm"
BasculinBlueBitmasks:  INCLUDE "gfx/pokemon/basculin_blue/bitmask.asm"
BasculinWhiteBitmasks: INCLUDE "gfx/pokemon/basculin_white/bitmask.asm"

DarumakaPlainBitmasks:    INCLUDE "gfx/pokemon/darumaka_plain/bitmask.asm"
DarumakaGalarianBitmasks: INCLUDE "gfx/pokemon/darumaka_galarian/bitmask.asm"

DarmanitanPlainBitmasks:       INCLUDE "gfx/pokemon/darmanitan_plain/bitmask.asm"
DarmanitanZenBitmasks:         INCLUDE "gfx/pokemon/darmanitan_zen/bitmask.asm"
DarmanitanGalarianBitmasks:    INCLUDE "gfx/pokemon/darmanitan_galarian/bitmask.asm"
DarmanitanGalarianZenBitmasks: INCLUDE "gfx/pokemon/darmanitan_galarian_zen/bitmask.asm"

YamaskPlainBitmasks:    INCLUDE "gfx/pokemon/yamask_plain/bitmask.asm"
YamaskGalarianBitmasks: INCLUDE "gfx/pokemon/yamask_galarian/bitmask.asm"

ZoruaPlainBitmasks: INCLUDE "gfx/pokemon/zorua_plain/bitmask.asm"

ZoroarkPlainBitmasks: INCLUDE "gfx/pokemon/zoroark_plain/bitmask.asm"

DeerlingSpringBitmasks: INCLUDE "gfx/pokemon/deerling_spring/bitmask.asm"
DeerlingSummerBitmasks: INCLUDE "gfx/pokemon/deerling_summer/bitmask.asm"
DeerlingAutumnBitmasks: INCLUDE "gfx/pokemon/deerling_autumn/bitmask.asm"
DeerlingWinterBitmasks: INCLUDE "gfx/pokemon/deerling_winter/bitmask.asm"

SawsbuckSpringBitmasks: INCLUDE "gfx/pokemon/sawsbuck_spring/bitmask.asm"
SawsbuckSummerBitmasks: INCLUDE "gfx/pokemon/sawsbuck_summer/bitmask.asm"
SawsbuckAutumnBitmasks: INCLUDE "gfx/pokemon/sawsbuck_autumn/bitmask.asm"
SawsbuckWinterBitmasks: INCLUDE "gfx/pokemon/sawsbuck_winter/bitmask.asm"

FrillishMaleBitmasks:   INCLUDE "gfx/pokemon/frillish_male/bitmask.asm"
FrillishFemaleBitmasks: INCLUDE "gfx/pokemon/frillish_female/bitmask.asm"

JellicentMaleBitmasks:   INCLUDE "gfx/pokemon/jellicent_male/bitmask.asm"
JellicentFemaleBitmasks: INCLUDE "gfx/pokemon/jellicent_female/bitmask.asm"

StunfiskPlainBitmasks: INCLUDE "gfx/pokemon/stunfisk_plain/bitmask.asm"

BraviaryPlainBitmasks: INCLUDE "gfx/pokemon/braviary_plain/bitmask.asm"

TornadusPlainBitmasks:   INCLUDE "gfx/pokemon/tornadus_plain/bitmask.asm"
TornadusTherianBitmasks: INCLUDE "gfx/pokemon/tornadus_therian/bitmask.asm"

ThundurusPlainBitmasks:   INCLUDE "gfx/pokemon/thundurus_plain/bitmask.asm"
ThundurusTherianBitmasks: INCLUDE "gfx/pokemon/thundurus_therian/bitmask.asm"

LandorusPlainBitmasks:   INCLUDE "gfx/pokemon/landorus_plain/bitmask.asm"
LandorusTherianBitmasks: INCLUDE "gfx/pokemon/landorus_therian/bitmask.asm"

KyuremPlainBitmasks: INCLUDE "gfx/pokemon/kyurem_plain/bitmask.asm"
KyuremWhiteBitmasks: INCLUDE "gfx/pokemon/kyurem_white/bitmask.asm"
KyuremBlackBitmasks: INCLUDE "gfx/pokemon/kyurem_black/bitmask.asm"

MeloettaPlainBitmasks:     INCLUDE "gfx/pokemon/meloetta_plain/bitmask.asm"
MeloettaPirouetteBitmasks: INCLUDE "gfx/pokemon/meloetta_pirouette/bitmask.asm"
