AnimationExtraPointers:
	table_width 2
	dw RattataPlainAnimationExtra
	dw RaticatePlainAnimationExtra
	dw PikachuPlainAnimationExtra
	dw RaichuPlainAnimationExtra
	dw SandshrewPlainAnimationExtra
	dw SandslashPlainAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw VulpixPlainAnimationExtra
	dw NinetalesPlainAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw MeowthPlainAnimationExtra
	dw PersianPlainAnimationExtra
	dw PsyduckAnimationExtra
	dw GolduckAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlithePlainAnimationExtra
	dw ArcaninePlainAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw GeodudePlainAnimationExtra
	dw GravelerPlainAnimationExtra
	dw GolemPlainAnimationExtra
	dw PonytaPlainAnimationExtra
	dw RapidashPlainAnimationExtra
	dw SlowpokePlainAnimationExtra
	dw SlowbroPlainAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw SeelAnimationExtra
	dw DewgongAnimationExtra
	dw GrimerPlainAnimationExtra
	dw MukPlainAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorPlainAnimationExtra
	dw LickitungAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingPlainAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw MrMimePlainAnimationExtra
	dw ScytherAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw PinsirAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw SnorlaxAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuPlainAnimationExtra
	dw CleffaAnimationExtra
	dw IgglybuffAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingPlainAnimationExtra
	dw MisdreavusAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselPlainAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaPlainAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw DelibirdAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LotadAnimationExtra
	dw LombreAnimationExtra
	dw LudicoloAnimationExtra
	dw SeedotAnimationExtra
	dw NuzleafAnimationExtra
	dw ShiftryAnimationExtra
	dw WingullAnimationExtra
	dw PelipperAnimationExtra
	dw RaltsAnimationExtra
	dw KirliaAnimationExtra
	dw GardevoirAnimationExtra
	dw ShroomishAnimationExtra
	dw BreloomAnimationExtra
	dw SlakothAnimationExtra
	dw VigorothAnimationExtra
	dw SlakingAnimationExtra
	dw AzurillAnimationExtra
	dw NosepassAnimationExtra
	dw SkittyAnimationExtra
	dw DelcattyAnimationExtra
	dw SableyeAnimationExtra
	dw MawileAnimationExtra
	dw AronAnimationExtra
	dw LaironAnimationExtra
	dw AggronAnimationExtra
	dw MedititeAnimationExtra
	dw MedichamAnimationExtra
	dw RoseliaAnimationExtra
	dw WailmerAnimationExtra
	dw WailordAnimationExtra
	dw NumelAnimationExtra
	dw CameruptAnimationExtra
	dw TorkoalAnimationExtra
	dw SpoinkAnimationExtra
	dw GrumpigAnimationExtra
	dw TrapinchAnimationExtra
	dw VibravaAnimationExtra
	dw FlygonAnimationExtra
	dw SwabluAnimationExtra
	dw AltariaAnimationExtra
	dw ZangooseAnimationExtra
	dw SeviperAnimationExtra
	dw LunatoneAnimationExtra
	dw SolrockAnimationExtra
	dw CorphishAnimationExtra
	dw CrawdauntAnimationExtra
	dw BaltoyAnimationExtra
	dw ClaydolAnimationExtra
	dw CastformPlainAnimationExtra
	dw MismagiusAnimationExtra
	dw HonchkrowAnimationExtra
	dw BonslyAnimationExtra
	dw MimeJrAnimationExtra
	dw MunchlaxAnimationExtra
	dw MantykeAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw LickilickyAnimationExtra
	dw TangrowthAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw YanmegaAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw SylveonAnimationExtra
	dw PerrserkerAnimationExtra
	dw CursolaAnimationExtra
	dw MrRimeAnimationExtra
	dw KleavorAnimationExtra
	dw SneaslerAnimationExtra
	dw DudunsparceTwoSegmentAnimationExtra
	dw AnnihilapeAnimationExtra
	dw VictiniAnimationExtra
	dw SnivyAnimationExtra
	dw ServineAnimationExtra
	dw SerperiorAnimationExtra
	dw TepigAnimationExtra
	dw PigniteAnimationExtra
	dw EmboarAnimationExtra
	dw OshawottAnimationExtra
	dw DewottAnimationExtra
	dw SamurottPlainAnimationExtra
	dw PatratAnimationExtra
	dw WatchogAnimationExtra
	dw LillipupAnimationExtra
	dw HerdierAnimationExtra
	dw StoutlandAnimationExtra
	dw PurrloinAnimationExtra
	dw LiepardAnimationExtra
	dw PansageAnimationExtra
	dw SimisageAnimationExtra
	dw PansearAnimationExtra
	dw SimisearAnimationExtra
	dw PanpourAnimationExtra
	dw SimipourAnimationExtra
	dw MunnaAnimationExtra
	dw MusharnaAnimationExtra
	dw PidoveAnimationExtra
	dw TranquillAnimationExtra
	dw UnfezantMaleAnimationExtra
	dw BlitzleAnimationExtra
	dw ZebstrikaAnimationExtra
	dw RoggenrolaAnimationExtra
	dw BoldoreAnimationExtra
	dw GigalithAnimationExtra
	dw WoobatAnimationExtra
	dw SwoobatAnimationExtra
	dw DrilburAnimationExtra
	dw ExcadrillAnimationExtra
	dw AudinoAnimationExtra
	dw TimburrAnimationExtra
	dw GurdurrAnimationExtra
	dw ConkeldurrAnimationExtra
	dw TympoleAnimationExtra
	dw PalpitoadAnimationExtra
	dw SeismitoadAnimationExtra
	dw ThrohAnimationExtra
	dw SawkAnimationExtra
	dw SewaddleAnimationExtra
	dw SwadloonAnimationExtra
	dw LeavannyAnimationExtra
	dw VenipedeAnimationExtra
	dw WhirlipedeAnimationExtra
	dw ScolipedeAnimationExtra
	dw CottoneeAnimationExtra
	dw WhimsicottAnimationExtra
	dw PetililAnimationExtra
	dw EggAnimationExtra
	dw EggAnimationExtra ; $100
	dw LilligantPlainAnimationExtra
	dw BasculinWhiteAnimationExtra
	dw SandileAnimationExtra
	dw KrokorokAnimationExtra
	dw KrookodileAnimationExtra
	dw DarumakaPlainAnimationExtra
	dw DarmanitanPlainAnimationExtra
	dw MaractusAnimationExtra
	dw DwebbleAnimationExtra
	dw CrustleAnimationExtra
	dw ScraggyAnimationExtra
	dw ScraftyAnimationExtra
	dw SigilyphAnimationExtra
	dw YamaskPlainAnimationExtra
	dw CofagrigusAnimationExtra
	dw TirtougaAnimationExtra
	dw CarracostaAnimationExtra
	dw ArchenAnimationExtra
	dw ArcheopsAnimationExtra
	dw TrubbishAnimationExtra
	dw GarbodorAnimationExtra
	dw ZoruaPlainAnimationExtra
	dw ZoroarkPlainAnimationExtra
	dw MinccinoAnimationExtra
	dw CinccinoAnimationExtra
	dw GothitaAnimationExtra
	dw GothoritaAnimationExtra
	dw GothitelleAnimationExtra
	dw SolosisAnimationExtra
	dw DuosionAnimationExtra
	dw ReuniclusAnimationExtra
	dw DucklettAnimationExtra
	dw SwannaAnimationExtra
	dw VanilliteAnimationExtra
	dw VanillishAnimationExtra
	dw VanilluxeAnimationExtra
	dw DeerlingSpringAnimationExtra
	dw SawsbuckSpringAnimationExtra
	dw EmolgaAnimationExtra
	dw KarrablastAnimationExtra
	dw EscavalierAnimationExtra
	dw FoongusAnimationExtra
	dw AmoongussAnimationExtra
	dw FrillishMaleAnimationExtra
	dw JellicentMaleAnimationExtra
	dw AlomomolaAnimationExtra
	dw JoltikAnimationExtra
	dw GalvantulaAnimationExtra
	dw FerroseedAnimationExtra
	dw FerrothornAnimationExtra
	dw KlinkAnimationExtra
	dw KlangAnimationExtra
	dw KlinklangAnimationExtra
	dw TynamoAnimationExtra
	dw EelektrikAnimationExtra
	dw EelektrossAnimationExtra
	dw ElgyemAnimationExtra
	dw BeheeyemAnimationExtra
	dw LitwickAnimationExtra
	dw LampentAnimationExtra
	dw ChandelureAnimationExtra
	dw AxewAnimationExtra
	dw FraxureAnimationExtra
	dw HaxorusAnimationExtra
	dw CubchooAnimationExtra
	dw BearticAnimationExtra
	dw CryogonalAnimationExtra
	dw ShelmetAnimationExtra
	dw AccelgorAnimationExtra
	dw StunfiskPlainAnimationExtra
	dw MienfooAnimationExtra
	dw MienshaoAnimationExtra
	dw DruddigonAnimationExtra
	dw GolettAnimationExtra
	dw GolurkAnimationExtra
	dw PawniardAnimationExtra
	dw BisharpAnimationExtra
	dw BouffalantAnimationExtra
	dw RuffletAnimationExtra
	dw BraviaryPlainAnimationExtra
	dw VullabyAnimationExtra
	dw MandibuzzAnimationExtra
	dw HeatmorAnimationExtra
	dw DurantAnimationExtra
	dw DeinoAnimationExtra
	dw ZweilousAnimationExtra
	dw HydreigonAnimationExtra
	dw LarvestaAnimationExtra
	dw VolcaronaAnimationExtra
	dw CobalionAnimationExtra
	dw TerrakionAnimationExtra
	dw VirizionAnimationExtra
	dw TornadusPlainAnimationExtra
	dw ThundurusPlainAnimationExtra
	dw ReshiramAnimationExtra
	dw ZekromAnimationExtra
	dw LandorusPlainAnimationExtra
	dw KyuremPlainAnimationExtra
	dw KeldeoAnimationExtra
	dw MeloettaPlainAnimationExtra
	dw GenesectAnimationExtra
	dw RunerigusAnimationExtra
	assert_table_length NUM_SPECIES

	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra
	dw PikachuSparkAnimationExtra

	dw PichuSpikyAnimationExtra

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw DudunsparceThreeSegmentAnimationExtra

	dw RattataAlolanAnimationExtra
	dw RaticateAlolanAnimationExtra
	dw RaichuAlolanAnimationExtra
	dw SandshrewAlolanAnimationExtra
	dw SandslashAlolanAnimationExtra
	dw VulpixAlolanAnimationExtra
	dw NinetalesAlolanAnimationExtra
	dw MeowthAlolanAnimationExtra
	dw PersianAlolanAnimationExtra
	dw GeodudeAlolanAnimationExtra
	dw GravelerAlolanAnimationExtra
	dw GolemAlolanAnimationExtra
	dw GrimerAlolanAnimationExtra
	dw MukAlolanAnimationExtra
	dw ExeggutorAlolanAnimationExtra

	dw MeowthGalarianAnimationExtra
	dw PonytaGalarianAnimationExtra
	dw RapidashGalarianAnimationExtra
	dw SlowpokeGalarianAnimationExtra
	dw SlowbroGalarianAnimationExtra
	dw WeezingGalarianAnimationExtra
	dw MrMimeGalarianAnimationExtra
	dw SlowkingGalarianAnimationExtra
	dw CorsolaGalarianAnimationExtra
	dw DarumakaGalarianAnimationExtra
	dw DarmanitanGalarianAnimationExtra
	dw YamaskGalarianAnimationExtra

	dw GrowlitheHisuianAnimationExtra
	dw ArcanineHisuianAnimationExtra
	dw SneaselHisuianAnimationExtra
	
	dw CastformSunAnimationExtra
	dw CastformRainAnimationExtra
	dw CastformHailAnimationExtra
	
	dw UnfezantFemaleAnimationExtra
	
	dw BasculinRedAnimationExtra
	dw BasculinBlueAnimationExtra
	
	dw DarmanitanZenAnimationExtra
	dw DarmanitanGalarianZenAnimationExtra
	
	dw DeerlingSummerAnimationExtra
	dw DeerlingAutumnAnimationExtra
	dw DeerlingWinterAnimationExtra
	
	dw SawsbuckSummerAnimationExtra
	dw SawsbuckAutumnAnimationExtra
	dw SawsbuckWinterAnimationExtra
	
	dw FrillishFemaleAnimationExtra
	dw JellicentFemaleAnimationExtra
	
	dw TornadusTherianAnimationExtra
	dw ThundurusTherianAnimationExtra
	dw LandorusTherianAnimationExtra
	
	dw KyuremWhiteAnimationExtra
	dw KyuremBlackAnimationExtra
	
	dw MeloettaPirouetteAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
