NidoranFAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_f/anim_idle.asm"
NidorinaAnimationExtra:   INCLUDE "gfx/pokemon/nidorina/anim_idle.asm"
NidoqueenAnimationExtra:  INCLUDE "gfx/pokemon/nidoqueen/anim_idle.asm"
NidoranMAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_m/anim_idle.asm"
NidorinoAnimationExtra:   INCLUDE "gfx/pokemon/nidorino/anim_idle.asm"
NidokingAnimationExtra:   INCLUDE "gfx/pokemon/nidoking/anim_idle.asm"
ClefairyAnimationExtra:   INCLUDE "gfx/pokemon/clefairy/anim_idle.asm"
ClefableAnimationExtra:   INCLUDE "gfx/pokemon/clefable/anim_idle.asm"
JigglypuffAnimationExtra: INCLUDE "gfx/pokemon/jigglypuff/anim_idle.asm"
WigglytuffAnimationExtra: INCLUDE "gfx/pokemon/wigglytuff/anim_idle.asm"
ZubatAnimationExtra:      INCLUDE "gfx/pokemon/zubat/anim_idle.asm"
GolbatAnimationExtra:     INCLUDE "gfx/pokemon/golbat/anim_idle.asm"
ParasAnimationExtra:      INCLUDE "gfx/pokemon/paras/anim_idle.asm"
ParasectAnimationExtra:   INCLUDE "gfx/pokemon/parasect/anim_idle.asm"
PsyduckAnimationExtra:    INCLUDE "gfx/pokemon/psyduck/anim_idle.asm"
GolduckAnimationExtra:    INCLUDE "gfx/pokemon/golduck/anim_idle.asm"
MankeyAnimationExtra:     INCLUDE "gfx/pokemon/mankey/anim_idle.asm"
PrimeapeAnimationExtra:   INCLUDE "gfx/pokemon/primeape/anim_idle.asm"
PoliwagAnimationExtra:    INCLUDE "gfx/pokemon/poliwag/anim_idle.asm"
PoliwhirlAnimationExtra:  INCLUDE "gfx/pokemon/poliwhirl/anim_idle.asm"
PoliwrathAnimationExtra:  INCLUDE "gfx/pokemon/poliwrath/anim_idle.asm"
MagnemiteAnimationExtra:  INCLUDE "gfx/pokemon/magnemite/anim_idle.asm"
MagnetonAnimationExtra:   INCLUDE "gfx/pokemon/magneton/anim_idle.asm"
SeelAnimationExtra:       INCLUDE "gfx/pokemon/seel/anim_idle.asm"
DewgongAnimationExtra:    INCLUDE "gfx/pokemon/dewgong/anim_idle.asm"
GastlyAnimationExtra:     INCLUDE "gfx/pokemon/gastly/anim_idle.asm"
HaunterAnimationExtra:    INCLUDE "gfx/pokemon/haunter/anim_idle.asm"
GengarAnimationExtra:     INCLUDE "gfx/pokemon/gengar/anim_idle.asm"
OnixAnimationExtra:       INCLUDE "gfx/pokemon/onix/anim_idle.asm"
ExeggcuteAnimationExtra:  INCLUDE "gfx/pokemon/exeggcute/anim_idle.asm"
LickitungAnimationExtra:  INCLUDE "gfx/pokemon/lickitung/anim_idle.asm"
KoffingAnimationExtra:    INCLUDE "gfx/pokemon/koffing/anim_idle.asm"
TangelaAnimationExtra:    INCLUDE "gfx/pokemon/tangela/anim_idle.asm"
KangaskhanAnimationExtra: INCLUDE "gfx/pokemon/kangaskhan/anim_idle.asm"
HorseaAnimationExtra:     INCLUDE "gfx/pokemon/horsea/anim_idle.asm"
SeadraAnimationExtra:     INCLUDE "gfx/pokemon/seadra/anim_idle.asm"
StaryuAnimationExtra:     INCLUDE "gfx/pokemon/staryu/anim_idle.asm"
StarmieAnimationExtra:    INCLUDE "gfx/pokemon/starmie/anim_idle.asm"
ScytherAnimationExtra:    INCLUDE "gfx/pokemon/scyther/anim_idle.asm"
ElectabuzzAnimationExtra: INCLUDE "gfx/pokemon/electabuzz/anim_idle.asm"
MagmarAnimationExtra:     INCLUDE "gfx/pokemon/magmar/anim_idle.asm"
PinsirAnimationExtra:     INCLUDE "gfx/pokemon/pinsir/anim_idle.asm"
LaprasAnimationExtra:     INCLUDE "gfx/pokemon/lapras/anim_idle.asm"
DittoAnimationExtra:      INCLUDE "gfx/pokemon/ditto/anim_idle.asm"
EeveeAnimationExtra:      INCLUDE "gfx/pokemon/eevee/anim_idle.asm"
VaporeonAnimationExtra:   INCLUDE "gfx/pokemon/vaporeon/anim_idle.asm"
JolteonAnimationExtra:    INCLUDE "gfx/pokemon/jolteon/anim_idle.asm"
FlareonAnimationExtra:    INCLUDE "gfx/pokemon/flareon/anim_idle.asm"
SnorlaxAnimationExtra:    INCLUDE "gfx/pokemon/snorlax/anim_idle.asm"
DratiniAnimationExtra:    INCLUDE "gfx/pokemon/dratini/anim_idle.asm"
DragonairAnimationExtra:  INCLUDE "gfx/pokemon/dragonair/anim_idle.asm"
DragoniteAnimationExtra:  INCLUDE "gfx/pokemon/dragonite/anim_idle.asm"
CrobatAnimationExtra:     INCLUDE "gfx/pokemon/crobat/anim_idle.asm"
ChinchouAnimationExtra:   INCLUDE "gfx/pokemon/chinchou/anim_idle.asm"
LanturnAnimationExtra:    INCLUDE "gfx/pokemon/lanturn/anim_idle.asm"
CleffaAnimationExtra:     INCLUDE "gfx/pokemon/cleffa/anim_idle.asm"
IgglybuffAnimationExtra:  INCLUDE "gfx/pokemon/igglybuff/anim_idle.asm"
TogepiAnimationExtra:     INCLUDE "gfx/pokemon/togepi/anim_idle.asm"
TogeticAnimationExtra:    INCLUDE "gfx/pokemon/togetic/anim_idle.asm"
MareepAnimationExtra:     INCLUDE "gfx/pokemon/mareep/anim_idle.asm"
FlaaffyAnimationExtra:    INCLUDE "gfx/pokemon/flaaffy/anim_idle.asm"
AmpharosAnimationExtra:   INCLUDE "gfx/pokemon/ampharos/anim_idle.asm"
SudowoodoAnimationExtra:  INCLUDE "gfx/pokemon/sudowoodo/anim_idle.asm"
MarillAnimationExtra:     INCLUDE "gfx/pokemon/marill/anim_idle.asm"
AzumarillAnimationExtra:  INCLUDE "gfx/pokemon/azumarill/anim_idle.asm"
PolitoedAnimationExtra:   INCLUDE "gfx/pokemon/politoed/anim_idle.asm"
SunkernAnimationExtra:    INCLUDE "gfx/pokemon/sunkern/anim_idle.asm"
SunfloraAnimationExtra:   INCLUDE "gfx/pokemon/sunflora/anim_idle.asm"
YanmaAnimationExtra:      INCLUDE "gfx/pokemon/yanma/anim_idle.asm"
EspeonAnimationExtra:     INCLUDE "gfx/pokemon/espeon/anim_idle.asm"
UmbreonAnimationExtra:    INCLUDE "gfx/pokemon/umbreon/anim_idle.asm"
MurkrowAnimationExtra:    INCLUDE "gfx/pokemon/murkrow/anim_idle.asm"
MisdreavusAnimationExtra: INCLUDE "gfx/pokemon/misdreavus/anim_idle.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim_idle.asm"
GligarAnimationExtra:     INCLUDE "gfx/pokemon/gligar/anim_idle.asm"
SteelixAnimationExtra:    INCLUDE "gfx/pokemon/steelix/anim_idle.asm"
SnubbullAnimationExtra:   INCLUDE "gfx/pokemon/snubbull/anim_idle.asm"
GranbullAnimationExtra:   INCLUDE "gfx/pokemon/granbull/anim_idle.asm"
ScizorAnimationExtra:     INCLUDE "gfx/pokemon/scizor/anim_idle.asm"
ShuckleAnimationExtra:    INCLUDE "gfx/pokemon/shuckle/anim_idle.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim_idle.asm"
SwinubAnimationExtra:     INCLUDE "gfx/pokemon/swinub/anim_idle.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim_idle.asm"
RemoraidAnimationExtra:   INCLUDE "gfx/pokemon/remoraid/anim_idle.asm"
OctilleryAnimationExtra:  INCLUDE "gfx/pokemon/octillery/anim_idle.asm"
DelibirdAnimationExtra:   INCLUDE "gfx/pokemon/delibird/anim_idle.asm"
MantineAnimationExtra:    INCLUDE "gfx/pokemon/mantine/anim_idle.asm"
SkarmoryAnimationExtra:   INCLUDE "gfx/pokemon/skarmory/anim_idle.asm"
HoundourAnimationExtra:   INCLUDE "gfx/pokemon/houndour/anim_idle.asm"
HoundoomAnimationExtra:   INCLUDE "gfx/pokemon/houndoom/anim_idle.asm"
KingdraAnimationExtra:    INCLUDE "gfx/pokemon/kingdra/anim_idle.asm"
ElekidAnimationExtra:     INCLUDE "gfx/pokemon/elekid/anim_idle.asm"
MagbyAnimationExtra:      INCLUDE "gfx/pokemon/magby/anim_idle.asm"
LarvitarAnimationExtra:   INCLUDE "gfx/pokemon/larvitar/anim_idle.asm"
PupitarAnimationExtra:    INCLUDE "gfx/pokemon/pupitar/anim_idle.asm"
TyranitarAnimationExtra:  INCLUDE "gfx/pokemon/tyranitar/anim_idle.asm"
LotadAnimationExtra:      INCLUDE "gfx/pokemon/lotad/anim_idle.asm"
LombreAnimationExtra:     INCLUDE "gfx/pokemon/lombre/anim_idle.asm"
LudicoloAnimationExtra:   INCLUDE "gfx/pokemon/ludicolo/anim_idle.asm"
SeedotAnimationExtra:     INCLUDE "gfx/pokemon/seedot/anim_idle.asm"
NuzleafAnimationExtra:    INCLUDE "gfx/pokemon/nuzleaf/anim_idle.asm"
ShiftryAnimationExtra:    INCLUDE "gfx/pokemon/shiftry/anim_idle.asm"
WingullAnimationExtra:    INCLUDE "gfx/pokemon/wingull/anim_idle.asm"
PelipperAnimationExtra:   INCLUDE "gfx/pokemon/pelipper/anim_idle.asm"
RaltsAnimationExtra:      INCLUDE "gfx/pokemon/ralts/anim_idle.asm"
KirliaAnimationExtra:     INCLUDE "gfx/pokemon/kirlia/anim_idle.asm"
GardevoirAnimationExtra:  INCLUDE "gfx/pokemon/gardevoir/anim_idle.asm"
ShroomishAnimationExtra:  INCLUDE "gfx/pokemon/shroomish/anim_idle.asm"
BreloomAnimationExtra:    INCLUDE "gfx/pokemon/breloom/anim_idle.asm"
AzurillAnimationExtra:    INCLUDE "gfx/pokemon/azurill/anim_idle.asm"
NosepassAnimationExtra:   INCLUDE "gfx/pokemon/nosepass/anim_idle.asm"
MawileAnimationExtra:     INCLUDE "gfx/pokemon/mawile/anim_idle.asm"
AronAnimationExtra:       INCLUDE "gfx/pokemon/aron/anim_idle.asm"
LaironAnimationExtra:     INCLUDE "gfx/pokemon/lairon/anim_idle.asm"
AggronAnimationExtra:     INCLUDE "gfx/pokemon/aggron/anim_idle.asm"
MedititeAnimationExtra:   INCLUDE "gfx/pokemon/meditite/anim_idle.asm"
MedichamAnimationExtra:   INCLUDE "gfx/pokemon/medicham/anim_idle.asm"
RoseliaAnimationExtra:    INCLUDE "gfx/pokemon/roselia/anim_idle.asm"
NumelAnimationExtra:      INCLUDE "gfx/pokemon/numel/anim_idle.asm"
CameruptAnimationExtra:   INCLUDE "gfx/pokemon/camerupt/anim_idle.asm"
TrapinchAnimationExtra:   INCLUDE "gfx/pokemon/trapinch/anim_idle.asm"
VibravaAnimationExtra:    INCLUDE "gfx/pokemon/vibrava/anim_idle.asm"
FlygonAnimationExtra:     INCLUDE "gfx/pokemon/flygon/anim_idle.asm"
SwabluAnimationExtra:     INCLUDE "gfx/pokemon/swablu/anim_idle.asm"
AltariaAnimationExtra:    INCLUDE "gfx/pokemon/altaria/anim_idle.asm"
CorphishAnimationExtra:   INCLUDE "gfx/pokemon/corphish/anim_idle.asm"
CrawdauntAnimationExtra:  INCLUDE "gfx/pokemon/crawdaunt/anim_idle.asm"
BaltoyAnimationExtra:     INCLUDE "gfx/pokemon/baltoy/anim_idle.asm"
ClaydolAnimationExtra:    INCLUDE "gfx/pokemon/claydol/anim_idle.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim_idle.asm"
HonchkrowAnimationExtra:  INCLUDE "gfx/pokemon/honchkrow/anim_idle.asm"
BonslyAnimationExtra:     INCLUDE "gfx/pokemon/bonsly/anim_idle.asm"
MimeJrAnimationExtra:     INCLUDE "gfx/pokemon/mime_jr_/anim_idle.asm"
MunchlaxAnimationExtra:   INCLUDE "gfx/pokemon/munchlax/anim_idle.asm"
MantykeAnimationExtra:    INCLUDE "gfx/pokemon/mantyke/anim_idle.asm"
WeavileAnimationExtra:    INCLUDE "gfx/pokemon/weavile/anim_idle.asm"
MagnezoneAnimationExtra:  INCLUDE "gfx/pokemon/magnezone/anim_idle.asm"
LickilickyAnimationExtra: INCLUDE "gfx/pokemon/lickilicky/anim_idle.asm"
TangrowthAnimationExtra:  INCLUDE "gfx/pokemon/tangrowth/anim_idle.asm"
ElectivireAnimationExtra: INCLUDE "gfx/pokemon/electivire/anim_idle.asm"
MagmortarAnimationExtra:  INCLUDE "gfx/pokemon/magmortar/anim_idle.asm"
TogekissAnimationExtra:   INCLUDE "gfx/pokemon/togekiss/anim_idle.asm"
YanmegaAnimationExtra:    INCLUDE "gfx/pokemon/yanmega/anim_idle.asm"
LeafeonAnimationExtra:    INCLUDE "gfx/pokemon/leafeon/anim_idle.asm"
GlaceonAnimationExtra:    INCLUDE "gfx/pokemon/glaceon/anim_idle.asm"
GliscorAnimationExtra:    INCLUDE "gfx/pokemon/gliscor/anim_idle.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim_idle.asm"
SylveonAnimationExtra:    INCLUDE "gfx/pokemon/sylveon/anim_idle.asm"
PerrserkerAnimationExtra: INCLUDE "gfx/pokemon/perrserker/anim_idle.asm"
CursolaAnimationExtra:    INCLUDE "gfx/pokemon/cursola/anim_idle.asm"
MrRimeAnimationExtra:     INCLUDE "gfx/pokemon/mr__rime/anim_idle.asm"
KleavorAnimationExtra:    INCLUDE "gfx/pokemon/kleavor/anim_idle.asm"
SneaslerAnimationExtra:   INCLUDE "gfx/pokemon/sneasler/anim_idle.asm"
AnnihilapeAnimationExtra: INCLUDE "gfx/pokemon/annihilape/anim_idle.asm"
VictiniAnimationExtra:    INCLUDE "gfx/pokemon/victini/anim_idle.asm"
SnivyAnimationExtra:      INCLUDE "gfx/pokemon/snivy/anim_idle.asm"
ServineAnimationExtra:    INCLUDE "gfx/pokemon/servine/anim_idle.asm"
SerperiorAnimationExtra:  INCLUDE "gfx/pokemon/serperior/anim_idle.asm"
TepigAnimationExtra:      INCLUDE "gfx/pokemon/tepig/anim_idle.asm"
PigniteAnimationExtra:    INCLUDE "gfx/pokemon/pignite/anim_idle.asm"
EmboarAnimationExtra:     INCLUDE "gfx/pokemon/emboar/anim_idle.asm"
OshawottAnimationExtra:   INCLUDE "gfx/pokemon/oshawott/anim_idle.asm"
DewottAnimationExtra:     INCLUDE "gfx/pokemon/dewott/anim_idle.asm"
PatratAnimationExtra:     INCLUDE "gfx/pokemon/patrat/anim_idle.asm"
WatchogAnimationExtra:    INCLUDE "gfx/pokemon/watchog/anim_idle.asm"
LillipupAnimationExtra:   INCLUDE "gfx/pokemon/lillipup/anim_idle.asm"
HerdierAnimationExtra:    INCLUDE "gfx/pokemon/herdier/anim_idle.asm"
StoutlandAnimationExtra:  INCLUDE "gfx/pokemon/stoutland/anim_idle.asm"
PurrloinAnimationExtra:   INCLUDE "gfx/pokemon/purrloin/anim_idle.asm"
LiepardAnimationExtra:    INCLUDE "gfx/pokemon/liepard/anim_idle.asm"
PansageAnimationExtra:    INCLUDE "gfx/pokemon/pansage/anim_idle.asm"
SimisageAnimationExtra:   INCLUDE "gfx/pokemon/simisage/anim_idle.asm"
PansearAnimationExtra:    INCLUDE "gfx/pokemon/pansear/anim_idle.asm"
SimisearAnimationExtra:   INCLUDE "gfx/pokemon/simisear/anim_idle.asm"
PanpourAnimationExtra:    INCLUDE "gfx/pokemon/panpour/anim_idle.asm"
SimipourAnimationExtra:   INCLUDE "gfx/pokemon/simipour/anim_idle.asm"
MunnaAnimationExtra:      INCLUDE "gfx/pokemon/munna/anim_idle.asm"
MusharnaAnimationExtra:   INCLUDE "gfx/pokemon/musharna/anim_idle.asm"
PidoveAnimationExtra:     INCLUDE "gfx/pokemon/pidove/anim_idle.asm"
TranquillAnimationExtra:  INCLUDE "gfx/pokemon/tranquill/anim_idle.asm"
BlitzleAnimationExtra:    INCLUDE "gfx/pokemon/blitzle/anim_idle.asm"
ZebstrikaAnimationExtra:  INCLUDE "gfx/pokemon/zebstrika/anim_idle.asm"
RoggenrolaAnimationExtra: INCLUDE "gfx/pokemon/roggenrola/anim_idle.asm"
BoldoreAnimationExtra:    INCLUDE "gfx/pokemon/boldore/anim_idle.asm"
GigalithAnimationExtra:   INCLUDE "gfx/pokemon/gigalith/anim_idle.asm"
WoobatAnimationExtra:     INCLUDE "gfx/pokemon/woobat/anim_idle.asm"
SwoobatAnimationExtra:    INCLUDE "gfx/pokemon/swoobat/anim_idle.asm"
DrilburAnimationExtra:    INCLUDE "gfx/pokemon/drilbur/anim_idle.asm"
ExcadrillAnimationExtra:  INCLUDE "gfx/pokemon/excadrill/anim_idle.asm"
AudinoAnimationExtra:     INCLUDE "gfx/pokemon/audino/anim_idle.asm"
TimburrAnimationExtra:    INCLUDE "gfx/pokemon/timburr/anim_idle.asm"
GurdurrAnimationExtra:    INCLUDE "gfx/pokemon/gurdurr/anim_idle.asm"
ConkeldurrAnimationExtra: INCLUDE "gfx/pokemon/conkeldurr/anim_idle.asm"
TympoleAnimationExtra:    INCLUDE "gfx/pokemon/tympole/anim_idle.asm"
PalpitoadAnimationExtra:  INCLUDE "gfx/pokemon/palpitoad/anim_idle.asm"
SeismitoadAnimationExtra: INCLUDE "gfx/pokemon/seismitoad/anim_idle.asm"
ThrohAnimationExtra:      INCLUDE "gfx/pokemon/throh/anim_idle.asm"
SawkAnimationExtra:       INCLUDE "gfx/pokemon/sawk/anim_idle.asm"
SewaddleAnimationExtra:   INCLUDE "gfx/pokemon/sewaddle/anim_idle.asm"
SwadloonAnimationExtra:   INCLUDE "gfx/pokemon/swadloon/anim_idle.asm"
LeavannyAnimationExtra:   INCLUDE "gfx/pokemon/leavanny/anim_idle.asm"
VenipedeAnimationExtra:   INCLUDE "gfx/pokemon/venipede/anim_idle.asm"
WhirlipedeAnimationExtra: INCLUDE "gfx/pokemon/whirlipede/anim_idle.asm"
ScolipedeAnimationExtra:  INCLUDE "gfx/pokemon/scolipede/anim_idle.asm"
CottoneeAnimationExtra:   INCLUDE "gfx/pokemon/cottonee/anim_idle.asm"
WhimsicottAnimationExtra: INCLUDE "gfx/pokemon/whimsicott/anim_idle.asm"
PetililAnimationExtra:    INCLUDE "gfx/pokemon/petilil/anim_idle.asm"
SandileAnimationExtra:    INCLUDE "gfx/pokemon/sandile/anim_idle.asm"
KrokorokAnimationExtra:   INCLUDE "gfx/pokemon/krokorok/anim_idle.asm"
KrookodileAnimationExtra: INCLUDE "gfx/pokemon/krookodile/anim_idle.asm"
MaractusAnimationExtra:   INCLUDE "gfx/pokemon/maractus/anim_idle.asm"
DwebbleAnimationExtra:    INCLUDE "gfx/pokemon/dwebble/anim_idle.asm"
CrustleAnimationExtra:    INCLUDE "gfx/pokemon/crustle/anim_idle.asm"
ScraggyAnimationExtra:    INCLUDE "gfx/pokemon/scraggy/anim_idle.asm"
ScraftyAnimationExtra:    INCLUDE "gfx/pokemon/scrafty/anim_idle.asm"
SigilyphAnimationExtra:   INCLUDE "gfx/pokemon/sigilyph/anim_idle.asm"
CofagrigusAnimationExtra: INCLUDE "gfx/pokemon/cofagrigus/anim_idle.asm"
TirtougaAnimationExtra:   INCLUDE "gfx/pokemon/tirtouga/anim_idle.asm"
CarracostaAnimationExtra: INCLUDE "gfx/pokemon/carracosta/anim_idle.asm"
ArchenAnimationExtra:     INCLUDE "gfx/pokemon/archen/anim_idle.asm"
ArcheopsAnimationExtra:   INCLUDE "gfx/pokemon/archeops/anim_idle.asm"
TrubbishAnimationExtra:   INCLUDE "gfx/pokemon/trubbish/anim_idle.asm"
GarbodorAnimationExtra:   INCLUDE "gfx/pokemon/garbodor/anim_idle.asm"
MinccinoAnimationExtra:   INCLUDE "gfx/pokemon/minccino/anim_idle.asm"
CinccinoAnimationExtra:   INCLUDE "gfx/pokemon/cinccino/anim_idle.asm"
GothitaAnimationExtra:    INCLUDE "gfx/pokemon/gothita/anim_idle.asm"
GothoritaAnimationExtra:  INCLUDE "gfx/pokemon/gothorita/anim_idle.asm"
GothitelleAnimationExtra: INCLUDE "gfx/pokemon/gothitelle/anim_idle.asm"
SolosisAnimationExtra:    INCLUDE "gfx/pokemon/solosis/anim_idle.asm"
DuosionAnimationExtra:    INCLUDE "gfx/pokemon/duosion/anim_idle.asm"
ReuniclusAnimationExtra:  INCLUDE "gfx/pokemon/reuniclus/anim_idle.asm"
DucklettAnimationExtra:   INCLUDE "gfx/pokemon/ducklett/anim_idle.asm"
SwannaAnimationExtra:     INCLUDE "gfx/pokemon/swanna/anim_idle.asm"
VanilliteAnimationExtra:  INCLUDE "gfx/pokemon/vanillite/anim_idle.asm"
VanillishAnimationExtra:  INCLUDE "gfx/pokemon/vanillish/anim_idle.asm"
VanilluxeAnimationExtra:  INCLUDE "gfx/pokemon/vanilluxe/anim_idle.asm"
EmolgaAnimationExtra:     INCLUDE "gfx/pokemon/emolga/anim_idle.asm"
KarrablastAnimationExtra: INCLUDE "gfx/pokemon/karrablast/anim_idle.asm"
EscavalierAnimationExtra: INCLUDE "gfx/pokemon/escavalier/anim_idle.asm"
FoongusAnimationExtra:    INCLUDE "gfx/pokemon/foongus/anim_idle.asm"
AmoongussAnimationExtra:  INCLUDE "gfx/pokemon/amoonguss/anim_idle.asm"
AlomomolaAnimationExtra:  INCLUDE "gfx/pokemon/alomomola/anim_idle.asm"
JoltikAnimationExtra:     INCLUDE "gfx/pokemon/joltik/anim_idle.asm"
GalvantulaAnimationExtra: INCLUDE "gfx/pokemon/galvantula/anim_idle.asm"
FerroseedAnimationExtra:  INCLUDE "gfx/pokemon/ferroseed/anim_idle.asm"
FerrothornAnimationExtra: INCLUDE "gfx/pokemon/ferrothorn/anim_idle.asm"
KlinkAnimationExtra:      INCLUDE "gfx/pokemon/klink/anim_idle.asm"
KlangAnimationExtra:      INCLUDE "gfx/pokemon/klang/anim_idle.asm"
KlinklangAnimationExtra:  INCLUDE "gfx/pokemon/klinklang/anim_idle.asm"
TynamoAnimationExtra:     INCLUDE "gfx/pokemon/tynamo/anim_idle.asm"
EelektrikAnimationExtra:  INCLUDE "gfx/pokemon/eelektrik/anim_idle.asm"
EelektrossAnimationExtra: INCLUDE "gfx/pokemon/eelektross/anim_idle.asm"
ElgyemAnimationExtra:     INCLUDE "gfx/pokemon/elgyem/anim_idle.asm"
BeheeyemAnimationExtra:   INCLUDE "gfx/pokemon/beheeyem/anim_idle.asm"
LitwickAnimationExtra:    INCLUDE "gfx/pokemon/litwick/anim_idle.asm"
LampentAnimationExtra:    INCLUDE "gfx/pokemon/lampent/anim_idle.asm"
ChandelureAnimationExtra: INCLUDE "gfx/pokemon/chandelure/anim_idle.asm"
AxewAnimationExtra:       INCLUDE "gfx/pokemon/axew/anim_idle.asm"
FraxureAnimationExtra:    INCLUDE "gfx/pokemon/fraxure/anim_idle.asm"
HaxorusAnimationExtra:    INCLUDE "gfx/pokemon/haxorus/anim_idle.asm"
CubchooAnimationExtra:    INCLUDE "gfx/pokemon/cubchoo/anim_idle.asm"
BearticAnimationExtra:    INCLUDE "gfx/pokemon/beartic/anim_idle.asm"
CryogonalAnimationExtra:  INCLUDE "gfx/pokemon/cryogonal/anim_idle.asm"
ShelmetAnimationExtra:    INCLUDE "gfx/pokemon/shelmet/anim_idle.asm"
AccelgorAnimationExtra:   INCLUDE "gfx/pokemon/accelgor/anim_idle.asm"
MienfooAnimationExtra:    INCLUDE "gfx/pokemon/mienfoo/anim_idle.asm"
MienshaoAnimationExtra:   INCLUDE "gfx/pokemon/mienshao/anim_idle.asm"
DruddigonAnimationExtra:  INCLUDE "gfx/pokemon/druddigon/anim_idle.asm"
GolettAnimationExtra:     INCLUDE "gfx/pokemon/golett/anim_idle.asm"
GolurkAnimationExtra:     INCLUDE "gfx/pokemon/golurk/anim_idle.asm"
PawniardAnimationExtra:   INCLUDE "gfx/pokemon/pawniard/anim_idle.asm"
BisharpAnimationExtra:    INCLUDE "gfx/pokemon/bisharp/anim_idle.asm"
BouffalantAnimationExtra: INCLUDE "gfx/pokemon/bouffalant/anim_idle.asm"
RuffletAnimationExtra:    INCLUDE "gfx/pokemon/rufflet/anim_idle.asm"
VullabyAnimationExtra:    INCLUDE "gfx/pokemon/vullaby/anim_idle.asm"
MandibuzzAnimationExtra:  INCLUDE "gfx/pokemon/mandibuzz/anim_idle.asm"
HeatmorAnimationExtra:    INCLUDE "gfx/pokemon/heatmor/anim_idle.asm"
DurantAnimationExtra:     INCLUDE "gfx/pokemon/durant/anim_idle.asm"
DeinoAnimationExtra:      INCLUDE "gfx/pokemon/deino/anim_idle.asm"
ZweilousAnimationExtra:   INCLUDE "gfx/pokemon/zweilous/anim_idle.asm"
HydreigonAnimationExtra:  INCLUDE "gfx/pokemon/hydreigon/anim_idle.asm"
LarvestaAnimationExtra:   INCLUDE "gfx/pokemon/larvesta/anim_idle.asm"
VolcaronaAnimationExtra:  INCLUDE "gfx/pokemon/volcarona/anim_idle.asm"
CobalionAnimationExtra:   INCLUDE "gfx/pokemon/cobalion/anim_idle.asm"
TerrakionAnimationExtra:  INCLUDE "gfx/pokemon/terrakion/anim_idle.asm"
VirizionAnimationExtra:   INCLUDE "gfx/pokemon/virizion/anim_idle.asm"
ReshiramAnimationExtra:   INCLUDE "gfx/pokemon/reshiram/anim_idle.asm"
ZekromAnimationExtra:     INCLUDE "gfx/pokemon/zekrom/anim_idle.asm"
KeldeoAnimationExtra:     INCLUDE "gfx/pokemon/keldeo/anim_idle.asm"
GenesectAnimationExtra:   INCLUDE "gfx/pokemon/genesect/anim_idle.asm"
RunerigusAnimationExtra:  INCLUDE "gfx/pokemon/runerigus/anim_idle.asm"

EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim_idle.asm"

PichuPlainAnimationExtra: INCLUDE "gfx/pokemon/pichu_plain/anim_idle.asm"
PichuSpikyAnimationExtra: INCLUDE "gfx/pokemon/pichu_spiky/anim_idle.asm"

PikachuSparkAnimationExtra:
PikachuPlainAnimationExtra:  INCLUDE "gfx/pokemon/pikachu_plain/anim_idle.asm"
PikachuFlyAnimationExtra:    INCLUDE "gfx/pokemon/pikachu_fly/anim_idle.asm"
PikachuSurfAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_surf/anim_idle.asm"
PikachuPikaAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_pika/anim_idle.asm"
PikachuChuchuAnimationExtra: INCLUDE "gfx/pokemon/pikachu_chuchu/anim_idle.asm"

DudunsparceTwoSegmentAnimationExtra:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim_idle.asm"
DudunsparceThreeSegmentAnimationExtra: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim_idle.asm"

RattataPlainAnimationExtra:  INCLUDE "gfx/pokemon/rattata_plain/anim_idle.asm"
RattataAlolanAnimationExtra: INCLUDE "gfx/pokemon/rattata_alolan/anim_idle.asm"

RaticatePlainAnimationExtra:  INCLUDE "gfx/pokemon/raticate_plain/anim_idle.asm"
RaticateAlolanAnimationExtra: INCLUDE "gfx/pokemon/raticate_alolan/anim_idle.asm"

RaichuPlainAnimationExtra:  INCLUDE "gfx/pokemon/raichu_plain/anim_idle.asm"
RaichuAlolanAnimationExtra: INCLUDE "gfx/pokemon/raichu_alolan/anim_idle.asm"

SandshrewPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandshrew_plain/anim_idle.asm"
SandshrewAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandshrew_alolan/anim_idle.asm"

SandslashPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandslash_plain/anim_idle.asm"
SandslashAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandslash_alolan/anim_idle.asm"

VulpixPlainAnimationExtra:  INCLUDE "gfx/pokemon/vulpix_plain/anim_idle.asm"
VulpixAlolanAnimationExtra: INCLUDE "gfx/pokemon/vulpix_alolan/anim_idle.asm"

NinetalesPlainAnimationExtra:  INCLUDE "gfx/pokemon/ninetales_plain/anim_idle.asm"
NinetalesAlolanAnimationExtra: INCLUDE "gfx/pokemon/ninetales_alolan/anim_idle.asm"

MeowthPlainAnimationExtra:  INCLUDE "gfx/pokemon/meowth_plain/anim_idle.asm"
MeowthAlolanAnimationExtra: INCLUDE "gfx/pokemon/meowth_alolan/anim_idle.asm"
MeowthGalarianAnimationExtra: INCLUDE "gfx/pokemon/meowth_galarian/anim_idle.asm"

PersianPlainAnimationExtra:  INCLUDE "gfx/pokemon/persian_plain/anim_idle.asm"
PersianAlolanAnimationExtra: INCLUDE "gfx/pokemon/persian_alolan/anim_idle.asm"

GeodudePlainAnimationExtra:  INCLUDE "gfx/pokemon/geodude_plain/anim_idle.asm"
GeodudeAlolanAnimationExtra: INCLUDE "gfx/pokemon/geodude_alolan/anim_idle.asm"

GravelerPlainAnimationExtra:  INCLUDE "gfx/pokemon/graveler_plain/anim_idle.asm"
GravelerAlolanAnimationExtra: INCLUDE "gfx/pokemon/graveler_alolan/anim_idle.asm"

GolemPlainAnimationExtra:  INCLUDE "gfx/pokemon/golem_plain/anim_idle.asm"
GolemAlolanAnimationExtra: INCLUDE "gfx/pokemon/golem_alolan/anim_idle.asm"

GrimerPlainAnimationExtra:  INCLUDE "gfx/pokemon/grimer_plain/anim_idle.asm"
GrimerAlolanAnimationExtra: INCLUDE "gfx/pokemon/grimer_alolan/anim_idle.asm"

MukPlainAnimationExtra:  INCLUDE "gfx/pokemon/muk_plain/anim_idle.asm"
MukAlolanAnimationExtra: INCLUDE "gfx/pokemon/muk_alolan/anim_idle.asm"

ExeggutorPlainAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor_plain/anim_idle.asm"
ExeggutorAlolanAnimationExtra: INCLUDE "gfx/pokemon/exeggutor_alolan/anim_idle.asm"

PonytaPlainAnimationExtra:    INCLUDE "gfx/pokemon/ponyta_plain/anim_idle.asm"
PonytaGalarianAnimationExtra: INCLUDE "gfx/pokemon/ponyta_galarian/anim_idle.asm"

RapidashPlainAnimationExtra:    INCLUDE "gfx/pokemon/rapidash_plain/anim_idle.asm"
RapidashGalarianAnimationExtra: INCLUDE "gfx/pokemon/rapidash_galarian/anim_idle.asm"

SlowpokePlainAnimationExtra:   INCLUDE "gfx/pokemon/slowpoke_plain/anim_idle.asm"
SlowpokeGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowpoke_galarian/anim_idle.asm"

SlowbroPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowbro_plain/anim_idle.asm"
SlowbroGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowbro_galarian/anim_idle.asm"

WeezingPlainAnimationExtra:    INCLUDE "gfx/pokemon/weezing_plain/anim_idle.asm"
WeezingGalarianAnimationExtra: INCLUDE "gfx/pokemon/weezing_galarian/anim_idle.asm"

MrMimePlainAnimationExtra:    INCLUDE "gfx/pokemon/mr__mime_plain/anim_idle.asm"
MrMimeGalarianAnimationExtra: INCLUDE "gfx/pokemon/mr__mime_galarian/anim_idle.asm"

SlowkingPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowking_plain/anim_idle.asm"
SlowkingGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowking_galarian/anim_idle.asm"

CorsolaPlainAnimationExtra:    INCLUDE "gfx/pokemon/corsola_plain/anim_idle.asm"
CorsolaGalarianAnimationExtra: INCLUDE "gfx/pokemon/corsola_galarian/anim_idle.asm"

GrowlithePlainAnimationExtra:   INCLUDE "gfx/pokemon/growlithe_plain/anim_idle.asm"
GrowlitheHisuianAnimationExtra: INCLUDE "gfx/pokemon/growlithe_hisuian/anim_idle.asm"

ArcaninePlainAnimationExtra:   INCLUDE "gfx/pokemon/arcanine_plain/anim_idle.asm"
ArcanineHisuianAnimationExtra: INCLUDE "gfx/pokemon/arcanine_hisuian/anim_idle.asm"

SneaselPlainAnimationExtra:   INCLUDE "gfx/pokemon/sneasel_plain/anim_idle.asm"
SneaselHisuianAnimationExtra: INCLUDE "gfx/pokemon/sneasel_hisuian/anim_idle.asm"

UnfezantMaleAnimationExtra:   INCLUDE "gfx/pokemon/unfezant_male/anim_idle.asm"
UnfezantFemaleAnimationExtra: INCLUDE "gfx/pokemon/unfezant_female/anim_idle.asm"

SamurottPlainAnimationExtra: INCLUDE "gfx/pokemon/samurott_plain/anim_idle.asm"

LilligantPlainAnimationExtra: INCLUDE "gfx/pokemon/lilligant_plain/anim_idle.asm"

BasculinRedAnimationExtra:   INCLUDE "gfx/pokemon/basculin_red/anim_idle.asm"
BasculinBlueAnimationExtra:  INCLUDE "gfx/pokemon/basculin_blue/anim_idle.asm"
BasculinWhiteAnimationExtra: INCLUDE "gfx/pokemon/basculin_white/anim_idle.asm"

DarumakaPlainAnimationExtra:    INCLUDE "gfx/pokemon/darumaka_plain/anim_idle.asm"
DarumakaGalarianAnimationExtra: INCLUDE "gfx/pokemon/darumaka_galarian/anim_idle.asm"

DarmanitanPlainAnimationExtra:       INCLUDE "gfx/pokemon/darmanitan_plain/anim_idle.asm"
DarmanitanZenAnimationExtra:         INCLUDE "gfx/pokemon/darmanitan_zen/anim_idle.asm"
DarmanitanGalarianAnimationExtra:    INCLUDE "gfx/pokemon/darmanitan_galarian/anim_idle.asm"
DarmanitanGalarianZenAnimationExtra: INCLUDE "gfx/pokemon/darmanitan_galarian_zen/anim_idle.asm"

YamaskPlainAnimationExtra:    INCLUDE "gfx/pokemon/yamask_plain/anim_idle.asm"
YamaskGalarianAnimationExtra: INCLUDE "gfx/pokemon/yamask_galarian/anim_idle.asm"

ZoruaPlainAnimationExtra: INCLUDE "gfx/pokemon/zorua_plain/anim_idle.asm"

ZoroarkPlainAnimationExtra: INCLUDE "gfx/pokemon/zoroark_plain/anim_idle.asm"

DeerlingSpringAnimationExtra: INCLUDE "gfx/pokemon/deerling_spring/anim_idle.asm"
DeerlingSummerAnimationExtra: INCLUDE "gfx/pokemon/deerling_summer/anim_idle.asm"
DeerlingAutumnAnimationExtra: INCLUDE "gfx/pokemon/deerling_autumn/anim_idle.asm"
DeerlingWinterAnimationExtra: INCLUDE "gfx/pokemon/deerling_winter/anim_idle.asm"

SawsbuckSpringAnimationExtra: INCLUDE "gfx/pokemon/sawsbuck_spring/anim_idle.asm"
SawsbuckSummerAnimationExtra: INCLUDE "gfx/pokemon/sawsbuck_summer/anim_idle.asm"
SawsbuckAutumnAnimationExtra: INCLUDE "gfx/pokemon/sawsbuck_autumn/anim_idle.asm"
SawsbuckWinterAnimationExtra: INCLUDE "gfx/pokemon/sawsbuck_winter/anim_idle.asm"

FrillishMaleAnimationExtra:   INCLUDE "gfx/pokemon/frillish_male/anim_idle.asm"
FrillishFemaleAnimationExtra: INCLUDE "gfx/pokemon/frillish_female/anim_idle.asm"

JellicentMaleAnimationExtra:   INCLUDE "gfx/pokemon/jellicent_male/anim_idle.asm"
JellicentFemaleAnimationExtra: INCLUDE "gfx/pokemon/jellicent_female/anim_idle.asm"

StunfiskPlainAnimationExtra: INCLUDE "gfx/pokemon/stunfisk_plain/anim_idle.asm"

BraviaryPlainAnimationExtra: INCLUDE "gfx/pokemon/braviary_plain/anim_idle.asm"

TornadusPlainAnimationExtra:   INCLUDE "gfx/pokemon/tornadus_plain/anim_idle.asm"
TornadusTherianAnimationExtra: INCLUDE "gfx/pokemon/tornadus_therian/anim_idle.asm"

ThundurusPlainAnimationExtra:   INCLUDE "gfx/pokemon/thundurus_plain/anim_idle.asm"
ThundurusTherianAnimationExtra: INCLUDE "gfx/pokemon/thundurus_therian/anim_idle.asm"

LandorusPlainAnimationExtra:   INCLUDE "gfx/pokemon/landorus_plain/anim_idle.asm"
LandorusTherianAnimationExtra: INCLUDE "gfx/pokemon/landorus_therian/anim_idle.asm"

KyuremPlainAnimationExtra: INCLUDE "gfx/pokemon/kyurem_plain/anim_idle.asm"
KyuremWhiteAnimationExtra: INCLUDE "gfx/pokemon/kyurem_white/anim_idle.asm"
KyuremBlackAnimationExtra: INCLUDE "gfx/pokemon/kyurem_black/anim_idle.asm"

MeloettaPlainAnimationExtra:     INCLUDE "gfx/pokemon/meloetta_plain/anim_idle.asm"
MeloettaPirouetteAnimationExtra: INCLUDE "gfx/pokemon/meloetta_pirouette/anim_idle.asm"
