AnimationExtraPointers:
	table_width 2
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw RattataPlainAnimationExtra
	dw RaticatePlainAnimationExtra
	dw EkansAnimationExtra
	dw ArbokJohtoAnimationExtra
	dw PikachuPlainAnimationExtra
	dw RaichuPlainAnimationExtra
	dw SandshrewPlainAnimationExtra
	dw SandslashPlainAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw VulpixPlainAnimationExtra
	dw NinetalesPlainAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw MeowthPlainAnimationExtra
	dw PersianPlainAnimationExtra
	dw PsyduckAnimationExtra
	dw GolduckAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlithePlainAnimationExtra
	dw ArcaninePlainAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw GeodudePlainAnimationExtra
	dw GravelerPlainAnimationExtra
	dw GolemPlainAnimationExtra
	dw PonytaPlainAnimationExtra
	dw RapidashPlainAnimationExtra
	dw SlowpokePlainAnimationExtra
	dw SlowbroPlainAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw SeelAnimationExtra
	dw DewgongAnimationExtra
	dw GrimerPlainAnimationExtra
	dw MukPlainAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorPlainAnimationExtra
	dw LickitungAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingPlainAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw MrMimePlainAnimationExtra
	dw ScytherAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw PinsirAnimationExtra
	dw MagikarpPlainAnimationExtra
	dw GyaradosPlainAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw SnorlaxAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw MewtwoPlainAnimationExtra
	dw MewAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionPlainAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuPlainAnimationExtra
	dw CleffaAnimationExtra
	dw IgglybuffAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw WooperPlainAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingPlainAnimationExtra
	dw MisdreavusAnimationExtra
	dw UnownAAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishPlainAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselPlainAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaPlainAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw DelibirdAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw AzurillAnimationExtra
	dw MismagiusAnimationExtra
	dw HonchkrowAnimationExtra
	dw BonslyAnimationExtra
	dw MimeJrAnimationExtra
	dw MunchlaxAnimationExtra
	dw MantykeAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw LickilickyAnimationExtra
	dw TangrowthAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw YanmegaAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw SylveonAnimationExtra
	dw PerrserkerAnimationExtra
	dw CursolaAnimationExtra
	dw MrRimeAnimationExtra
	dw KleavorAnimationExtra
	dw UrsalunaPlainAnimationExtra
	dw SneaslerAnimationExtra
	dw OverqwilAnimationExtra
	dw DudunsparceTwoSegmentAnimationExtra
	dw ClodsireAnimationExtra
	dw AnnihilapeAnimationExtra
	dw SnivyAnimationExtra
	dw ServineAnimationExtra
	dw SerperiorAnimationExtra
	dw TepigAnimationExtra
	dw PigniteAnimationExtra
	dw EmboarAnimationExtra
	dw OshawottAnimationExtra
	dw DewottAnimationExtra
	dw SamurottPlainAnimationExtra
	dw PatratAnimationExtra
	dw WatchogAnimationExtra
	dw LillipupAnimationExtra
	dw HerdierAnimationExtra
	dw StoutlandAnimationExtra
	dw PurrloinAnimationExtra
	dw LiepardAnimationExtra
	dw MunnaAnimationExtra
	dw MusharnaAnimationExtra
	dw PidoveAnimationExtra
	dw TranquillAnimationExtra
	dw UnfezantMaleAnimationExtra
	dw BlitzleAnimationExtra
	dw ZebstrikaAnimationExtra
	dw RoggenrolaAnimationExtra
	dw BoldoreAnimationExtra
	dw GigalithAnimationExtra
	dw WoobatAnimationExtra
	dw SwoobatAnimationExtra
	dw DrilburAnimationExtra
	dw ExcadrillAnimationExtra
	dw AudinoAnimationExtra
	dw TimburrAnimationExtra
	dw GurdurrAnimationExtra
	dw ConkeldurrAnimationExtra
	dw TympoleAnimationExtra
	dw PalpitoadAnimationExtra
	dw SeismitoadAnimationExtra
	dw ThrohAnimationExtra
	dw SawkAnimationExtra
	dw SewaddleAnimationExtra
	dw SwadloonAnimationExtra
	dw LeavannyAnimationExtra
	dw VenipedeAnimationExtra
	dw WhirlipedeAnimationExtra
	dw ScolipedeAnimationExtra
	dw CottoneeAnimationExtra
	dw WhimsicottAnimationExtra
	dw PetililAnimationExtra
	dw LilligantPlainAnimationExtra
	dw BasculinRedAnimationExtra ; BasculinWhiteAnimationExtra
	dw SandileAnimationExtra
	dw KrokorokAnimationExtra
	dw KrookodileAnimationExtra
	dw DarumakaPlainAnimationExtra
	dw DarmanitanPlainAnimationExtra
	dw MaractusAnimationExtra
	dw DwebbleAnimationExtra
	dw CrustleAnimationExtra
	dw ScraggyAnimationExtra
	dw ScraftyAnimationExtra
	dw SigilyphAnimationExtra
	dw YamaskPlainAnimationExtra
	dw CofagrigusAnimationExtra
	dw TirtougaAnimationExtra
	dw EggAnimationExtra
	dw EggAnimationExtra ; $100
	dw CarracostaAnimationExtra
	dw ArchenAnimationExtra
	dw ArcheopsAnimationExtra
	dw TrubbishAnimationExtra
	dw GarbodorAnimationExtra
	dw ZoruaPlainAnimationExtra
	dw ZoroarkPlainAnimationExtra
	dw GothitaAnimationExtra
	dw GothoritaAnimationExtra
	dw GothitelleAnimationExtra
	dw SolosisAnimationExtra
	dw DuosionAnimationExtra
	dw ReuniclusAnimationExtra
	dw DucklettAnimationExtra
	dw SwannaAnimationExtra
	dw VanilliteAnimationExtra
	dw VanillishAnimationExtra
	dw VanilluxeAnimationExtra
	dw DeerlingSpringAnimationExtra
	dw SawsbuckSpringAnimationExtra
	dw EmolgaAnimationExtra
	dw KarrablastAnimationExtra
	dw EscavalierAnimationExtra
	dw FoongusAnimationExtra
	dw AmoongussAnimationExtra
	dw FrillishMaleAnimationExtra
	dw JellicentMaleAnimationExtra
	dw JoltikAnimationExtra
	dw GalvantulaAnimationExtra
	dw FerroseedAnimationExtra
	dw FerrothornAnimationExtra
	dw KlinkAnimationExtra
	dw KlangAnimationExtra
	dw KlinklangAnimationExtra
	dw TynamoAnimationExtra
	dw EelektrikAnimationExtra
	dw EelektrossAnimationExtra
	dw LitwickAnimationExtra
	dw LampentAnimationExtra
	dw ChandelureAnimationExtra
	dw AxewAnimationExtra
	dw FraxureAnimationExtra
	dw HaxorusAnimationExtra
	dw CubchooAnimationExtra
	dw BearticAnimationExtra
	dw CryogonalAnimationExtra
	dw ShelmetAnimationExtra
	dw AccelgorAnimationExtra
	dw StunfiskPlainAnimationExtra
	dw GolettAnimationExtra
	dw GolurkAnimationExtra
	assert_table_length NUM_SPECIES

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw ArbokKantoAnimationExtra
	dw ArbokKogaAnimationExtra
	dw ArbokAgathaAnimationExtra
	dw ArbokArianaAnimationExtra

	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra
	dw PikachuSparkAnimationExtra

	dw PichuSpikyAnimationExtra

	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpDiamondsAnimationExtra
	dw MagikarpPatchesAnimationExtra
	dw MagikarpForehead1AnimationExtra
	dw MagikarpMask1AnimationExtra
	dw MagikarpForehead2AnimationExtra
	dw MagikarpMask2AnimationExtra
	dw MagikarpSaucyAnimationExtra
	dw MagikarpRaindropAnimationExtra

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw GyaradosRedAnimationExtra

	dw MewtwoArmoredAnimationExtra

	dw DudunsparceThreeSegmentAnimationExtra

	dw RattataAlolanAnimationExtra
	dw RaticateAlolanAnimationExtra
	dw RaichuAlolanAnimationExtra
	dw SandshrewAlolanAnimationExtra
	dw SandslashAlolanAnimationExtra
	dw VulpixAlolanAnimationExtra
	dw NinetalesAlolanAnimationExtra
	dw MeowthAlolanAnimationExtra
	dw PersianAlolanAnimationExtra
	dw GeodudeAlolanAnimationExtra
	dw GravelerAlolanAnimationExtra
	dw GolemAlolanAnimationExtra
	dw GrimerAlolanAnimationExtra
	dw MukAlolanAnimationExtra
	dw ExeggutorAlolanAnimationExtra

	dw MeowthGalarianAnimationExtra
	dw PonytaGalarianAnimationExtra
	dw RapidashGalarianAnimationExtra
	dw SlowpokeGalarianAnimationExtra
	dw SlowbroGalarianAnimationExtra
	dw WeezingGalarianAnimationExtra
	dw MrMimeGalarianAnimationExtra
	dw SlowkingGalarianAnimationExtra
	dw CorsolaGalarianAnimationExtra

	dw GrowlitheHisuianAnimationExtra
	dw ArcanineHisuianAnimationExtra
	dw TyphlosionHisuianAnimationExtra
	dw QwilfishHisuianAnimationExtra
	dw SneaselHisuianAnimationExtra

	dw WooperPaldeanAnimationExtra

	dw UrsalunaBloodmoonAnimationExtra
	
	dw UnfezantFemaleAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
