FramesPointers:
	table_width 2
	dw RattataPlainFrames
	dw RaticatePlainFrames
	dw PikachuPlainFrames
	dw RaichuPlainFrames
	dw SandshrewPlainFrames
	dw SandslashPlainFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixPlainFrames
	dw NinetalesPlainFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw ParasFrames
	dw ParasectFrames
	dw MeowthPlainFrames
	dw PersianPlainFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlithePlainFrames
	dw ArcaninePlainFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw GeodudePlainFrames
	dw GravelerPlainFrames
	dw GolemPlainFrames
	dw PonytaPlainFrames
	dw RapidashPlainFrames
	dw SlowpokePlainFrames
	dw SlowbroPlainFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerPlainFrames
	dw MukPlainFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw ExeggcuteFrames
	dw ExeggutorPlainFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingPlainFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimePlainFrames
	dw ScytherFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw SnorlaxFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuPlainFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingPlainFrames
	dw MisdreavusFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselPlainFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaPlainFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw ElekidFrames
	dw MagbyFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LotadFrames
	dw LombreFrames
	dw LudicoloFrames
	dw SeedotFrames
	dw NuzleafFrames
	dw ShiftryFrames
	dw WingullFrames
	dw PelipperFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw SlakothFrames
	dw VigorothFrames
	dw SlakingFrames
	dw AzurillFrames
	dw NosepassFrames
	dw SkittyFrames
	dw DelcattyFrames
	dw SableyeFrames
	dw MawileFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw MedititeFrames
	dw MedichamFrames
	dw RoseliaFrames
	dw WailmerFrames
	dw WailordFrames
	dw NumelFrames
	dw CameruptFrames
	dw TorkoalFrames
	dw SpoinkFrames
	dw GrumpigFrames
	dw TrapinchFrames
	dw VibravaFrames
	dw FlygonFrames
	dw SwabluFrames
	dw AltariaFrames
	dw ZangooseFrames
	dw SeviperFrames
	dw LunatoneFrames
	dw SolrockFrames
	dw CorphishFrames
	dw CrawdauntFrames
	dw BaltoyFrames
	dw ClaydolFrames
	dw CastformPlainFrames
	dw ShuppetFrames
	dw BanetteFrames
	dw TropiusFrames
	dw AbsolFrames
	dw SnoruntFrames
	dw GlalieFrames
	dw SphealFrames
	dw SealeoFrames
	dw WalreinFrames
	dw BagonFrames
	dw ShelgonFrames
	dw SalamenceFrames
	dw BeldumFrames
	dw MetangFrames
	dw MetagrossFrames
	dw StarlyFrames
	dw StaraviaFrames
	dw StaraptorFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw BudewFrames
	dw RoseradeFrames
	dw CombeeFemaleFrames
	dw VespiquenFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw MismagiusFrames
	dw HonchkrowFrames
	dw BonslyFrames
	dw MimeJrFrames
	dw MunchlaxFrames
	dw MantykeFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw LickilickyFrames
	dw TangrowthFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw YanmegaFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw GliscorFrames
	dw MamoswineFrames
	dw VictiniFrames
	dw SnivyFrames
	dw ServineFrames
	dw SerperiorFrames
	dw TepigFrames
	dw PigniteFrames
	dw EmboarFrames
	dw OshawottFrames
	dw DewottFrames
	dw SamurottPlainFrames
	dw PatratFrames
	dw WatchogFrames
	dw LillipupFrames
	dw HerdierFrames
	dw StoutlandFrames
	dw PurrloinFrames
	dw LiepardFrames
	dw PansageFrames
	dw SimisageFrames
	dw PansearFrames
	dw SimisearFrames
	dw PanpourFrames
	dw SimipourFrames
	dw MunnaFrames
	dw MusharnaFrames
	dw PidoveFrames
	dw TranquillFrames
	dw UnfezantMaleFrames
	dw BlitzleFrames
	dw ZebstrikaFrames
	dw RoggenrolaFrames
	dw BoldoreFrames
	dw GigalithFrames
	dw WoobatFrames
	dw SwoobatFrames
	dw DrilburFrames
	dw EggFrames
	dw EggFrames ; $100
	dw ExcadrillFrames
	dw AudinoFrames
	dw TimburrFrames
	dw GurdurrFrames
	dw ConkeldurrFrames
	dw TympoleFrames
	dw PalpitoadFrames
	dw SeismitoadFrames
	dw ThrohFrames
	dw SawkFrames
	dw SewaddleFrames
	dw SwadloonFrames
	dw LeavannyFrames
	dw VenipedeFrames
	dw WhirlipedeFrames
	dw ScolipedeFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw PetililFrames
	dw LilligantPlainFrames
	dw BasculinWhiteFrames
	dw SandileFrames
	dw KrokorokFrames
	dw KrookodileFrames
	dw DarumakaPlainFrames
	dw DarmanitanPlainFrames
	dw MaractusFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw ScraggyFrames
	dw ScraftyFrames
	dw SigilyphFrames
	dw YamaskPlainFrames
	dw CofagrigusFrames
	dw TirtougaFrames
	dw CarracostaFrames
	dw ArchenFrames
	dw ArcheopsFrames
	dw TrubbishFrames
	dw GarbodorFrames
	dw ZoruaPlainFrames
	dw ZoroarkPlainFrames
	dw MinccinoFrames
	dw CinccinoFrames
	dw GothitaFrames
	dw GothoritaFrames
	dw GothitelleFrames
	dw SolosisFrames
	dw DuosionFrames
	dw ReuniclusFrames
	dw DucklettFrames
	dw SwannaFrames
	dw VanilliteFrames
	dw VanillishFrames
	dw VanilluxeFrames
	dw DeerlingSpringFrames
	dw SawsbuckSpringFrames
	dw EmolgaFrames
	dw KarrablastFrames
	dw EscavalierFrames
	dw FoongusFrames
	dw AmoongussFrames
	dw FrillishMaleFrames
	dw JellicentMaleFrames
	dw AlomomolaFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw FerroseedFrames
	dw FerrothornFrames
	dw KlinkFrames
	dw KlangFrames
	dw KlinklangFrames
	dw TynamoFrames
	dw EelektrikFrames
	dw EelektrossFrames
	dw ElgyemFrames
	dw BeheeyemFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw AxewFrames
	dw FraxureFrames
	dw HaxorusFrames
	dw CubchooFrames
	dw BearticFrames
	dw CryogonalFrames
	dw ShelmetFrames
	dw AccelgorFrames
	dw StunfiskPlainFrames
	dw MienfooFrames
	dw MienshaoFrames
	dw DruddigonFrames
	dw GolettFrames
	dw GolurkFrames
	dw PawniardFrames
	dw BisharpFrames
	dw BouffalantFrames
	dw RuffletFrames
	dw BraviaryPlainFrames
	dw VullabyFrames
	dw MandibuzzFrames
	dw HeatmorFrames
	dw DurantFrames
	dw DeinoFrames
	dw ZweilousFrames
	dw HydreigonFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw CobalionFrames
	dw TerrakionFrames
	dw VirizionFrames
	dw TornadusPlainFrames
	dw ThundurusPlainFrames
	dw ReshiramFrames
	dw ZekromFrames
	dw LandorusPlainFrames
	dw KyuremPlainFrames
	dw KeldeoFrames
	dw MeloettaPlainFrames
	dw GenesectFrames
	dw SylveonFrames
	dw PerrserkerFrames
	dw CursolaFrames
	dw MrRimeFrames
	dw RunerigusFrames
	dw KleavorFrames
	dw SneaslerFrames
	dw AnnihilapeFrames
	dw DudunsparceTwoSegmentFrames
	assert_table_length NUM_SPECIES

	dw PikachuFlyFrames
	dw PikachuSurfFrames
	dw PikachuPikaFrames
	dw PikachuChuchuFrames
	dw PikachuSparkFrames

	dw PichuSpikyFrames

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw DudunsparceThreeSegmentFrames

	dw RattataAlolanFrames
	dw RaticateAlolanFrames
	dw RaichuAlolanFrames
	dw SandshrewAlolanFrames
	dw SandslashAlolanFrames
	dw VulpixAlolanFrames
	dw NinetalesAlolanFrames
	dw MeowthAlolanFrames
	dw PersianAlolanFrames
	dw GeodudeAlolanFrames
	dw GravelerAlolanFrames
	dw GolemAlolanFrames
	dw GrimerAlolanFrames
	dw MukAlolanFrames
	dw ExeggutorAlolanFrames

	dw MeowthGalarianFrames
	dw PonytaGalarianFrames
	dw RapidashGalarianFrames
	dw SlowpokeGalarianFrames
	dw SlowbroGalarianFrames
	dw WeezingGalarianFrames
	dw MrMimeGalarianFrames
	dw SlowkingGalarianFrames
	dw CorsolaGalarianFrames
	dw DarumakaGalarianFrames
	dw DarmanitanGalarianFrames
	dw YamaskGalarianFrames

	dw GrowlitheHisuianFrames
	dw ArcanineHisuianFrames
	dw SneaselHisuianFrames
	
	dw CastformSunFrames
	dw CastformRainFrames
	dw CastformHailFrames
	
	dw CombeeMaleFrames
	
	dw UnfezantFemaleFrames
	
	dw BasculinRedFrames
	dw BasculinBlueFrames
	
	dw DarmanitanZenFrames
	dw DarmanitanGalarianZenFrames
	
	dw DeerlingSummerFrames
	dw DeerlingAutumnFrames
	dw DeerlingWinterFrames
	
	dw SawsbuckSummerFrames
	dw SawsbuckAutumnFrames
	dw SawsbuckWinterFrames
	
	dw FrillishFemaleFrames
	dw JellicentFemaleFrames
	
	dw TornadusTherianFrames
	dw ThundurusTherianFrames
	dw LandorusTherianFrames
	
	dw KyuremWhiteFrames
	dw KyuremBlackFrames
	
	dw MeloettaPirouetteFrames

	assert_table_length NUM_UNIQUE_POKEMON
