JohtoFrames:

ChikoritaFrames:  INCLUDE "gfx/pokemon/chikorita/frames.asm"
BayleefFrames:    INCLUDE "gfx/pokemon/bayleef/frames.asm"
MeganiumFrames:   INCLUDE "gfx/pokemon/meganium/frames.asm"
CyndaquilFrames:  INCLUDE "gfx/pokemon/cyndaquil/frames.asm"
QuilavaFrames:    INCLUDE "gfx/pokemon/quilava/frames.asm"
TotodileFrames:   INCLUDE "gfx/pokemon/totodile/frames.asm"
CroconawFrames:   INCLUDE "gfx/pokemon/croconaw/frames.asm"
FeraligatrFrames: INCLUDE "gfx/pokemon/feraligatr/frames.asm"
CrobatFrames:     INCLUDE "gfx/pokemon/crobat/frames.asm"
ChinchouFrames:   INCLUDE "gfx/pokemon/chinchou/frames.asm"
LanturnFrames:    INCLUDE "gfx/pokemon/lanturn/frames.asm"
CleffaFrames:     INCLUDE "gfx/pokemon/cleffa/frames.asm"
IgglybuffFrames:  INCLUDE "gfx/pokemon/igglybuff/frames.asm"
TogepiFrames:     INCLUDE "gfx/pokemon/togepi/frames.asm"
TogeticFrames:    INCLUDE "gfx/pokemon/togetic/frames.asm"
MareepFrames:     INCLUDE "gfx/pokemon/mareep/frames.asm"
FlaaffyFrames:    INCLUDE "gfx/pokemon/flaaffy/frames.asm"
AmpharosFrames:   INCLUDE "gfx/pokemon/ampharos/frames.asm"
MarillFrames:     INCLUDE "gfx/pokemon/marill/frames.asm"
AzumarillFrames:  INCLUDE "gfx/pokemon/azumarill/frames.asm"
SudowoodoFrames:  INCLUDE "gfx/pokemon/sudowoodo/frames.asm"
PolitoedFrames:   INCLUDE "gfx/pokemon/politoed/frames.asm"
SunkernFrames:    INCLUDE "gfx/pokemon/sunkern/frames.asm"
SunfloraFrames:   INCLUDE "gfx/pokemon/sunflora/frames.asm"
YanmaFrames:      INCLUDE "gfx/pokemon/yanma/frames.asm"
QuagsireFrames:   INCLUDE "gfx/pokemon/quagsire/frames.asm"
EspeonFrames:     INCLUDE "gfx/pokemon/espeon/frames.asm"
UmbreonFrames:    INCLUDE "gfx/pokemon/umbreon/frames.asm"
MurkrowFrames:    INCLUDE "gfx/pokemon/murkrow/frames.asm"
MisdreavusFrames: INCLUDE "gfx/pokemon/misdreavus/frames.asm"
DunsparceFrames:  INCLUDE "gfx/pokemon/dunsparce/frames.asm"
GligarFrames:     INCLUDE "gfx/pokemon/gligar/frames.asm"
SteelixFrames:    INCLUDE "gfx/pokemon/steelix/frames.asm"
SnubbullFrames:   INCLUDE "gfx/pokemon/snubbull/frames.asm"
GranbullFrames:   INCLUDE "gfx/pokemon/granbull/frames.asm"
ScizorFrames:     INCLUDE "gfx/pokemon/scizor/frames.asm"
ShuckleFrames:    INCLUDE "gfx/pokemon/shuckle/frames.asm"
HeracrossFrames:  INCLUDE "gfx/pokemon/heracross/frames.asm"
TeddiursaFrames:  INCLUDE "gfx/pokemon/teddiursa/frames.asm"
UrsaringFrames:   INCLUDE "gfx/pokemon/ursaring/frames.asm"
SwinubFrames:     INCLUDE "gfx/pokemon/swinub/frames.asm"
PiloswineFrames:  INCLUDE "gfx/pokemon/piloswine/frames.asm"
RemoraidFrames:   INCLUDE "gfx/pokemon/remoraid/frames.asm"
OctilleryFrames:  INCLUDE "gfx/pokemon/octillery/frames.asm"
DelibirdFrames:   INCLUDE "gfx/pokemon/delibird/frames.asm"
MantineFrames:    INCLUDE "gfx/pokemon/mantine/frames.asm"
SkarmoryFrames:   INCLUDE "gfx/pokemon/skarmory/frames.asm"
HoundourFrames:   INCLUDE "gfx/pokemon/houndour/frames.asm"
HoundoomFrames:   INCLUDE "gfx/pokemon/houndoom/frames.asm"
KingdraFrames:    INCLUDE "gfx/pokemon/kingdra/frames.asm"
ElekidFrames:     INCLUDE "gfx/pokemon/elekid/frames.asm"
MagbyFrames:      INCLUDE "gfx/pokemon/magby/frames.asm"
RaikouFrames:     INCLUDE "gfx/pokemon/raikou/frames.asm"
EnteiFrames:      INCLUDE "gfx/pokemon/entei/frames.asm"
SuicuneFrames:    INCLUDE "gfx/pokemon/suicune/frames.asm"
LarvitarFrames:   INCLUDE "gfx/pokemon/larvitar/frames.asm"
PupitarFrames:    INCLUDE "gfx/pokemon/pupitar/frames.asm"
TyranitarFrames:  INCLUDE "gfx/pokemon/tyranitar/frames.asm"
LugiaFrames:      INCLUDE "gfx/pokemon/lugia/frames.asm"
HoOhFrames:       INCLUDE "gfx/pokemon/ho_oh/frames.asm"
CelebiFrames:     INCLUDE "gfx/pokemon/celebi/frames.asm"
AzurillFrames:    INCLUDE "gfx/pokemon/azurill/frames.asm"
MismagiusFrames:  INCLUDE "gfx/pokemon/mismagius/frames.asm"
HonchkrowFrames:  INCLUDE "gfx/pokemon/honchkrow/frames.asm"
BonslyFrames:     INCLUDE "gfx/pokemon/bonsly/frames.asm"
MimeJrFrames:     INCLUDE "gfx/pokemon/mime_jr_/frames.asm"
MunchlaxFrames:   INCLUDE "gfx/pokemon/munchlax/frames.asm"
MantykeFrames:    INCLUDE "gfx/pokemon/mantyke/frames.asm"
WeavileFrames:    INCLUDE "gfx/pokemon/weavile/frames.asm"
MagnezoneFrames:  INCLUDE "gfx/pokemon/magnezone/frames.asm"
LickilickyFrames: INCLUDE "gfx/pokemon/lickilicky/frames.asm"
TangrowthFrames:  INCLUDE "gfx/pokemon/tangrowth/frames.asm"
ElectivireFrames: INCLUDE "gfx/pokemon/electivire/frames.asm"
MagmortarFrames:  INCLUDE "gfx/pokemon/magmortar/frames.asm"
TogekissFrames:   INCLUDE "gfx/pokemon/togekiss/frames.asm"
YanmegaFrames:    INCLUDE "gfx/pokemon/yanmega/frames.asm"
LeafeonFrames:    INCLUDE "gfx/pokemon/leafeon/frames.asm"
GlaceonFrames:    INCLUDE "gfx/pokemon/glaceon/frames.asm"
GliscorFrames:    INCLUDE "gfx/pokemon/gliscor/frames.asm"
MamoswineFrames:  INCLUDE "gfx/pokemon/mamoswine/frames.asm"
SylveonFrames:    INCLUDE "gfx/pokemon/sylveon/frames.asm"
PerrserkerFrames: INCLUDE "gfx/pokemon/perrserker/frames.asm"
CursolaFrames:    INCLUDE "gfx/pokemon/cursola/frames.asm"
SirfetchDFrames:  INCLUDE "gfx/pokemon/sirfetch_d/frames.asm"
MrRimeFrames:     INCLUDE "gfx/pokemon/mr__rime/frames.asm"
KleavorFrames:    INCLUDE "gfx/pokemon/kleavor/frames.asm"
SneaslerFrames:   INCLUDE "gfx/pokemon/sneasler/frames.asm"
OverqwilFrames:   INCLUDE "gfx/pokemon/overqwil/frames.asm"
ClodsireFrames:   INCLUDE "gfx/pokemon/clodsire/frames.asm"
AnnihilapeFrames: INCLUDE "gfx/pokemon/annihilape/frames.asm"
SnivyFrames:      INCLUDE "gfx/pokemon/snivy/frames.asm"
ServineFrames:    INCLUDE "gfx/pokemon/servine/frames.asm"
SerperiorFrames:  INCLUDE "gfx/pokemon/serperior/frames.asm"
TepigFrames:      INCLUDE "gfx/pokemon/tepig/frames.asm"
PigniteFrames:    INCLUDE "gfx/pokemon/pignite/frames.asm"
EmboarFrames:     INCLUDE "gfx/pokemon/emboar/frames.asm"
OshawottFrames:   INCLUDE "gfx/pokemon/oshawott/frames.asm"
DewottFrames:     INCLUDE "gfx/pokemon/dewott/frames.asm"
PatratFrames:     INCLUDE "gfx/pokemon/patrat/frames.asm"
WatchogFrames:    INCLUDE "gfx/pokemon/watchog/frames.asm"
LillipupFrames:   INCLUDE "gfx/pokemon/lillipup/frames.asm"
HerdierFrames:    INCLUDE "gfx/pokemon/herdier/frames.asm"
StoutlandFrames:  INCLUDE "gfx/pokemon/stoutland/frames.asm"
PurrloinFrames:   INCLUDE "gfx/pokemon/purrloin/frames.asm"
LiepardFrames:    INCLUDE "gfx/pokemon/liepard/frames.asm"
MunnaFrames:      INCLUDE "gfx/pokemon/munna/frames.asm"
MusharnaFrames:   INCLUDE "gfx/pokemon/musharna/frames.asm"
PidoveFrames:     INCLUDE "gfx/pokemon/pidove/frames.asm"
TranquillFrames:  INCLUDE "gfx/pokemon/tranquill/frames.asm"
BlitzleFrames:    INCLUDE "gfx/pokemon/blitzle/frames.asm"
ZebstrikaFrames:  INCLUDE "gfx/pokemon/zebstrika/frames.asm"
RoggenrolaFrames: INCLUDE "gfx/pokemon/roggenrola/frames.asm"
BoldoreFrames:    INCLUDE "gfx/pokemon/boldore/frames.asm"
GigalithFrames:   INCLUDE "gfx/pokemon/gigalith/frames.asm"
WoobatFrames:     INCLUDE "gfx/pokemon/woobat/frames.asm"
SwoobatFrames:    INCLUDE "gfx/pokemon/swoobat/frames.asm"
DrilburFrames:    INCLUDE "gfx/pokemon/drilbur/frames.asm"
ExcadrillFrames:  INCLUDE "gfx/pokemon/excadrill/frames.asm"
AudinoFrames:     INCLUDE "gfx/pokemon/audino/frames.asm"
TimburrFrames:    INCLUDE "gfx/pokemon/timburr/frames.asm"
GurdurrFrames:    INCLUDE "gfx/pokemon/gurdurr/frames.asm"
ConkeldurrFrames: INCLUDE "gfx/pokemon/conkeldurr/frames.asm"
TympoleFrames:    INCLUDE "gfx/pokemon/tympole/frames.asm"
PalpitoadFrames:  INCLUDE "gfx/pokemon/palpitoad/frames.asm"
SeismitoadFrames: INCLUDE "gfx/pokemon/seismitoad/frames.asm"
ThrohFrames:      INCLUDE "gfx/pokemon/throh/frames.asm"
SawkFrames:       INCLUDE "gfx/pokemon/sawk/frames.asm"
SewaddleFrames:   INCLUDE "gfx/pokemon/sewaddle/frames.asm"
SwadloonFrames:   INCLUDE "gfx/pokemon/swadloon/frames.asm"
LeavannyFrames:   INCLUDE "gfx/pokemon/leavanny/frames.asm"
VenipedeFrames:   INCLUDE "gfx/pokemon/venipede/frames.asm"
WhirlipedeFrames: INCLUDE "gfx/pokemon/whirlipede/frames.asm"
ScolipedeFrames:  INCLUDE "gfx/pokemon/scolipede/frames.asm"
CottoneeFrames:   INCLUDE "gfx/pokemon/cottonee/frames.asm"
WhimsicottFrames: INCLUDE "gfx/pokemon/whimsicott/frames.asm"
PetililFrames:    INCLUDE "gfx/pokemon/petilil/frames.asm"
SandileFrames:    INCLUDE "gfx/pokemon/sandile/frames.asm"
KrokorokFrames:   INCLUDE "gfx/pokemon/krokorok/frames.asm"
KrookodileFrames: INCLUDE "gfx/pokemon/krookodile/frames.asm"
MaractusFrames:   INCLUDE "gfx/pokemon/maractus/frames.asm"
DwebbleFrames:    INCLUDE "gfx/pokemon/dwebble/frames.asm"
CrustleFrames:    INCLUDE "gfx/pokemon/crustle/frames.asm"
ScraggyFrames:    INCLUDE "gfx/pokemon/scraggy/frames.asm"
ScraftyFrames:    INCLUDE "gfx/pokemon/scrafty/frames.asm"
SigilyphFrames:   INCLUDE "gfx/pokemon/sigilyph/frames.asm"
CofagrigusFrames: INCLUDE "gfx/pokemon/cofagrigus/frames.asm"
TirtougaFrames:   INCLUDE "gfx/pokemon/tirtouga/frames.asm"
CarracostaFrames: INCLUDE "gfx/pokemon/carracosta/frames.asm"
ArchenFrames:     INCLUDE "gfx/pokemon/archen/frames.asm"
ArcheopsFrames:   INCLUDE "gfx/pokemon/archeops/frames.asm"
TrubbishFrames:   INCLUDE "gfx/pokemon/trubbish/frames.asm"
GarbodorFrames:   INCLUDE "gfx/pokemon/garbodor/frames.asm"
GothitaFrames:    INCLUDE "gfx/pokemon/gothita/frames.asm"
GothoritaFrames:  INCLUDE "gfx/pokemon/gothorita/frames.asm"
GothitelleFrames: INCLUDE "gfx/pokemon/gothitelle/frames.asm"
SolosisFrames:    INCLUDE "gfx/pokemon/solosis/frames.asm"
DuosionFrames:    INCLUDE "gfx/pokemon/duosion/frames.asm"
ReuniclusFrames:  INCLUDE "gfx/pokemon/reuniclus/frames.asm"
DucklettFrames:   INCLUDE "gfx/pokemon/ducklett/frames.asm"
SwannaFrames:     INCLUDE "gfx/pokemon/swanna/frames.asm"
VanilliteFrames:  INCLUDE "gfx/pokemon/vanillite/frames.asm"
VanillishFrames:  INCLUDE "gfx/pokemon/vanillish/frames.asm"
VanilluxeFrames:  INCLUDE "gfx/pokemon/vanilluxe/frames.asm"
EmolgaFrames:     INCLUDE "gfx/pokemon/emolga/frames.asm"
KarrablastFrames: INCLUDE "gfx/pokemon/karrablast/frames.asm"
EscavalierFrames: INCLUDE "gfx/pokemon/escavalier/frames.asm"
FoongusFrames:    INCLUDE "gfx/pokemon/foongus/frames.asm"
AmoongussFrames:  INCLUDE "gfx/pokemon/amoonguss/frames.asm"
JoltikFrames:     INCLUDE "gfx/pokemon/joltik/frames.asm"
GalvantulaFrames: INCLUDE "gfx/pokemon/galvantula/frames.asm"
FerroseedFrames:  INCLUDE "gfx/pokemon/ferroseed/frames.asm"
FerrothornFrames: INCLUDE "gfx/pokemon/ferrothorn/frames.asm"

EggFrames:        INCLUDE "gfx/pokemon/egg/frames.asm"

UnownAFrames: INCLUDE "gfx/pokemon/unown_a/frames.asm"
UnownBFrames: INCLUDE "gfx/pokemon/unown_b/frames.asm"
UnownCFrames: INCLUDE "gfx/pokemon/unown_c/frames.asm"
UnownDFrames: INCLUDE "gfx/pokemon/unown_d/frames.asm"
UnownEFrames: INCLUDE "gfx/pokemon/unown_e/frames.asm"
UnownFFrames: INCLUDE "gfx/pokemon/unown_f/frames.asm"
UnownGFrames: INCLUDE "gfx/pokemon/unown_g/frames.asm"
UnownHFrames: INCLUDE "gfx/pokemon/unown_h/frames.asm"
UnownIFrames: INCLUDE "gfx/pokemon/unown_i/frames.asm"
UnownJFrames: INCLUDE "gfx/pokemon/unown_j/frames.asm"
UnownKFrames: INCLUDE "gfx/pokemon/unown_k/frames.asm"
UnownLFrames: INCLUDE "gfx/pokemon/unown_l/frames.asm"
UnownMFrames: INCLUDE "gfx/pokemon/unown_m/frames.asm"
UnownNFrames: INCLUDE "gfx/pokemon/unown_n/frames.asm"
UnownOFrames: INCLUDE "gfx/pokemon/unown_o/frames.asm"
UnownPFrames: INCLUDE "gfx/pokemon/unown_p/frames.asm"
UnownQFrames: INCLUDE "gfx/pokemon/unown_q/frames.asm"
UnownRFrames: INCLUDE "gfx/pokemon/unown_r/frames.asm"
UnownSFrames: INCLUDE "gfx/pokemon/unown_s/frames.asm"
UnownTFrames: INCLUDE "gfx/pokemon/unown_t/frames.asm"
UnownUFrames: INCLUDE "gfx/pokemon/unown_u/frames.asm"
UnownVFrames: INCLUDE "gfx/pokemon/unown_v/frames.asm"
UnownWFrames: INCLUDE "gfx/pokemon/unown_w/frames.asm"
UnownXFrames: INCLUDE "gfx/pokemon/unown_x/frames.asm"
UnownYFrames: INCLUDE "gfx/pokemon/unown_y/frames.asm"
UnownZFrames: INCLUDE "gfx/pokemon/unown_z/frames.asm"
UnownExclamationFrames: INCLUDE "gfx/pokemon/unown_exclamation/frames.asm"
UnownQuestionFrames:    INCLUDE "gfx/pokemon/unown_question/frames.asm"

PichuPlainFrames: INCLUDE "gfx/pokemon/pichu_plain/frames.asm"
PichuSpikyFrames: INCLUDE "gfx/pokemon/pichu_spiky/frames.asm"

SlowkingPlainFrames:    INCLUDE "gfx/pokemon/slowking_plain/frames.asm"
SlowkingGalarianFrames: INCLUDE "gfx/pokemon/slowking_galarian/frames.asm"

CorsolaPlainFrames:    INCLUDE "gfx/pokemon/corsola_plain/frames.asm"
CorsolaGalarianFrames: INCLUDE "gfx/pokemon/corsola_galarian/frames.asm"

TyphlosionPlainFrames:   INCLUDE "gfx/pokemon/typhlosion_plain/frames.asm"
TyphlosionHisuianFrames: INCLUDE "gfx/pokemon/typhlosion_hisuian/frames.asm"

QwilfishPlainFrames:   INCLUDE "gfx/pokemon/qwilfish_plain/frames.asm"
QwilfishHisuianFrames: INCLUDE "gfx/pokemon/qwilfish_hisuian/frames.asm"

SneaselPlainFrames:   INCLUDE "gfx/pokemon/sneasel_plain/frames.asm"
SneaselHisuianFrames: INCLUDE "gfx/pokemon/sneasel_hisuian/frames.asm"

DudunsparceTwoSegmentFrames:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/frames.asm"
DudunsparceThreeSegmentFrames: INCLUDE "gfx/pokemon/dudunsparce_three_segment/frames.asm"

WooperPlainFrames:   INCLUDE "gfx/pokemon/wooper_plain/frames.asm"
WooperPaldeanFrames: INCLUDE "gfx/pokemon/wooper_paldean/frames.asm"

UrsalunaPlainFrames:     INCLUDE "gfx/pokemon/ursaluna_plain/frames.asm"
UrsalunaBloodmoonFrames: INCLUDE "gfx/pokemon/ursaluna_bloodmoon/frames.asm"

UnfezantMaleFrames:   INCLUDE "gfx/pokemon/unfezant_male/frames.asm"
UnfezantFemaleFrames: INCLUDE "gfx/pokemon/unfezant_female/frames.asm"

SamurottPlainFrames: INCLUDE "gfx/pokemon/samurott_plain/frames.asm"

LilligantPlainFrames: INCLUDE "gfx/pokemon/lilligant_plain/frames.asm"

BasculinRedFrames: INCLUDE "gfx/pokemon/basculin_red/frames.asm"

DarumakaPlainFrames: INCLUDE "gfx/pokemon/darumaka_plain/frames.asm"

DarmanitanPlainFrames: INCLUDE "gfx/pokemon/darmanitan_plain/frames.asm"

YamaskPlainFrames: INCLUDE "gfx/pokemon/yamask_plain/frames.asm"

ZoruaPlainFrames: INCLUDE "gfx/pokemon/zorua_plain/frames.asm"

ZoroarkPlainFrames: INCLUDE "gfx/pokemon/zoroark_plain/frames.asm"

DeerlingSpringFrames: INCLUDE "gfx/pokemon/deerling_spring/frames.asm"

SawsbuckSpringFrames: INCLUDE "gfx/pokemon/sawsbuck_spring/frames.asm"

FrillishMaleFrames:   INCLUDE "gfx/pokemon/frillish_male/frames.asm"

JellicentMaleFrames:   INCLUDE "gfx/pokemon/jellicent_male/frames.asm"
