KantoFrames:

BulbasaurFrames:  INCLUDE "gfx/pokemon/bulbasaur/frames.asm"
IvysaurFrames:    INCLUDE "gfx/pokemon/ivysaur/frames.asm"
VenusaurFrames:   INCLUDE "gfx/pokemon/venusaur/frames.asm"
CharmanderFrames: INCLUDE "gfx/pokemon/charmander/frames.asm"
CharmeleonFrames: INCLUDE "gfx/pokemon/charmeleon/frames.asm"
CharizardFrames:  INCLUDE "gfx/pokemon/charizard/frames.asm"
SquirtleFrames:   INCLUDE "gfx/pokemon/squirtle/frames.asm"
WartortleFrames:  INCLUDE "gfx/pokemon/wartortle/frames.asm"
BlastoiseFrames:  INCLUDE "gfx/pokemon/blastoise/frames.asm"
NidoranFFrames:   INCLUDE "gfx/pokemon/nidoran_f/frames.asm"
NidorinaFrames:   INCLUDE "gfx/pokemon/nidorina/frames.asm"
NidoqueenFrames:  INCLUDE "gfx/pokemon/nidoqueen/frames.asm"
NidoranMFrames:   INCLUDE "gfx/pokemon/nidoran_m/frames.asm"
NidorinoFrames:   INCLUDE "gfx/pokemon/nidorino/frames.asm"
NidokingFrames:   INCLUDE "gfx/pokemon/nidoking/frames.asm"
ClefairyFrames:   INCLUDE "gfx/pokemon/clefairy/frames.asm"
ClefableFrames:   INCLUDE "gfx/pokemon/clefable/frames.asm"
JigglypuffFrames: INCLUDE "gfx/pokemon/jigglypuff/frames.asm"
WigglytuffFrames: INCLUDE "gfx/pokemon/wigglytuff/frames.asm"
ZubatFrames:      INCLUDE "gfx/pokemon/zubat/frames.asm"
GolbatFrames:     INCLUDE "gfx/pokemon/golbat/frames.asm"
ParasFrames:      INCLUDE "gfx/pokemon/paras/frames.asm"
ParasectFrames:   INCLUDE "gfx/pokemon/parasect/frames.asm"
PsyduckFrames:    INCLUDE "gfx/pokemon/psyduck/frames.asm"
GolduckFrames:    INCLUDE "gfx/pokemon/golduck/frames.asm"
MankeyFrames:     INCLUDE "gfx/pokemon/mankey/frames.asm"
PrimeapeFrames:   INCLUDE "gfx/pokemon/primeape/frames.asm"
PoliwagFrames:    INCLUDE "gfx/pokemon/poliwag/frames.asm"
PoliwhirlFrames:  INCLUDE "gfx/pokemon/poliwhirl/frames.asm"
PoliwrathFrames:  INCLUDE "gfx/pokemon/poliwrath/frames.asm"
MagnemiteFrames:  INCLUDE "gfx/pokemon/magnemite/frames.asm"
MagnetonFrames:   INCLUDE "gfx/pokemon/magneton/frames.asm"
SeelFrames:       INCLUDE "gfx/pokemon/seel/frames.asm"
DewgongFrames:    INCLUDE "gfx/pokemon/dewgong/frames.asm"
GastlyFrames:     INCLUDE "gfx/pokemon/gastly/frames.asm"
HaunterFrames:    INCLUDE "gfx/pokemon/haunter/frames.asm"
GengarFrames:     INCLUDE "gfx/pokemon/gengar/frames.asm"
OnixFrames:       INCLUDE "gfx/pokemon/onix/frames.asm"
ExeggcuteFrames:  INCLUDE "gfx/pokemon/exeggcute/frames.asm"
LickitungFrames:  INCLUDE "gfx/pokemon/lickitung/frames.asm"
KoffingFrames:    INCLUDE "gfx/pokemon/koffing/frames.asm"
TangelaFrames:    INCLUDE "gfx/pokemon/tangela/frames.asm"
KangaskhanFrames: INCLUDE "gfx/pokemon/kangaskhan/frames.asm"
HorseaFrames:     INCLUDE "gfx/pokemon/horsea/frames.asm"
SeadraFrames:     INCLUDE "gfx/pokemon/seadra/frames.asm"
StaryuFrames:     INCLUDE "gfx/pokemon/staryu/frames.asm"
StarmieFrames:    INCLUDE "gfx/pokemon/starmie/frames.asm"
ScytherFrames:    INCLUDE "gfx/pokemon/scyther/frames.asm"
ElectabuzzFrames: INCLUDE "gfx/pokemon/electabuzz/frames.asm"
MagmarFrames:     INCLUDE "gfx/pokemon/magmar/frames.asm"
PinsirFrames:     INCLUDE "gfx/pokemon/pinsir/frames.asm"
LaprasFrames:     INCLUDE "gfx/pokemon/lapras/frames.asm"
DittoFrames:      INCLUDE "gfx/pokemon/ditto/frames.asm"
EeveeFrames:      INCLUDE "gfx/pokemon/eevee/frames.asm"
VaporeonFrames:   INCLUDE "gfx/pokemon/vaporeon/frames.asm"
JolteonFrames:    INCLUDE "gfx/pokemon/jolteon/frames.asm"
FlareonFrames:    INCLUDE "gfx/pokemon/flareon/frames.asm"
SnorlaxFrames:    INCLUDE "gfx/pokemon/snorlax/frames.asm"
DratiniFrames:    INCLUDE "gfx/pokemon/dratini/frames.asm"
DragonairFrames:  INCLUDE "gfx/pokemon/dragonair/frames.asm"
DragoniteFrames:  INCLUDE "gfx/pokemon/dragonite/frames.asm"
MewFrames:        INCLUDE "gfx/pokemon/mew/frames.asm"

PikachuPlainFrames:  INCLUDE "gfx/pokemon/pikachu_plain/frames.asm"
PikachuFlyFrames:    INCLUDE "gfx/pokemon/pikachu_fly/frames.asm"
PikachuSurfFrames:   INCLUDE "gfx/pokemon/pikachu_surf/frames.asm"
PikachuPikaFrames:   INCLUDE "gfx/pokemon/pikachu_pika/frames.asm"
PikachuChuchuFrames: INCLUDE "gfx/pokemon/pikachu_chuchu/frames.asm"
PikachuSparkFrames:  INCLUDE "gfx/pokemon/pikachu_spark/frames.asm"

MewtwoPlainFrames:   INCLUDE "gfx/pokemon/mewtwo_plain/frames.asm"
MewtwoArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"

RattataPlainFrames:  INCLUDE "gfx/pokemon/rattata_plain/frames.asm"
RattataAlolanFrames: INCLUDE "gfx/pokemon/rattata_alolan/frames.asm"

RaticatePlainFrames:  INCLUDE "gfx/pokemon/raticate_plain/frames.asm"
RaticateAlolanFrames: INCLUDE "gfx/pokemon/raticate_alolan/frames.asm"

RaichuPlainFrames:  INCLUDE "gfx/pokemon/raichu_plain/frames.asm"
RaichuAlolanFrames: INCLUDE "gfx/pokemon/raichu_alolan/frames.asm"

SandshrewPlainFrames:  INCLUDE "gfx/pokemon/sandshrew_plain/frames.asm"
SandshrewAlolanFrames: INCLUDE "gfx/pokemon/sandshrew_alolan/frames.asm"

SandslashPlainFrames:  INCLUDE "gfx/pokemon/sandslash_plain/frames.asm"
SandslashAlolanFrames: INCLUDE "gfx/pokemon/sandslash_alolan/frames.asm"

VulpixPlainFrames:  INCLUDE "gfx/pokemon/vulpix_plain/frames.asm"
VulpixAlolanFrames: INCLUDE "gfx/pokemon/vulpix_alolan/frames.asm"

NinetalesPlainFrames:  INCLUDE "gfx/pokemon/ninetales_plain/frames.asm"
NinetalesAlolanFrames: INCLUDE "gfx/pokemon/ninetales_alolan/frames.asm"

MeowthPlainFrames:    INCLUDE "gfx/pokemon/meowth_plain/frames.asm"
MeowthAlolanFrames:   INCLUDE "gfx/pokemon/meowth_alolan/frames.asm"
MeowthGalarianFrames: INCLUDE "gfx/pokemon/meowth_galarian/frames.asm"

PersianPlainFrames:  INCLUDE "gfx/pokemon/persian_plain/frames.asm"
PersianAlolanFrames: INCLUDE "gfx/pokemon/persian_alolan/frames.asm"

GeodudePlainFrames:  INCLUDE "gfx/pokemon/geodude_plain/frames.asm"
GeodudeAlolanFrames: INCLUDE "gfx/pokemon/geodude_alolan/frames.asm"

GravelerPlainFrames:  INCLUDE "gfx/pokemon/graveler_plain/frames.asm"
GravelerAlolanFrames: INCLUDE "gfx/pokemon/graveler_alolan/frames.asm"

GolemPlainFrames:  INCLUDE "gfx/pokemon/golem_plain/frames.asm"
GolemAlolanFrames: INCLUDE "gfx/pokemon/golem_alolan/frames.asm"

GrimerPlainFrames:  INCLUDE "gfx/pokemon/grimer_plain/frames.asm"
GrimerAlolanFrames: INCLUDE "gfx/pokemon/grimer_alolan/frames.asm"

MukPlainFrames:  INCLUDE "gfx/pokemon/muk_plain/frames.asm"
MukAlolanFrames: INCLUDE "gfx/pokemon/muk_alolan/frames.asm"

ExeggutorPlainFrames:  INCLUDE "gfx/pokemon/exeggutor_plain/frames.asm"
ExeggutorAlolanFrames: INCLUDE "gfx/pokemon/exeggutor_alolan/frames.asm"

PonytaPlainFrames:    INCLUDE "gfx/pokemon/ponyta_plain/frames.asm"
PonytaGalarianFrames: INCLUDE "gfx/pokemon/ponyta_galarian/frames.asm"

RapidashPlainFrames:    INCLUDE "gfx/pokemon/rapidash_plain/frames.asm"
RapidashGalarianFrames: INCLUDE "gfx/pokemon/rapidash_galarian/frames.asm"

SlowpokePlainFrames:   INCLUDE "gfx/pokemon/slowpoke_plain/frames.asm"
SlowpokeGalarianFrames: INCLUDE "gfx/pokemon/slowpoke_galarian/frames.asm"

SlowbroPlainFrames:    INCLUDE "gfx/pokemon/slowbro_plain/frames.asm"
SlowbroGalarianFrames: INCLUDE "gfx/pokemon/slowbro_galarian/frames.asm"

WeezingPlainFrames:    INCLUDE "gfx/pokemon/weezing_plain/frames.asm"
WeezingGalarianFrames: INCLUDE "gfx/pokemon/weezing_galarian/frames.asm"

MrMimePlainFrames:    INCLUDE "gfx/pokemon/mr__mime_plain/frames.asm"
MrMimeGalarianFrames: INCLUDE "gfx/pokemon/mr__mime_galarian/frames.asm"

GrowlithePlainFrames:   INCLUDE "gfx/pokemon/growlithe_plain/frames.asm"
GrowlitheHisuianFrames: INCLUDE "gfx/pokemon/growlithe_hisuian/frames.asm"

ArcaninePlainFrames:   INCLUDE "gfx/pokemon/arcanine_plain/frames.asm"
ArcanineHisuianFrames: INCLUDE "gfx/pokemon/arcanine_hisuian/frames.asm"
